import type { SectionDefinition } from "@/types/requirements";

export const driversSection: SectionDefinition = {
  id: "drivers",
  name: "Drivers & Circulation Ledger",
  nameDari: "چلوونکي و کتابجه ګردش",
  enableReview: true,
  description:
    "Driver register for Items tracking only — separate from HR employees. Used for oil/item holder sub accounts and کتابجه ګردش activity records (asphalt پخته, gravel خامه, km).",
  status: "draft",
  currentTool: "Paper driver register and circulation book",
  summary: [
    "Driver master — name, father name, unique_id, active, start date; not HR employee data",
    "Drivers linked to product sub accounts for oil and item tracking",
    "کتابجه ګردش — per-trip/activity record: driver, mali_year, date, km optional, asphalt and/or gravel amounts",
    "At least one of asphalt (پخته) or gravel (خامه) required per circulation entry; both allowed",
    "Driver active flag controls use in new vouchers and circulation entries",
  ],
  precededBy: [],
  relatedSections: ["items-product-ledger"],
  roles: [
    {
      role: "Items Accountant",
      location: "HQ — محاسبه اجناس",
      mainActions: "Register drivers, record کتابجه ګردش entries",
      approval: false,
      readOnly: false,
    },
    {
      role: "Branch Responsible",
      location: "Site",
      mainActions: "Submit circulation entries for drivers in branch",
      approval: false,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View driver register and circulation history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-ITM-030",
      name: "Driver",
      description:
        "Driver register for Items module only — activity and inventory tracking. Not the HR employee master.",
      fields: [
        {
          name: "unique_id",
          label: "Driver ID",
          labelDari: "شناسه چلوونکی",
          meaning: "System-generated unique driver number",
          type: "text",
          required: true,
          example: "DRV-0012",
          rules: "Auto-generated; unique",
        },
        {
          name: "name",
          label: "Name",
          labelDari: "نام",
          meaning: "Driver full name",
          type: "text",
          required: true,
          example: "Ahmad",
        },
        {
          name: "father_name",
          label: "Father Name",
          labelDari: "نام پدر",
          meaning: "Father's name — required for identification",
          type: "text",
          required: true,
          example: "Mohammad",
        },
        {
          name: "active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Whether driver can receive new items and circulation entries",
          type: "boolean",
          required: true,
          example: "true",
        },
        {
          name: "start_date",
          label: "Start Date",
          labelDari: "تاریخ شروع",
          meaning: "When driver started — for tracking only",
          type: "hijri_date",
          required: true,
          example: "1404/06/01",
        },
        {
          name: "branch_id",
          label: "Home Branch",
          labelDari: "شعبه",
          meaning: "Primary branch for this driver",
          type: "reference",
          required: false,
          example: "Branch A",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Optional internal notes",
          type: "longtext",
          required: false,
          example: "Heavy truck licence",
        },
      ],
    },
    {
      id: "ENT-ITM-031",
      name: "Circulation Ledger Entry (کتابجه ګردش)",
      description:
        "Activity record per driver — tracks asphalt (پخته), gravel (خامه), and optional km. Separate from oil movement vouchers but linked to same driver.",
      fields: [
        {
          name: "unique_number",
          label: "System Number",
          labelDari: "شماره سیستم",
          meaning: "Auto-generated entry number",
          type: "text",
          required: true,
          example: "CIR-0156/1405",
        },
        {
          name: "driver_id",
          label: "Driver",
          labelDari: "چلوونکی",
          meaning: "Reference → Driver (ENT-ITM-030)",
          type: "reference",
          required: true,
          example: "DRV-0012 — Ahmad",
        },
        {
          name: "mali_year",
          label: "Mali Year",
          labelDari: "سال مالی",
          meaning: "Fiscal year select (current ± 5)",
          type: "enum",
          required: true,
          example: "1405",
        },
        {
          name: "date",
          label: "Date",
          labelDari: "تاریخ",
          meaning: "Activity date",
          type: "hijri_date",
          required: true,
          example: "1405/03/10",
        },
        {
          name: "starting_km",
          label: "Starting KM",
          labelDari: "کیلومتر شروع",
          meaning: "Odometer at start — optional",
          type: "decimal",
          required: false,
          example: "125400",
        },
        {
          name: "end_km",
          label: "End KM",
          labelDari: "کیلومتر ختم",
          meaning: "Odometer at end — optional",
          type: "decimal",
          required: false,
          example: "125680",
        },
        {
          name: "amount_asphalt",
          label: "Asphalt Amount (پخته)",
          labelDari: "مقدار پخته",
          meaning: "Quantity of asphalt — پخته",
          type: "decimal",
          required: "conditional",
          example: "12.5",
          rules: "At least one of amount_asphalt or amount_gravel required",
        },
        {
          name: "amount_gravel",
          label: "Gravel Amount (خامه)",
          labelDari: "مقدار خامه",
          meaning: "Quantity of gravel — خامه",
          type: "decimal",
          required: "conditional",
          example: "8.0",
          rules: "At least one of amount_asphalt or amount_gravel required; both allowed on same entry",
        },
        {
          name: "details",
          label: "Details",
          labelDari: "جزئیات",
          meaning: "Route, project, or activity description",
          type: "longtext",
          required: false,
          example: "Road repair Kabul ring — section 4",
        },
        {
          name: "attachment",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional supporting document",
          type: "file",
          required: false,
          example: "circulation_scan.pdf",
        },
        {
          name: "created_by",
          label: "Created By",
          type: "reference",
          required: true,
          meaning: "Clerk who recorded entry",
          example: "Items Accountant",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-ITM-030",
      name: "Register driver",
      trigger: "New driver for item/oil tracking",
      startActor: "Items Accountant",
      endState: "Active driver available for sub accounts and circulation",
      steps: [
        { step: 1, actor: "Items Accountant", action: "Create driver", input: "name, father_name, start_date, branch", output: "DRV unique_id assigned" },
        { step: 2, actor: "Items Accountant", action: "Create product sub account for driver", input: "driver_id linked on items-product-ledger", output: "Holder sub account for oil/items" },
      ],
    },
    {
      id: "WF-ITM-031",
      name: "Record کتابجه ګردش",
      trigger: "Driver activity with asphalt and/or gravel",
      startActor: "Items Accountant / Branch Responsible",
      endState: "Circulation entry posted",
      steps: [
        { step: 1, actor: "Clerk", action: "Select active driver", input: "driver_id", output: "Circulation form" },
        { step: 2, actor: "Clerk", action: "Enter date, mali_year, km optional", input: "starting_km, end_km", output: "Header complete" },
        { step: 3, actor: "Clerk", action: "Enter asphalt and/or gravel", input: "At least one amount required", output: "Posted circulation entry" },
      ],
    },
  ],
  businessRules: [
    { id: "BR-ITM-030", rule: "Driver unique_id auto-generated and immutable", trigger: "Create", response: "System assigns DRV-####", severity: "Critical" },
    { id: "BR-ITM-031", rule: "Inactive drivers cannot receive new چګ صادره or circulation entries", trigger: "New voucher / circulation", response: "Block", severity: "Critical" },
    { id: "BR-ITM-032", rule: "کتابجه ګردش requires at least amount_asphalt or amount_gravel > 0", trigger: "Save entry", response: "Block if both empty", severity: "Critical" },
    { id: "BR-ITM-033", rule: "Both asphalt and gravel allowed on same circulation entry", trigger: "Save entry", response: "Allow", severity: "Medium" },
    { id: "BR-ITM-034", rule: "Driver register is Items-only — do not sync with HR employee master", trigger: "Integration", response: "Separate table", severity: "High" },
  ],
  permissionsMatrix: [
    { action: "Create / edit drivers", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "R" },
    { action: "Deactivate driver", archiveClerk: "—", executive: "A", deptStaff: "U", auditor: "—" },
    { action: "Record کتابجه ګردش", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "R" },
    { action: "View driver & circulation history", archiveClerk: "—", executive: "R", deptStaff: "R", auditor: "R" },
  ],
  reports: [
    {
      id: "RPT-ITM-030",
      name: "Driver Register",
      purpose: "All drivers with active status",
      filters: "Active, branch, start date",
      columns: "unique_id, name, father_name, branch, start_date, active",
      export: "PDF, Excel",
    },
    {
      id: "RPT-ITM-031",
      name: "Circulation Ledger (کتابجه ګردش)",
      purpose: "Asphalt and gravel activity per driver",
      filters: "Driver, mali_year, date range",
      columns: "date, driver, asphalt, gravel, km, details",
      export: "PDF, Excel",
    },
  ],
  crossModuleNotes: [
    "Drivers used only for Items tracking — oil holder sub accounts and circulation.",
    "Oil movements and spend still recorded in items-product-ledger; circulation is parallel activity log.",
  ],
  deliverableChecklist: [
    { item: "Driver master fields documented", done: true },
    { item: "کتابجه ګردش entry rules", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
