import type { SectionDefinition } from "@/types/requirements";

export const itemsProductLedgerSection: SectionDefinition = {
  id: "items-product-ledger",
  name: "Items Ledger & Movement Vouchers",
  nameDari: "دفتر اجناس و چګ صادره / چک وارده",
  enableReview: true,
  description:
    "Standalone Items department ledger. Account books (general + sub accounts) are separate from Product master. Products are selected on movement and spend lines — not on sub accounts. Spend confirmation supports multiple product lines per record. user_id tracks the person on movements and spend.",
  status: "draft",
  currentTool: "Paper account books, handwritten چګ صادره / چک وارده slips",
  summary: [
    "Independent task — account books and products are separate",
    "Product master — name, unit, description, image; code system-generated",
    "General account — ledger book (name, code, status, is_spend_account toggle)",
    "Sub account — name, account_id, code, status only (no product, holder, or balance fields)",
    "Products selected on movement lines and spend lines — multiple products per spend",
    "user_id on movement vouchers and spend — key for person-specific reports",
    "Daily and monthly reports plus filters by person, product, account, sub account",
    "Optional file attachment on vouchers and spend",
  ],
  precededBy: [],
  followedBy: [],
  relatedSections: [],
  roles: [
    {
      role: "Items Accountant",
      location: "HQ — محاسبه اجناس",
      mainActions: "Maintain products, account books, lots; post movements and spend",
      approval: false,
      readOnly: false,
    },
    {
      role: "Branch Responsible",
      location: "HQ / Site",
      mainActions: "Post چک وارده and چګ صادره",
      approval: false,
      readOnly: false,
    },
    {
      role: "Control Clerk",
      location: "HQ — کنترول",
      mainActions: "Confirm spend records",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View balances, movements, spend, and all reports",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-ITM-015",
      name: "Product",
      description: "Product master — not an account. Referenced on movement and spend lines.",
      fields: [
        {
          name: "name",
          label: "Product Name",
          labelDari: "نام جنس",
          meaning: "Display name",
          type: "text",
          required: true,
          example: "Engine Oil 20W-50",
        },
        {
          name: "code",
          label: "Product Code",
          labelDari: "کود جنس",
          meaning: "System-generated unique product code",
          type: "text",
          required: true,
          example: "PRD-0042",
          rules: "Auto-generated on create; read-only; unique",
        },
        {
          name: "unit",
          label: "Unit",
          labelDari: "واحد",
          meaning: "litre, piece, kg, etc.",
          type: "text",
          required: true,
          example: "litre",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Optional notes",
          type: "longtext",
          required: false,
          example: "Heavy vehicle engine oil",
        },
        {
          name: "image",
          label: "Product Image",
          labelDari: "عکس",
          meaning: "Optional photo",
          type: "file",
          required: false,
          example: "oil_product.jpg",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | inactive",
          type: "enum",
          required: true,
          example: "active",
        },
      ],
    },
    {
      id: "ENT-ITM-020",
      name: "Items General Account",
      description: "Ledger book — name, code, status. User marks is_spend_account when this book records consumption.",
      fields: [
        {
          name: "name",
          label: "Account Name",
          labelDari: "نام حساب / کتاب",
          meaning: "Book title",
          type: "text",
          required: true,
          example: "Oil & Supplies Ledger",
        },
        {
          name: "code",
          label: "Account Code",
          labelDari: "کود حساب",
          meaning: "Unique book code",
          type: "text",
          required: true,
          example: "ITM-1100",
          rules: "Unique; immutable after first posted movement",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | inactive",
          type: "enum",
          required: true,
          example: "active",
        },
        {
          name: "is_spend_account",
          label: "Spend Account",
          labelDari: "حساب مصرف",
          meaning: "When true, this book receives confirmed spend quantities",
          type: "boolean",
          required: true,
          example: "false",
          rules: "User selects at setup — replaces account_type enum",
        },
      ],
    },
    {
      id: "ENT-ITM-021",
      name: "Items Sub Account",
      description: "Detail account under a ledger book — holder or branch label only. Products are chosen on transaction lines, not here.",
      fields: [
        {
          name: "name",
          label: "Sub Account Name",
          labelDari: "نام حساب فرعی",
          meaning: "e.g. Branch A, Driver Ahmad, Store Room",
          type: "text",
          required: true,
          example: "Branch A Responsible",
        },
        {
          name: "account_id",
          label: "General Account",
          labelDari: "حساب عمومی / کتاب",
          meaning: "Reference → Items General Account (ENT-ITM-020)",
          type: "reference",
          required: true,
          example: "ITM-1100 — Oil & Supplies Ledger",
        },
        {
          name: "code",
          label: "Sub Account Code",
          labelDari: "کود",
          meaning: "Unique within parent account",
          type: "text",
          required: true,
          example: "ITM-1100-BA",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | inactive",
          type: "enum",
          required: true,
          example: "active",
        },
      ],
    },
    {
      id: "ENT-ITM-022",
      name: "Product Stock Lot",
      description: "Price batch per product.",
      fields: [
        { name: "product_id", label: "Product", labelDari: "جنس", meaning: "Reference → Product", type: "reference", required: true, example: "PRD-0042" },
        { name: "lot_number", label: "Lot Number", labelDari: "شماره لوت", meaning: "System lot id", type: "text", required: true, example: "LOT-03/1405" },
        { name: "unit_price", label: "Unit Price", labelDari: "قیمت واحد", meaning: "Price per unit", type: "decimal", required: true, example: "85.50" },
        { name: "quantity_received", label: "Qty Received", labelDari: "مقدار ورودی", meaning: "Original quantity", type: "decimal", required: true, example: "5000" },
        { name: "quantity_remaining", label: "Qty Remaining", labelDari: "باقیمانده", meaning: "Still available", type: "decimal", required: true, example: "3200" },
        { name: "mali_year", label: "Mali Year", labelDari: "سال مالی", meaning: "Fiscal year", type: "enum", required: true, example: "1405" },
        { name: "received_date", label: "Received Date", labelDari: "تاریخ", type: "hijri_date", required: true, meaning: "When lot opened", example: "1405/01/15" },
        { name: "status", label: "Status", labelDari: "وضعیت", meaning: "open | depleted | closed", type: "enum", required: true, example: "open" },
      ],
    },
    {
      id: "ENT-ITM-023",
      name: "Items Movement Voucher (چګ صادره / چک وارده)",
      description: "Movement between sub accounts. Products on lines. user_id identifies the person related to this movement.",
      fields: [
        { name: "unique_number", label: "System Number", labelDari: "شماره سیستم", meaning: "Auto-generated", type: "text", required: true, example: "IMV-0088/1405" },
        { name: "paper_number", label: "Paper Number", labelDari: "شماره کاغذی", meaning: "Optional", type: "text", required: false, example: "45/1405" },
        { name: "direction", label: "Direction", labelDari: "جهت", meaning: "out (چګ صادره) | in (چک وارده)", type: "enum", required: true, example: "out" },
        { name: "date", label: "Date", labelDari: "تاریخ", type: "hijri_date", required: true, meaning: "Voucher date", example: "1405/03/10" },
        { name: "mali_year", label: "Mali Year", labelDari: "سال مالی", type: "enum", required: true, meaning: "Fiscal year select", example: "1405" },
        { name: "description", label: "Description", labelDari: "توضیحات", type: "longtext", required: true, meaning: "Summary", example: "Issue oil to Ahmad" },
        { name: "user_id", label: "Related Person", labelDari: "شخص مربوط", type: "reference", required: true, meaning: "Employee or person this movement relates to — used in person reports", example: "Karim — Branch A" },
        { name: "from_sub_account_id", label: "From Sub Account", labelDari: "از حساب فرعی", type: "reference", required: "conditional", meaning: "Source on چګ صادره", example: "ITM-1100-BA" },
        { name: "to_sub_account_id", label: "To Sub Account", labelDari: "به حساب فرعی", type: "reference", required: "conditional", meaning: "Destination", example: "ITM-1100-02" },
        { name: "created_by", label: "Created By", labelDari: "ثبت شده توسط", type: "reference", required: true, meaning: "Clerk who posted", example: "Items Accountant" },
        { name: "attachment", label: "Attachment", labelDari: "ضمیمه", type: "file", required: false, meaning: "Optional scan", example: "chag_45.pdf" },
        { name: "status", label: "Status", labelDari: "وضعیت", meaning: "draft | posted", type: "enum", required: true, example: "posted" },
      ],
    },
    {
      id: "ENT-ITM-024",
      name: "Items Movement Line",
      description: "Product line on movement voucher — select product and lot here.",
      fields: [
        { name: "voucher_id", label: "Voucher", type: "reference", required: true, meaning: "Parent voucher", example: "IMV-0088/1405" },
        { name: "product_id", label: "Product", labelDari: "جنس", type: "reference", required: true, meaning: "Product from master", example: "PRD-0042" },
        { name: "stock_lot_id", label: "Stock Lot", labelDari: "لوت", type: "reference", required: "conditional", meaning: "Price batch", example: "LOT-03/1405", rules: "Select open lot with remaining qty" },
        { name: "amount", label: "Amount", labelDari: "مقدار", type: "decimal", required: true, meaning: "Quantity", example: "200" },
        { name: "unit", label: "Unit", labelDari: "واحد", type: "text", required: true, meaning: "From product", example: "litre" },
        { name: "unit_price", label: "Unit Price", labelDari: "قیمت واحد", type: "decimal", required: true, meaning: "From lot — read-only", example: "85.50" },
        { name: "total", label: "Total", labelDari: "مجموع", type: "decimal", required: true, meaning: "amount × unit_price", example: "17100" },
        { name: "details", label: "Details", labelDari: "جزئیات", type: "longtext", required: false, meaning: "Optional", example: "Route Kabul–Mazar" },
      ],
    },
    {
      id: "ENT-ITM-025",
      name: "Spend Confirmation",
      description: "Header for confirmed consumption. Multiple product lines (ENT-ITM-026). user_id identifies who spent/consumed.",
      fields: [
        { name: "unique_number", label: "System Number", labelDari: "شماره سیستم", type: "text", required: true, meaning: "Auto-generated", example: "SPN-0044/1405" },
        { name: "holder_sub_account_id", label: "Holder Sub Account", labelDari: "حساب فرعی", type: "reference", required: true, meaning: "Sub account quantities are deducted from", example: "ITM-1100-02" },
        { name: "user_id", label: "Related Person", labelDari: "شخص مربوط", type: "reference", required: true, meaning: "Person who consumed — required for person reports", example: "Ahmad — Driver" },
        { name: "spent_account_id", label: "Spend Account Book", labelDari: "کتاب مصرف", type: "reference", required: true, meaning: "General account where is_spend_account=true", example: "ITM-SPENT" },
        { name: "date", label: "Date", labelDari: "تاریخ", type: "hijri_date", required: true, meaning: "Spend date", example: "1405/03/12" },
        { name: "mali_year", label: "Mali Year", labelDari: "سال مالی", type: "enum", required: true, meaning: "Fiscal year", example: "1405" },
        { name: "description", label: "Description", labelDari: "توضیحات", type: "longtext", required: false, meaning: "Optional summary", example: "March route consumption" },
        { name: "confirmed_by", label: "Confirmed By", labelDari: "تأیید شده توسط", type: "reference", required: true, meaning: "Clerk who posted spend", example: "Control Clerk" },
        { name: "attachment", label: "Attachment", labelDari: "ضمیمه", type: "file", required: false, meaning: "Optional document", example: "split.pdf" },
        { name: "status", label: "Status", labelDari: "وضعیت", meaning: "draft | posted", type: "enum", required: true, example: "posted" },
      ],
    },
    {
      id: "ENT-ITM-026",
      name: "Spend Confirmation Line",
      description: "One product per line — spend record can have many products at once.",
      fields: [
        { name: "spend_id", label: "Spend Confirmation", labelDari: "سند مصرف", type: "reference", required: true, meaning: "Parent spend header", example: "SPN-0044/1405" },
        { name: "line_number", label: "Line", type: "text", required: true, meaning: "Sequence", example: "1" },
        { name: "product_id", label: "Product", labelDari: "جنس", type: "reference", required: true, meaning: "Product consumed", example: "PRD-0042" },
        { name: "stock_lot_id", label: "Stock Lot", labelDari: "لوت", type: "reference", required: "conditional", meaning: "Lot consumed", example: "LOT-03/1405" },
        { name: "amount", label: "Spent Amount", labelDari: "مقدار مصرف", type: "decimal", required: true, meaning: "Quantity consumed", example: "180" },
        { name: "unit", label: "Unit", labelDari: "واحد", type: "text", required: true, meaning: "From product", example: "litre" },
        { name: "unit_price", label: "Unit Price", labelDari: "قیمت واحد", type: "decimal", required: true, meaning: "From lot", example: "85.50" },
        { name: "total", label: "Total", labelDari: "مجموع", type: "decimal", required: true, meaning: "amount × unit_price", example: "15390" },
        { name: "details", label: "Details", labelDari: "جزئیات", type: "longtext", required: false, meaning: "Optional line note", example: "Engine oil used" },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-ITM-020",
      name: "Setup — products, account books, sub accounts",
      trigger: "New ledger",
      startActor: "Items Accountant",
      endState: "Products, books, and sub accounts ready",
      flowDiagram: "Create product (code auto) → create account book → create sub accounts → open stock lots",
      steps: [
        { step: 1, actor: "Items Accountant", action: "Register product", input: "name, unit — code auto-generated", output: "ENT-ITM-015" },
        { step: 2, actor: "Items Accountant", action: "Create general account", input: "name, code, is_spend_account if consumption book", output: "ENT-ITM-020" },
        { step: 3, actor: "Items Accountant", action: "Create sub account", input: "name, account_id, code, status", output: "ENT-ITM-021" },
        { step: 4, actor: "Items Accountant", action: "Open stock lot", input: "product_id, qty, unit_price", output: "ENT-ITM-022" },
      ],
    },
    {
      id: "WF-ITM-021",
      name: "چګ صادره / چک وارده",
      trigger: "Move items between sub accounts",
      startActor: "Items Accountant",
      endState: "Posted voucher with user_id and product lines",
      steps: [
        { step: 1, actor: "Clerk", action: "Create voucher", input: "direction, user_id, from/to sub accounts, date", output: "Draft" },
        { step: 2, actor: "Clerk", action: "Add product lines", input: "product, lot, amount per line", output: "Post" },
      ],
    },
    {
      id: "WF-ITM-023",
      name: "Confirm spend (multiple products)",
      trigger: "Consumption confirmed",
      startActor: "Control Clerk",
      endState: "Spend posted with one or more product lines",
      steps: [
        { step: 1, actor: "Clerk", action: "Create spend header", input: "user_id, holder sub account, spend account book", output: "Draft SPN" },
        { step: 2, actor: "Clerk", action: "Add spend lines", input: "As many products as needed — product, lot, amount each", output: "Post — deduct from holder; add to spend book" },
      ],
    },
  ],
  businessRules: [
    { id: "BR-ITM-015", rule: "Product code is system-generated on create — not user-entered", trigger: "Create product", response: "Auto-assign PRD-####; read-only", severity: "Critical" },
    { id: "BR-ITM-016", rule: "Sub account has no product_id — products selected only on movement and spend lines", trigger: "Create sub account", response: "Only name, account_id, code, status", severity: "Critical" },
    { id: "BR-ITM-017", rule: "user_id required on movement vouchers and spend confirmation", trigger: "Post", response: "Block if missing", severity: "Critical" },
    { id: "BR-ITM-018", rule: "Spend confirmation must have at least one product line", trigger: "Post spend", response: "Block empty lines", severity: "Critical" },
    { id: "BR-ITM-019", rule: "spent_account_id must reference general account with is_spend_account=true", trigger: "Post spend", response: "Block wrong book", severity: "Critical" },
    { id: "BR-ITM-020", rule: "Cannot delete account or sub account when movements exist", trigger: "Delete", response: "Deactivate only", severity: "Critical" },
    { id: "BR-ITM-021", rule: "Lines must select open stock lot with sufficient quantity_remaining", trigger: "Add line", response: "Block if insufficient", severity: "Critical" },
    { id: "BR-ITM-029", rule: "Balances computed from posted movements and spend — not stored on sub account", trigger: "View balances", response: "Report engine aggregates by account, sub account, product, user_id", severity: "High" },
  ],
  permissionsMatrix: [
    { action: "Manage products & account books", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "R" },
    { action: "Post چګ صادره / چک وارده", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "—" },
    { action: "Confirm spend", archiveClerk: "—", executive: "—", deptStaff: "A", auditor: "—" },
    { action: "View all reports", archiveClerk: "—", executive: "R", deptStaff: "R", auditor: "R" },
  ],
  reports: [
    {
      id: "RPT-ITM-020",
      name: "Daily Report",
      purpose: "All movements and spend for a single Hijri day",
      filters: "Date, mali_year, optional: account, sub account, product, user_id",
      columns: "date, voucher/spend no., direction, user, account, sub account, product lines, totals",
      export: "PDF, Excel",
    },
    {
      id: "RPT-ITM-021",
      name: "Monthly Report",
      purpose: "Summary for a Hijri month — movements, spend, balances",
      filters: "Month/year (mali_year), optional: account, product, user_id",
      columns: "month, movement count, spend count, product totals, account summaries",
      export: "PDF, Excel",
    },
    {
      id: "RPT-ITM-022",
      name: "Person Report (user_id)",
      purpose: "Everything for one specific person — taken, given, spent",
      filters: "user_id, mali_year, date range",
      columns: "date, type (movement/spend), product, amount, account, sub account, balance running",
      export: "PDF, Excel",
    },
    {
      id: "RPT-ITM-023",
      name: "Product Report",
      purpose: "Activity and balance for one specific product",
      filters: "product_id, mali_year, date range, lot",
      columns: "movements, spend, lot remaining, by account/sub account breakdown",
      export: "PDF, Excel",
    },
    {
      id: "RPT-ITM-024",
      name: "General Account Report",
      purpose: "All activity under one ledger book",
      filters: "general account_id, mali_year, date range",
      columns: "sub accounts, movements, spend, product totals",
      export: "PDF, Excel",
    },
    {
      id: "RPT-ITM-025",
      name: "Sub Account Report",
      purpose: "Detail for one sub account — ins, outs, spend, current computed balance",
      filters: "sub_account_id, mali_year, date range, product",
      columns: "date, direction, user_id, product, amount, running balance",
      export: "PDF, Excel",
    },
    {
      id: "RPT-ITM-026",
      name: "Movement Voucher Finder",
      purpose: "Search چګ صادره / چک وارده",
      filters: "unique_number, user_id, account, sub account, product, date range",
      columns: "number, direction, user, accounts, lines",
      export: "PDF, Excel",
    },
    {
      id: "RPT-ITM-027",
      name: "Stock Lot Register",
      purpose: "Lots per product",
      filters: "Product, status, mali_year",
      columns: "product, lot, price, received, remaining",
      export: "Excel",
    },
  ],
  validationRules: [
    { field: "code (product)", rule: "System-generated; read-only", uiBehavior: "Shown after save" },
    { field: "is_spend_account", rule: "Boolean toggle on general account", uiBehavior: "Checkbox at account setup" },
    { field: "user_id", rule: "Required on movement and spend header", uiBehavior: "Person selector" },
    { field: "spend lines", rule: "One or more product lines per spend", uiBehavior: "Add line button like movement voucher" },
    { field: "sub account", rule: "name, account_id, code, status only", uiBehavior: "No product or holder fields" },
  ],
  crossModuleNotes: [
    "Standalone Items task — not bound to other modules.",
    "Products on lines only; sub accounts are simple book subdivisions.",
    "user_id drives person-specific reports.",
    "is_spend_account replaces account_type enum on general accounts.",
    "Procurement Projects and Small Procurement line items select from ENT-ITM-015 — register products here first.",
  ],
  deliverableChecklist: [
    { item: "Product code auto-generated", done: true },
    { item: "Simplified sub account (no product/holder/balance fields)", done: true },
    { item: "Multi-line spend confirmation", done: true },
    { item: "Daily, monthly, person, product, account, sub account reports", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
