import type { SectionDefinition } from "@/types/requirements";

export const personRegisterSection: SectionDefinition = {
  id: "person-register",
  name: "Person Register (جمع اشخاص)",
  nameDari: "جمع اشخاص",
  enableReview: true,
  description:
    "Person-level debit/credit register for general employees — summary of what each employee took or gave back. Person is selected from active HR employees filtered by branch. Separate from movement vouchers and from the driver register.",
  status: "draft",
  currentTool: "Paper جمع اشخاص book",
  summary: [
    "Person = active employee from HR (ENT-HR-010) — dropdown selection, not free text",
    "Select branch first — employee picker shows only active employees in that branch",
    "No driver_id — this section is for general employees, not the driver register",
    "entry_type: debit = taken (employee received/took); credit = given (employee gave back)",
    "System number, date, mali_year, description, product, lot/price, amount, unit, unit_price, total",
    "Optional attachment on entries",
  ],
  precededBy: [],
  followedBy: [],
  relatedSections: ["items-product-ledger", "hr"],
  roles: [
    {
      role: "Items Accountant",
      location: "HQ — محاسبه اجناس",
      mainActions: "Record جمع اشخاص entries, view person balances by branch",
      approval: false,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View person register and totals",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-ITM-040",
      name: "Person Register Entry (جمع اشخاص)",
      description:
        "Single debit or credit line for an employee — debit = taken, credit = given. Person always references an active HR employee.",
      fields: [
        {
          name: "unique_number",
          label: "System Number",
          labelDari: "شماره سیستم",
          meaning: "Auto-generated",
          type: "text",
          required: true,
          example: "JAM-0033/1405",
        },
        {
          name: "date",
          label: "Date",
          labelDari: "تاریخ",
          meaning: "Entry date",
          type: "hijri_date",
          required: true,
          example: "1405/03/11",
        },
        {
          name: "mali_year",
          label: "Mali Year",
          labelDari: "سال مالی",
          meaning: "Fiscal year select (current ± 5)",
          type: "enum",
          required: true,
          example: "1405",
        },
        {
          name: "branch_id",
          label: "Branch",
          labelDari: "شعبه",
          meaning: "Branch context — filters which employees appear in the person picker",
          type: "reference",
          required: true,
          example: "Branch A",
          rules: "Required before employee selection; only active employees assigned to this branch are listed",
        },
        {
          name: "employee_id",
          label: "Employee (Person)",
          labelDari: "کارمند / شخص",
          meaning: "Reference → HR Employee Record (ENT-HR-010) — active employees only",
          type: "reference",
          required: true,
          example: "EMP-0045 — Mohammad Rahimi",
          rules:
            "Dropdown — not free text. Shows only employees with status=active in the selected branch. Inactive or terminated employees excluded.",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Context of entry",
          type: "longtext",
          required: true,
          example: "Oil advance for March routes",
        },
        {
          name: "product_id",
          label: "Product",
          labelDari: "جنس",
          meaning: "Reference → Product master (ENT-ITM-015)",
          type: "reference",
          required: true,
          example: "PRD-OIL-01 — Engine Oil",
        },
        {
          name: "stock_lot_id",
          label: "Stock Lot",
          labelDari: "لوت / قیمت",
          meaning: "Which price batch — select when multiple lots exist",
          type: "reference",
          required: "conditional",
          example: "LOT-03/1405 @ 85.50",
          rules: "Required when product has multiple open lots — user selects which oil/price",
        },
        {
          name: "amount",
          label: "Amount",
          labelDari: "مقدار",
          meaning: "Quantity",
          type: "decimal",
          required: true,
          example: "200",
        },
        {
          name: "unit",
          label: "Unit",
          labelDari: "واحد",
          meaning: "From product",
          type: "text",
          required: true,
          example: "litre",
        },
        {
          name: "unit_price",
          label: "Unit Price",
          labelDari: "قیمت واحد",
          meaning: "From lot or manual when no lot",
          type: "decimal",
          required: true,
          example: "85.50",
        },
        {
          name: "total",
          label: "Total",
          labelDari: "مجموع",
          meaning: "amount × unit_price — auto",
          type: "decimal",
          required: true,
          example: "17100",
        },
        {
          name: "entry_type",
          label: "Entry Type",
          labelDari: "نوع",
          meaning: "debit | credit",
          type: "enum",
          required: true,
          example: "debit",
          rules:
            "debit = taken — employee received / took the item; credit = given — employee gave the item back",
        },
        {
          name: "attachment",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional document",
          type: "file",
          required: false,
          example: "jam_ashkhas_scan.pdf",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-ITM-040",
      name: "Record جمع اشخاص entry",
      trigger: "Need person-level taken/given summary for an employee",
      startActor: "Items Accountant",
      endState: "Entry posted — employee balance updated",
      flowDiagram: "Select branch → pick active employee → product/lot → debit (taken) or credit (given)",
      steps: [
        {
          step: 1,
          actor: "Clerk",
          action: "Select branch",
          input: "branch_id",
          output: "Employee dropdown populated with active HR employees in that branch only",
        },
        {
          step: 2,
          actor: "Clerk",
          action: "Select employee and enter header",
          input: "employee_id, date, mali_year, description",
          output: "Draft entry",
        },
        {
          step: 3,
          actor: "Clerk",
          action: "Select product and lot (price)",
          input: "product, stock_lot_id when multiple prices",
          output: "unit_price filled",
        },
        {
          step: 4,
          actor: "Clerk",
          action: "Enter amount and entry type",
          input: "amount; debit = taken or credit = given",
          output: "total auto-calculated; entry posted",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-ITM-040",
      rule: "When multiple stock lots exist for product, user must select lot (price batch)",
      trigger: "Add entry",
      response: "Block if ambiguous",
      severity: "Critical",
    },
    {
      id: "BR-ITM-041",
      rule: "When current lot finishes, new entries use new lot at new price",
      trigger: "Lot depleted",
      response: "Show only open lots in picker",
      severity: "Critical",
    },
    {
      id: "BR-ITM-042",
      rule: "Employee picker lists only HR employees with status=active in the selected branch",
      trigger: "Select branch / open employee dropdown",
      response: "Filter list; no inactive or terminated staff",
      severity: "Critical",
    },
    {
      id: "BR-ITM-043",
      rule: "debit = taken (employee received); credit = given (employee returned)",
      trigger: "Post entry",
      response: "Store entry_type; running balance = sum(debit totals) − sum(credit totals) per employee",
      severity: "Critical",
    },
    {
      id: "BR-ITM-044",
      rule: "employee_id is required — must reference HR Employee Record; no driver_id on this form",
      trigger: "Create entry",
      response: "Block free-text person names",
      severity: "Critical",
    },
    {
      id: "BR-ITM-045",
      rule: "branch_id required before employee can be selected",
      trigger: "Create entry",
      response: "Disable employee picker until branch chosen",
      severity: "High",
    },
  ],
  permissionsMatrix: [
    { action: "Create جمع اشخاص entries", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "—" },
    { action: "View person register & balances", archiveClerk: "—", executive: "R", deptStaff: "R", auditor: "R" },
  ],
  reports: [
    {
      id: "RPT-ITM-040",
      name: "Person Register (جمع اشخاص)",
      purpose: "All entries per employee with taken/given and running balance",
      filters: "Branch, employee, product, mali_year, entry_type (debit/credit), date range",
      columns: "number, date, branch, employee, product, lot, amount, unit_price, total, taken/given, balance",
      export: "PDF, Excel",
    },
  ],
  validationRules: [
    { field: "branch_id", rule: "Required first — drives employee list", uiBehavior: "Branch dropdown before employee" },
    { field: "employee_id", rule: "Required; active HR employees in selected branch only", uiBehavior: "Searchable select — no free text" },
    { field: "entry_type", rule: "debit = taken | credit = given", uiBehavior: "Toggle or radio with Dari labels: اخذ / داده" },
  ],
  integrations: [
    {
      id: "INT-ITM-040",
      direction: "in",
      module: "HR — Employee Record (ENT-HR-010)",
      data: "employee_id, full_name, branch, status=active",
      when: "Employee picker on جمع اشخاص form",
      note: "Read-only link — person does not come from driver register",
    },
  ],
  crossModuleNotes: [
    "Person comes from HR active employees — not the Items driver register (section: drivers).",
    "Select branch first; employee dropdown shows only that branch's active staff.",
    "debit = taken (employee received); credit = given (employee gave back) — ENCC confirmed.",
    "Separate from movement vouchers (چګ صادره / چک وارده) — this is person-level summary ledger.",
    "Stock lot selection ensures correct price when same product has different purchase prices.",
  ],
  deliverableChecklist: [
    { item: "جمع اشخاص fields and debit/credit rules (taken/given)", done: true },
    { item: "HR employee selection by branch", done: true },
    { item: "Lot/price selection documented", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
