import type { SectionDefinition } from "@/types/requirements";

export const contractEmployeesSection: SectionDefinition = {
  id: "contract-employees",
  name: "Contract Employees",
  nameDari: "ثبت کارمندان قراردادی",
  enableReview: true,
  description:
    "Register and manage contract workers at ENCC mine and field sites — not permanent HR employees. Each person belongs to a site, a site-specific work group, and has a role type (worker, group leader, etc.). Work groups and pay rates are configured per site. Group assignment is easy to change without re-registering the person.",
  status: "draft",
  currentTool: "Paper site registers and group lists",
  summary: [
    "Contract employee — name, father_name, site, type, branch, phone, file, status, join_date, group",
    "Site Work Group — dynamic per site only (id, name); move people between groups with one action",
    "Site Work Rate — per site prices for ترمیم اساسی, ترمیم جاری, حفریات (per cm), wagon, ton",
    "Only active employees appear on daily attendance and work reports",
  ],
  relatedSections: ["daily-site-work", "general-tables"],
  roles: [
    {
      role: "Site Clerk",
      location: "Mine / field site",
      mainActions: "Register contract employees, assign groups, upload files",
      approval: false,
      readOnly: false,
    },
    {
      role: "Site Supervisor",
      location: "Mine / field site",
      mainActions: "Review employee lists, approve group changes",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View employee register and group history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-SITE-010",
      name: "Site Work Group",
      description:
        "Work crew group scoped to one site — id and name only. Admin adds groups per site; employees are assigned to one group at a time.",
      fields: [
        {
          name: "site_id",
          label: "Site",
          labelDari: "سایت / معدن",
          meaning: "Reference → Mining Site (ENT-OPR-G004)",
          type: "reference",
          required: true,
          example: "Karkar Mine",
          rules: "Groups are unique per site — same group name allowed on different sites",
        },
        {
          name: "name",
          label: "Group Name",
          labelDari: "نام گروپ",
          meaning: "Crew or team name at this site",
          type: "text",
          required: true,
          example: "Group A / گروپ الف",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Inactive groups hidden from new assignments",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-SITE-011",
      name: "Site Work Rate",
      description:
        "Pay rates for daily work units at a site — used to calculate line totals on daily work reports. One current rate set per site.",
      fields: [
        {
          name: "site_id",
          label: "Site",
          labelDari: "سایت",
          meaning: "Reference → Mining Site (ENT-OPR-G004)",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "permanent_repair_rate",
          label: "Permanent Repair Rate (AFN/cm)",
          labelDari: "نرخ ترمیم اساسی (افغانی/سانتی)",
          meaning: "Price per cm for ترمیم اساسی",
          type: "decimal",
          required: true,
          example: "850",
        },
        {
          name: "continuous_repair_rate",
          label: "Continuous Repair Rate (AFN/cm)",
          labelDari: "نرخ ترمیم جاری (افغانی/سانتی)",
          meaning: "Price per cm for ترمیم جاری",
          type: "decimal",
          required: true,
          example: "650",
        },
        {
          name: "digging_rate",
          label: "Digging Rate (AFN/cm)",
          labelDari: "نرخ حفریات (افغانی/سانتی)",
          meaning: "Price per cm for حفریات",
          type: "decimal",
          required: true,
          example: "1200",
        },
        {
          name: "wagon_rate",
          label: "Wagon Rate (AFN/unit)",
          labelDari: "نرخ ویگن (افغانی/عدد)",
          meaning: "Price per wagon unit",
          type: "decimal",
          required: true,
          example: "500",
        },
        {
          name: "ton_rate",
          label: "Ton Rate (AFN/ton)",
          labelDari: "نرخ تن (افغانی/تن)",
          meaning: "Price per ton",
          type: "decimal",
          required: true,
          example: "350",
        },
        {
          name: "effective_from",
          label: "Effective From",
          labelDari: "از تاریخ",
          meaning: "Hijri date this rate applies from",
          type: "hijri_date",
          required: true,
          example: "1405/01/01",
        },
        {
          name: "is_current",
          label: "Current Rate",
          labelDari: "نرخ فعلی",
          meaning: "Only one current rate per site",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-SITE-012",
      name: "Contract Employee",
      description:
        "Contract worker at a site — separate from HR permanent employees (ENT-HR-010). Used for attendance and piece-rate daily work.",
      fields: [
        {
          name: "employee_code",
          label: "Employee Code",
          labelDari: "کود کارمند",
          meaning: "Auto-generated unique code",
          type: "text",
          required: true,
          example: "CE-KRK-0042",
          rules: "Auto-generated; unique",
        },
        {
          name: "name",
          label: "Name",
          labelDari: "نام",
          meaning: "Given name",
          type: "text",
          required: true,
          example: "Ahmad",
        },
        {
          name: "father_name",
          label: "Father Name",
          labelDari: "نام پدر",
          meaning: "Patronymic",
          type: "text",
          required: true,
          example: "Karim",
        },
        {
          name: "site_id",
          label: "Site",
          labelDari: "سایت",
          meaning: "Reference → Mining Site (ENT-OPR-G004)",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "employee_type",
          label: "Type",
          labelDari: "نوع",
          meaning: "worker | group_leader | supervisor | technician | driver | other",
          type: "enum",
          required: true,
          example: "worker",
        },
        {
          name: "group_id",
          label: "Work Group",
          labelDari: "گروپ",
          meaning: "Reference → Site Work Group (ENT-SITE-010) — filtered to active groups on selected site",
          type: "reference",
          required: true,
          example: "Group A",
          rules: "Quick-change via group switch action — no re-registration needed",
        },
        {
          name: "branch_id",
          label: "Branch",
          labelDari: "شعبه",
          meaning: "Reference → Branch (ENT-OPR-G009) — optional",
          type: "reference",
          required: false,
          example: "Kabul HQ Branch",
        },
        {
          name: "phone",
          label: "Phone",
          labelDari: "تلفن",
          meaning: "Contact number",
          type: "text",
          required: false,
          example: "0700123456",
        },
        {
          name: "join_date",
          label: "Join Date",
          labelDari: "تاریخ شروع",
          meaning: "Start on site — Hijri",
          type: "hijri_date",
          required: true,
          example: "1404/06/01",
        },
        {
          name: "file",
          label: "Contract File",
          labelDari: "فایل قرارداد",
          meaning: "Signed contract or ID scan — optional",
          type: "file",
          required: false,
          example: "contract_scan.pdf",
          rules: "PDF, JPG, PNG; max 10 MB",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | inactive | terminated",
          type: "enum",
          required: true,
          example: "active",
          rules: "Only active employees on daily attendance and work sheets",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-SITE-010",
      name: "Register contract employee",
      trigger: "New contract worker starts at site",
      startActor: "Site Clerk",
      endState: "Active employee assigned to site and group",
      flowDiagram: "Select site → pick group → enter name, type, join_date → optional file → active",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Ensure site has groups and work rates configured",
          input: "site_id",
          output: "Groups and current ENT-SITE-011 rates available",
        },
        {
          step: 2,
          actor: "Site Clerk",
          action: "Create contract employee",
          input: "name, father_name, site_id, employee_type, group_id, join_date",
          output: "ENT-SITE-012 with auto employee_code; status=active",
        },
      ],
    },
    {
      id: "WF-SITE-011",
      name: "Switch employee group",
      trigger: "Worker moves to another crew at same site",
      startActor: "Site Clerk",
      endState: "Employee in new group — history logged",
      flowDiagram: "Open employee → select new group (same site) → save",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Open employee record",
          input: "employee_code or name search",
          output: "Current group shown",
        },
        {
          step: 2,
          actor: "Site Clerk",
          action: "Change group",
          input: "new group_id — dropdown filtered to same site_id only",
          output: "group_id updated; previous group logged in audit trail",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-SITE-010",
      rule: "group_id must belong to same site_id as the employee",
      trigger: "Save employee or switch group",
      response: "Block if group.site_id ≠ employee.site_id",
      severity: "Critical",
    },
    {
      id: "BR-SITE-011",
      rule: "Only one current Site Work Rate (is_current=true) per site",
      trigger: "Set current rate",
      response: "Auto-deactivate previous current rate for that site",
      severity: "High",
    },
    {
      id: "BR-SITE-012",
      rule: "Inactive or terminated employees excluded from daily work sheets",
      trigger: "Load daily report",
      response: "Filter status=active only",
      severity: "Critical",
    },
    {
      id: "BR-SITE-013",
      rule: "Group switch is a single field change — no new employee record required",
      trigger: "Change group_id",
      response: "Audit log old → new group with date and user",
      severity: "Medium",
    },
  ],
  validationRules: [
    {
      field: "group_id",
      rule: "Required; filtered by employee site_id",
      uiBehavior: "Dropdown — quick switch button on list and detail view",
    },
    {
      field: "employee_type",
      rule: "worker | group_leader | supervisor | technician | driver | other",
      uiBehavior: "Enum select",
    },
    {
      field: "site work group",
      rule: "name required per site",
      uiBehavior: "Admin list scoped by site filter",
    },
  ],
  integrations: [
    {
      id: "INT-SITE-010",
      direction: "in",
      module: "General Tables — Mining Site (ENT-OPR-G004), Branch (ENT-OPR-G009)",
      data: "site_id, branch_id",
      when: "Employee and group create",
    },
  ],
  crossModuleNotes: [
    "Contract employees are NOT HR permanent employees (ENT-HR-010) — separate register for site piece-rate workers.",
    "Work groups exist only per site — not shared across sites.",
  ],
  deliverableChecklist: [
    { item: "Contract employee registration defined", done: true },
    { item: "Per-site groups and work rates defined", done: true },
    { item: "Easy group switch workflow", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
