import type { SectionDefinition } from "@/types/requirements";

export const dailySiteWorkSection: SectionDefinition = {
  id: "daily-site-work",
  name: "Daily Attendance & Work",
  nameDari: "حاضری و کار روزانه",
  enableReview: true,
  description:
    "Daily site sheet — select Hijri date and site, mark all active contract employees present or absent, record work quantities (ترمیم اساسی cm, ترمیم جاری cm, حفریات cm, wagon, ton) with auto-calculated pay from site rates. Grouped by work group. Day totals per work type and headcount. Month-end salary rollup with tax — printable 8 people per page with daily numbers.",
  status: "draft",
  currentTool: "Paper daily attendance and work books",
  summary: [
    "Select site + Hijri date + mali_year — load all active contract employees grouped by work group",
    "Each line: present | absent; if present — work quantities × site rates = line pay total",
    "Work units: permanent repair (ترمیم اساسی cm), continuous repair (ترمیم جاری cm), digging (حفریات cm), wagon, ton",
    "Day footer: total present, total absent, sum each work type, grand pay total",
    "Header: description, responsible person; optional file",
    "Month report: per person totals by type, gross salary, tax, net — 8 people per printed page, daily breakdown",
  ],
  precededBy: [
    {
      moduleId: "site",
      sectionId: "contract-employees",
      label: "Contract Employees",
    },
  ],
  relatedSections: ["contract-employees", "general-tables"],
  roles: [
    {
      role: "Site Clerk",
      location: "Mine / field site",
      mainActions: "Enter daily attendance and work quantities",
      approval: false,
      readOnly: false,
    },
    {
      role: "Site Supervisor",
      location: "Mine / field site",
      mainActions: "Review and sign daily sheet, verify totals",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View daily and monthly reports",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-SITE-020",
      name: "Daily Site Report",
      description:
        "One daily sheet per site per Hijri date — header with totals; child lines for each active employee.",
      fields: [
        {
          name: "report_id",
          label: "Report ID",
          labelDari: "شناسه گزارش",
          meaning: "Auto-generated daily sheet number",
          type: "text",
          required: true,
          example: "DSR-KRK-1405/03/15",
          rules: "Unique per site + date",
        },
        {
          name: "site_id",
          label: "Site",
          labelDari: "سایت",
          meaning: "Reference → Mining Site (ENT-OPR-G004)",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "date",
          label: "Date",
          labelDari: "تاریخ",
          meaning: "Work day — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/03/15",
        },
        {
          name: "mali_year",
          label: "Mali Year",
          labelDari: "سال مالی",
          meaning: "Fiscal year — select current ± 5",
          type: "enum",
          required: true,
          example: "1405",
        },
        {
          name: "hijri_month",
          label: "Hijri Month",
          labelDari: "ماه هجری",
          meaning: "Month of the work day — for monthly rollups (1–12)",
          type: "text",
          required: true,
          example: "03",
          rules: "Derived from date; used in month-end reports",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Daily report notes — weather, delays, special conditions",
          type: "longtext",
          required: false,
          example: "Normal shift — section 4 repair completed",
        },
        {
          name: "responsible_person",
          label: "Responsible Person",
          labelDari: "شخص مسئول",
          meaning: "Supervisor or clerk who prepared/signed this daily sheet",
          type: "text",
          required: true,
          example: "Mohammad Rahim — Site Supervisor",
        },
        {
          name: "file",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional scanned daily sheet",
          type: "file",
          required: false,
          example: "daily_sheet_scan.pdf",
        },
        {
          name: "total_present",
          label: "Total Present",
          labelDari: "مجموع حاضر",
          meaning: "Count of employees marked present — auto-calculated",
          type: "decimal",
          required: true,
          example: "42",
          rules: "Read-only; sum of lines with attendance=present",
        },
        {
          name: "total_absent",
          label: "Total Absent",
          labelDari: "مجموع غایب",
          meaning: "Count marked absent — auto-calculated",
          type: "decimal",
          required: true,
          example: "3",
          rules: "Read-only; no leave types — present or absent only",
        },
        {
          name: "total_permanent_repair_cm",
          label: "Total Permanent Repair (cm)",
          labelDari: "مجموع ترمیم اساسی (سانتی)",
          meaning: "Sum of permanent_repair_cm across all present lines",
          type: "decimal",
          required: true,
          example: "1250",
          rules: "Read-only day total",
        },
        {
          name: "total_continuous_repair_cm",
          label: "Total Continuous Repair (cm)",
          labelDari: "مجموع ترمیم جاری (سانتی)",
          meaning: "Sum of continuous_repair_cm across present lines",
          type: "decimal",
          required: true,
          example: "890",
          rules: "Read-only day total",
        },
        {
          name: "total_digging_cm",
          label: "Total Digging (cm)",
          labelDari: "مجموع حفریات (سانتی)",
          meaning: "Sum of digging_cm across present lines",
          type: "decimal",
          required: true,
          example: "340",
          rules: "Read-only day total",
        },
        {
          name: "total_wagon",
          label: "Total Wagon",
          labelDari: "مجموع ویگن",
          meaning: "Sum of wagon units across present lines",
          type: "decimal",
          required: true,
          example: "18",
          rules: "Read-only day total",
        },
        {
          name: "total_ton",
          label: "Total Ton",
          labelDari: "مجموع تن",
          meaning: "Sum of ton across present lines",
          type: "decimal",
          required: true,
          example: "220",
          rules: "Read-only day total",
        },
        {
          name: "grand_total_pay",
          label: "Grand Total Pay (AFN)",
          labelDari: "مجموع کل معاش روز",
          meaning: "Sum of all line pay totals for the day",
          type: "decimal",
          required: true,
          example: "485000",
          rules: "Read-only",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | submitted | approved",
          type: "enum",
          required: true,
          example: "submitted",
        },
      ],
    },
    {
      id: "ENT-SITE-021",
      name: "Daily Work Line",
      description:
        "One row per active contract employee on the daily sheet — attendance plus work quantities and calculated pay.",
      fields: [
        {
          name: "daily_report_id",
          label: "Daily Report",
          labelDari: "گزارش روز",
          meaning: "Parent — reference → ENT-SITE-020",
          type: "reference",
          required: true,
          example: "DSR-KRK-1405/03/15",
        },
        {
          name: "employee_id",
          label: "Employee",
          labelDari: "کارمند",
          meaning: "Reference → Contract Employee (ENT-SITE-012)",
          type: "reference",
          required: true,
          example: "CE-KRK-0042 — Ahmad بن Karim",
          rules: "Active employees at this site only; one line per employee per day",
        },
        {
          name: "group_id",
          label: "Group",
          labelDari: "گروپ",
          meaning: "Snapshot of employee group on this day — from employee.group_id",
          type: "reference",
          required: true,
          example: "Group A",
          rules: "Display grouped by this field on sheet",
        },
        {
          name: "employee_type",
          label: "Type",
          labelDari: "نوع",
          meaning: "Snapshot of employee_type on this day — worker, group_leader, etc.",
          type: "enum",
          required: true,
          example: "worker",
          rules: "Read-only from employee record",
        },
        {
          name: "attendance",
          label: "Attendance",
          labelDari: "حاضری",
          meaning: "present | absent",
          type: "enum",
          required: true,
          example: "present",
          rules: "No leave types — present or absent only; absent lines have zero work and zero pay",
        },
        {
          name: "permanent_repair_cm",
          label: "Permanent Repair (cm)",
          labelDari: "ترمیم اساسی (سانتی)",
          meaning: "Cm of ترمیم اساسی — × site permanent_repair_rate",
          type: "decimal",
          required: false,
          example: "45",
          rules: "Required when attendance=present if any work done; 0 if absent",
        },
        {
          name: "continuous_repair_cm",
          label: "Continuous Repair (cm)",
          labelDari: "ترمیم جاری (سانتی)",
          meaning: "Cm of ترمیم جاری — × site continuous_repair_rate",
          type: "decimal",
          required: false,
          example: "30",
        },
        {
          name: "digging_cm",
          label: "Digging (cm)",
          labelDari: "حفریات (سانتی)",
          meaning: "Cm of حفریات — × site digging_rate",
          type: "decimal",
          required: false,
          example: "12",
        },
        {
          name: "wagon",
          label: "Wagon",
          labelDari: "ویگن",
          meaning: "Wagon units — × site wagon_rate",
          type: "decimal",
          required: false,
          example: "2",
        },
        {
          name: "ton",
          label: "Ton",
          labelDari: "تن",
          meaning: "Tons — × site ton_rate",
          type: "decimal",
          required: false,
          example: "5",
        },
        {
          name: "line_description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Optional notes for this person's work today",
          type: "longtext",
          required: false,
          example: "Section 4 rail repair",
        },
        {
          name: "line_total_pay",
          label: "Line Total Pay (AFN)",
          labelDari: "مجموع معاش (افغانی)",
          meaning: "Auto: sum of (qty × rate) for each work type using ENT-SITE-011 current rates",
          type: "decimal",
          required: true,
          example: "12500",
          rules: "Read-only; 0 when attendance=absent",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-SITE-020",
      name: "Record daily attendance and work",
      trigger: "End of work day at site",
      startActor: "Site Clerk",
      endState: "Daily sheet submitted with totals",
      flowDiagram:
        "Select site + date → load active employees by group → mark present/absent → enter work for present → auto totals → responsible person → submit",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Open or create daily report",
          input: "site_id, date (Hijri), mali_year",
          output: "ENT-SITE-020 draft; all active ENT-SITE-012 loaded grouped by group_id",
        },
        {
          step: 2,
          actor: "Site Clerk",
          action: "Mark attendance for each employee",
          input: "present | absent per line",
          output: "total_present and total_absent updating live",
        },
        {
          step: 3,
          actor: "Site Clerk",
          action: "Enter work quantities for present employees",
          input: "permanent_repair_cm, continuous_repair_cm, digging_cm, wagon, ton, optional line_description",
          output: "line_total_pay calculated from ENT-SITE-011 rates",
        },
        {
          step: 4,
          actor: "Site Clerk",
          action: "Review day totals and add header notes",
          input: "description, responsible_person, optional file",
          output: "Day totals: each work type sum + grand_total_pay",
        },
        {
          step: 5,
          actor: "Site Supervisor",
          action: "Approve daily sheet",
          input: "Review totals",
          output: "status: approved",
        },
      ],
    },
    {
      id: "WF-SITE-021",
      name: "Month-end salary rollup",
      trigger: "End of Hijri month",
      startActor: "Site Clerk",
      endState: "Monthly salary report with tax — printable",
      flowDiagram:
        "Select site + mali_year + Hijri month → aggregate all approved daily lines → gross, tax, net per person",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Run monthly report",
          input: "site_id, mali_year, hijri_month",
          output: "Per employee: days present, totals per work type, gross salary",
        },
        {
          step: 2,
          actor: "System",
          action: "Apply tax and compute net",
          input: "gross salary, configurable tax rate or fixed deduction",
          output: "tax_amount, net_salary per employee",
        },
        {
          step: 3,
          actor: "Site Supervisor",
          action: "Print monthly payroll",
          input: "Approved month data",
          output: "PDF — 8 employees per page; daily pay numbers shown per person",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-SITE-020",
      rule: "One daily report per site per Hijri date — no duplicate sheets",
      trigger: "Create daily report",
      response: "Block duplicate site_id + date",
      severity: "Critical",
    },
    {
      id: "BR-SITE-021",
      rule: "line_total_pay = (permanent_repair_cm × rate) + (continuous_repair_cm × rate) + (digging_cm × rate) + (wagon × rate) + (ton × rate) using current ENT-SITE-011 for site",
      trigger: "Save work line",
      response: "Auto-calculate; 0 if attendance=absent",
      severity: "Critical",
    },
    {
      id: "BR-SITE-022",
      rule: "Absent employees — all work fields zero; excluded from work type day totals",
      trigger: "attendance=absent",
      response: "Clear work quantities; line_total_pay=0",
      severity: "High",
    },
    {
      id: "BR-SITE-023",
      rule: "Daily sheet lists employees grouped by work group — name, father_name, type shown on each line",
      trigger: "Load daily report",
      response: "Sort by group_id then name; display employee name + father_name + type",
      severity: "Medium",
    },
    {
      id: "BR-SITE-024",
      rule: "Month-end gross salary = sum of line_total_pay for all present days in the Hijri month",
      trigger: "Monthly report",
      response: "Aggregate by employee_id",
      severity: "Critical",
    },
    {
      id: "BR-SITE-025",
      rule: "Monthly printable layout — 8 employees per page with daily pay numbers and type/work breakdown",
      trigger: "Print monthly report",
      response: "Paginate 8 per page; include each day's line_total_pay in grid",
      severity: "High",
    },
  ],
  validationRules: [
    {
      field: "date",
      rule: "Required Hijri date",
      uiBehavior: "Date picker — loads or creates sheet for site + date",
    },
    {
      field: "attendance grid",
      rule: "All active site employees shown; checkbox present/absent",
      uiBehavior: "Grouped by work group; bulk mark present for group optional",
    },
    {
      field: "work quantities",
      rule: "Enabled only when attendance=present",
      uiBehavior: "Numeric fields; line total updates live",
    },
    {
      field: "daily totals",
      rule: "Footer shows total present, absent, each work type sum, grand pay",
      uiBehavior: "Read-only summary bar on sheet",
    },
    {
      field: "monthly print",
      rule: "8 people per page; columns: name, father_name, type, each work type month total, gross, tax, net, daily numbers",
      uiBehavior: "Print preview with page breaks",
    },
  ],
  integrations: [
    {
      id: "INT-SITE-020",
      direction: "in",
      module: "Site — Contract Employees (ENT-SITE-012), Work Rates (ENT-SITE-011), Groups (ENT-SITE-010)",
      data: "employee list, rates, group names",
      when: "Daily sheet load and pay calculation",
    },
    {
      id: "INT-SITE-021",
      direction: "out",
      module: "Salaries — Payroll (future)",
      data: "monthly gross, tax, net per contract employee",
      when: "Month-end approval",
      note: "Future handoff to معاشات if needed",
    },
  ],
  crossModuleNotes: [
    "Salary is based on work done — no fixed daily wage; absent = zero pay for that day.",
    "Hijri dates and mali_year drive daily and monthly reports.",
    "Work rates come from ENT-SITE-011 — must be configured before first daily sheet.",
  ],
  reports: [
    {
      id: "RPT-SITE-020",
      name: "Daily site sheet (printable)",
      purpose: "Full daily report — groups, each person with attendance and work, day totals",
      filters: "site_id, date",
      columns:
        "group, name, father_name, type, attendance, permanent_repair_cm, continuous_repair_cm, digging_cm, wagon, ton, line_total_pay | footer: day totals",
      export: "PDF — printable",
    },
    {
      id: "RPT-SITE-021",
      name: "Daily list by group",
      purpose: "Same day grouped view for supervisor sign-off",
      filters: "site_id, date, group_id",
      columns: "group, name, father_name, type, attendance, line_total_pay",
      export: "PDF, Excel",
    },
    {
      id: "RPT-SITE-022",
      name: "Monthly work by person",
      purpose: "Each employee — total days present, each work type month sum, gross salary",
      filters: "site_id, mali_year, hijri_month",
      columns:
        "name, father_name, type, group, days_present, permanent_repair_cm, continuous_repair_cm, digging_cm, wagon, ton, gross_salary",
      export: "Excel, PDF",
    },
    {
      id: "RPT-SITE-023",
      name: "Monthly salary with tax (printable)",
      purpose: "Payroll sheet — 8 employees per page, daily numbers, tax, net",
      filters: "site_id, mali_year, hijri_month",
      columns:
        "name, father_name, type, daily_pay_grid (each day number), gross, tax, net — 8 per page",
      export: "PDF — printable",
    },
    {
      id: "RPT-SITE-024",
      name: "Monthly totals by work type",
      purpose: "Site-wide month sum per work unit",
      filters: "site_id, mali_year, hijri_month",
      columns: "work_type, total_quantity, total_pay_afn",
      export: "Excel, PDF",
    },
    {
      id: "RPT-SITE-025",
      name: "Attendance summary",
      purpose: "Present vs absent counts per day in month",
      filters: "site_id, mali_year, hijri_month",
      columns: "date, total_present, total_absent, grand_total_pay",
      export: "Excel, PDF",
    },
  ],
  deliverableChecklist: [
    { item: "Daily attendance present/absent defined", done: true },
    { item: "Work quantities with site rate calculation", done: true },
    { item: "Day totals and monthly salary rollup", done: true },
    { item: "Printable monthly — 8 per page with daily numbers", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
