import type { SectionDefinition } from "@/types/requirements";

export const dailyWorkReportSection: SectionDefinition = {
  id: "daily-work-report",
  name: "Daily Work Report",
  nameDari: "گزارش کار روزانه",
  enableReview: true,
  description:
    "Daily work sheet per site — after attendance is approved, record work quantities for present employees (ترمیم اساسی cm, ترمیم جاری cm, حفریات cm, wagon, ton) with auto-calculated pay from site rates. Grouped by work group. Day totals per work type and grand pay. Month-end salary rollup with tax — printable 8 people per page with daily numbers.",
  status: "draft",
  currentTool: "Paper daily work books",
  summary: [
    "Requires approved attendance for same site + Hijri date — loads present employees only",
    "Work units: permanent repair (ترمیم اساسی cm), continuous repair (ترمیم جاری cm), digging (حفریات cm), wagon, ton",
    "Each line: work quantities × site rates = line pay total; lines auto-grouped by employee active group",
    "Day footer: sum each work type, grand pay total",
    "Header: description, responsible person; optional file",
    "Month report: per person totals by type, gross salary, tax, net — 8 people per printed page, daily breakdown",
  ],
  precededBy: [
    {
      moduleId: "site",
      sectionId: "contract-employees",
      label: "Contract Employees",
    },
    {
      moduleId: "site",
      sectionId: "daily-attendance",
      label: "Daily Attendance",
    },
  ],
  relatedSections: ["contract-employees", "daily-attendance", "general-tables"],
  roles: [
    {
      role: "Site Clerk",
      location: "Mine / field site",
      mainActions: "Enter daily work quantities for present employees",
      approval: false,
      readOnly: false,
    },
    {
      role: "Site Supervisor",
      location: "Mine / field site",
      mainActions: "Review and sign daily work sheet, verify totals",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View daily and monthly work reports",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-SITE-020",
      name: "Daily Work Report",
      description:
        "One daily work sheet per site per Hijri date — linked to approved attendance; header with work totals; child lines for each present employee.",
      fields: [
        {
          name: "report_id",
          label: "Report ID",
          labelDari: "شناسه گزارش",
          meaning: "Auto-generated daily work report number",
          type: "text",
          required: true,
          example: "DWR-KRK-1405/03/15",
          rules: "Unique per site + date",
        },
        {
          name: "attendance_sheet_id",
          label: "Attendance Sheet",
          labelDari: "برگه حاضری",
          meaning: "Reference → approved Daily Attendance Sheet (ENT-SITE-018) for same site + date",
          type: "reference",
          required: true,
          example: "ATT-KRK-1405/03/15",
          rules: "Must be approved; same site_id and date",
        },
        {
          name: "site_id",
          label: "Site",
          labelDari: "سایت",
          meaning: "Reference → Mining Site (ENT-OPR-G004) — from attendance sheet",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "date",
          label: "Date",
          labelDari: "تاریخ",
          meaning: "Work day — Hijri — from attendance sheet",
          type: "hijri_date",
          required: true,
          example: "1405/03/15",
        },
        {
          name: "hijri_month",
          label: "Hijri Month",
          labelDari: "ماه هجری",
          meaning: "Month of the work day — for monthly rollups (1–12)",
          type: "text",
          required: true,
          example: "03",
          rules: "Derived from date; used in month-end reports",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Daily work report notes — sections completed, delays, special conditions",
          type: "longtext",
          required: false,
          example: "Normal shift — section 4 repair completed",
        },
        {
          name: "responsible_person",
          label: "Responsible Person",
          labelDari: "شخص مسئول",
          meaning: "Supervisor or clerk who prepared/signed this work report",
          type: "text",
          required: true,
          example: "Mohammad Rahim — Site Supervisor",
        },
        {
          name: "file",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional scanned daily work sheet",
          type: "file",
          required: false,
          example: "work_sheet_scan.pdf",
        },
        {
          name: "total_permanent_repair_cm",
          label: "Total Permanent Repair (cm)",
          labelDari: "مجموع ترمیم اساسی (سانتی)",
          meaning: "Sum of permanent_repair_cm across all work lines",
          type: "decimal",
          required: true,
          example: "1250",
          rules: "Read-only day total",
        },
        {
          name: "total_continuous_repair_cm",
          label: "Total Continuous Repair (cm)",
          labelDari: "مجموع ترمیم جاری (سانتی)",
          meaning: "Sum of continuous_repair_cm across all work lines",
          type: "decimal",
          required: true,
          example: "890",
          rules: "Read-only day total",
        },
        {
          name: "total_digging_cm",
          label: "Total Digging (cm)",
          labelDari: "مجموع حفریات (سانتی)",
          meaning: "Sum of digging_cm across all work lines",
          type: "decimal",
          required: true,
          example: "340",
          rules: "Read-only day total",
        },
        {
          name: "total_wagon",
          label: "Total Wagon",
          labelDari: "مجموع ویگن",
          meaning: "Sum of wagon units across all work lines",
          type: "decimal",
          required: true,
          example: "18",
          rules: "Read-only day total",
        },
        {
          name: "total_ton",
          label: "Total Ton",
          labelDari: "مجموع تن",
          meaning: "Sum of ton across all work lines",
          type: "decimal",
          required: true,
          example: "220",
          rules: "Read-only day total",
        },
        {
          name: "grand_total_pay",
          label: "Grand Total Pay (AFN)",
          labelDari: "مجموع کل معاش روز",
          meaning: "Sum of all line pay totals for the day",
          type: "decimal",
          required: true,
          example: "485000",
          rules: "Read-only",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | submitted | approved",
          type: "enum",
          required: true,
          example: "submitted",
        },
      ],
    },
    {
      id: "ENT-SITE-021",
      name: "Daily Work Line",
      description:
        "One row per present employee on the daily work sheet — work quantities and calculated pay. Absent employees are not listed.",
      fields: [
        {
          name: "work_report_id",
          label: "Work Report",
          labelDari: "گزارش کار",
          meaning: "Parent — reference → ENT-SITE-020",
          type: "reference",
          required: true,
          example: "DWR-KRK-1405/03/15",
        },
        {
          name: "employee_id",
          label: "Employee",
          labelDari: "کارمند",
          meaning: "Reference → Contract Employee (ENT-SITE-012) — present on linked attendance only",
          type: "reference",
          required: true,
          example: "CE-KRK-0042 — Ahmad بن Karim",
          rules: "Present employees from ENT-SITE-019 only; one line per employee per day; group resolved from ENT-SITE-012 active group_id",
        },
        {
          name: "employee_type",
          label: "Type",
          labelDari: "نوع",
          meaning: "Snapshot of employee_type on this day — worker, group_leader, etc.",
          type: "enum",
          required: true,
          example: "worker",
          rules: "Read-only from employee record",
        },
        {
          name: "permanent_repair_cm",
          label: "Permanent Repair (cm)",
          labelDari: "ترمیم اساسی (سانتی)",
          meaning: "Cm of ترمیم اساسی — × site permanent_repair_rate",
          type: "decimal",
          required: false,
          example: "45",
        },
        {
          name: "continuous_repair_cm",
          label: "Continuous Repair (cm)",
          labelDari: "ترمیم جاری (سانتی)",
          meaning: "Cm of ترمیم جاری — × site continuous_repair_rate",
          type: "decimal",
          required: false,
          example: "30",
        },
        {
          name: "digging_cm",
          label: "Digging (cm)",
          labelDari: "حفریات (سانتی)",
          meaning: "Cm of حفریات — × site digging_rate",
          type: "decimal",
          required: false,
          example: "12",
        },
        {
          name: "wagon",
          label: "Wagon",
          labelDari: "ویگن",
          meaning: "Wagon units — × site wagon_rate",
          type: "decimal",
          required: false,
          example: "2",
        },
        {
          name: "ton",
          label: "Ton",
          labelDari: "تن",
          meaning: "Tons — × site ton_rate",
          type: "decimal",
          required: false,
          example: "5",
        },
        {
          name: "line_description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Optional notes for this person's work today",
          type: "longtext",
          required: false,
          example: "Section 4 rail repair",
        },
        {
          name: "line_total_pay",
          label: "Line Total Pay (AFN)",
          labelDari: "مجموع معاش (افغانی)",
          meaning: "Auto: sum of (qty × rate) for each work type using ENT-SITE-011 current rates",
          type: "decimal",
          required: true,
          example: "12500",
          rules: "Read-only",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-SITE-020",
      name: "Record daily work",
      trigger: "After attendance approved — end of work day at site",
      startActor: "Site Clerk",
      endState: "Daily work report submitted with totals",
      flowDiagram:
        "Select site + date → load approved attendance → present employees by group → enter work quantities → auto totals → responsible person → submit",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Open or create daily work report",
          input: "site_id, date (Hijri)",
          output: "ENT-SITE-020 draft linked to approved ENT-SITE-018; present employees loaded and auto-grouped by each employee's active group_id (ENT-SITE-012)",
        },
        {
          step: 2,
          actor: "Site Clerk",
          action: "Enter work quantities for present employees",
          input: "permanent_repair_cm, continuous_repair_cm, digging_cm, wagon, ton, optional line_description",
          output: "line_total_pay calculated from ENT-SITE-011 rates",
        },
        {
          step: 3,
          actor: "Site Clerk",
          action: "Review day totals and add header notes",
          input: "description, responsible_person, optional file",
          output: "Day totals: each work type sum + grand_total_pay",
        },
        {
          step: 4,
          actor: "Site Supervisor",
          action: "Approve daily work report",
          input: "Review totals",
          output: "status: approved",
        },
      ],
    },
    {
      id: "WF-SITE-021",
      name: "Month-end salary rollup",
      trigger: "End of Hijri month",
      startActor: "Site Clerk",
      endState: "Monthly salary report with tax — printable",
      flowDiagram:
        "Select site + Hijri month → aggregate all approved daily work lines → gross, tax, net per person",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Run monthly report",
          input: "site_id, hijri_month, optional year from date",
          output: "Per employee: days present (from attendance), totals per work type, gross salary",
        },
        {
          step: 2,
          actor: "System",
          action: "Apply tax and compute net",
          input: "gross salary, configurable tax rate or fixed deduction",
          output: "tax_amount, net_salary per employee",
        },
        {
          step: 3,
          actor: "Site Supervisor",
          action: "Print monthly payroll",
          input: "Approved month data",
          output: "PDF — 8 employees per page; daily pay numbers shown per person",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-SITE-022",
      rule: "One daily work report per site per Hijri date — no duplicate sheets",
      trigger: "Create daily work report",
      response: "Block duplicate site_id + date",
      severity: "Critical",
    },
    {
      id: "BR-SITE-023",
      rule: "Daily work report requires approved attendance sheet for same site + date",
      trigger: "Create daily work report",
      response: "Block if ENT-SITE-018 not approved",
      severity: "Critical",
    },
    {
      id: "BR-SITE-024",
      rule: "Only employees marked present on attendance appear on work report — absent employees excluded",
      trigger: "Load daily work report",
      response: "Filter to attendance=present from linked ENT-SITE-019",
      severity: "Critical",
    },
    {
      id: "BR-SITE-025",
      rule: "line_total_pay = (permanent_repair_cm × rate) + (continuous_repair_cm × rate) + (digging_cm × rate) + (wagon × rate) + (ton × rate) using current ENT-SITE-011 for site",
      trigger: "Save work line",
      response: "Auto-calculate",
      severity: "Critical",
    },
    {
      id: "BR-SITE-026",
      rule: "Daily work sheet auto-groups present employees by each employee's active group_id (ENT-SITE-012) — no group field on work line",
      trigger: "Load daily work report",
      response: "Resolve group from employee record; sort by group then name; display group header, employee name + father_name + type",
      severity: "Medium",
    },
    {
      id: "BR-SITE-027",
      rule: "Month-end gross salary = sum of line_total_pay for all work days in the Hijri month",
      trigger: "Monthly report",
      response: "Aggregate by employee_id",
      severity: "Critical",
    },
    {
      id: "BR-SITE-028",
      rule: "Monthly printable layout — 8 employees per page with daily pay numbers and type/work breakdown",
      trigger: "Print monthly report",
      response: "Paginate 8 per page; include each day's line_total_pay in grid",
      severity: "High",
    },
  ],
  validationRules: [
    {
      field: "date",
      rule: "Required Hijri date — must have approved attendance",
      uiBehavior: "Date picker — loads or creates work report for site + date",
    },
    {
      field: "work grid",
      rule: "Present employees only from approved attendance; auto-grouped by employee active group_id",
      uiBehavior: "Grouped sections per work group; numeric work fields; line total updates live",
    },
    {
      field: "daily totals",
      rule: "Footer shows each work type sum and grand pay",
      uiBehavior: "Read-only summary bar on sheet",
    },
    {
      field: "monthly print",
      rule: "8 people per page; columns: name, father_name, type, each work type month total, gross, tax, net, daily numbers",
      uiBehavior: "Print preview with page breaks",
    },
  ],
  integrations: [
    {
      id: "INT-SITE-020",
      direction: "in",
      module: "Site — Daily Attendance (ENT-SITE-018/019)",
      data: "present employees for site + date",
      when: "Daily work report load",
    },
    {
      id: "INT-SITE-021",
      direction: "in",
      module: "Site — Contract Employees (ENT-SITE-012), Work Rates (ENT-SITE-011), Groups (ENT-SITE-010)",
      data: "employee details, rates, group names",
      when: "Pay calculation",
    },
    {
      id: "INT-SITE-022",
      direction: "out",
      module: "Salaries — Payroll (future)",
      data: "monthly gross, tax, net per contract employee",
      when: "Month-end approval",
      note: "Future handoff to معاشات if needed",
    },
  ],
  crossModuleNotes: [
    "Salary is based on work done — no fixed daily wage; no work line = zero pay for that day.",
    "Work report depends on approved attendance — present employees only.",
    "Work rates come from ENT-SITE-011 — must be configured before first work report.",
  ],
  reports: [
    {
      id: "RPT-SITE-020",
      name: "Daily work sheet (printable)",
      purpose: "Full daily work report — groups, each present person with work quantities, day totals",
      filters: "site_id, date",
      columns:
        "group, name, father_name, type, permanent_repair_cm, continuous_repair_cm, digging_cm, wagon, ton, line_total_pay | footer: day totals",
      export: "PDF — printable",
    },
    {
      id: "RPT-SITE-021",
      name: "Daily work list by group",
      purpose: "Same day grouped view for supervisor sign-off",
      filters: "site_id, date",
      columns: "group, name, father_name, type, line_total_pay",
      export: "PDF, Excel",
    },
    {
      id: "RPT-SITE-022",
      name: "Monthly work by person",
      purpose: "Each employee — total days present, each work type month sum, gross salary",
      filters: "site_id, hijri_month, optional year from date",
      columns:
        "name, father_name, type, group (from employee), days_present, permanent_repair_cm, continuous_repair_cm, digging_cm, wagon, ton, gross_salary",
      export: "Excel, PDF",
    },
    {
      id: "RPT-SITE-023",
      name: "Monthly salary with tax (printable)",
      purpose: "Payroll sheet — 8 employees per page, daily numbers, tax, net",
      filters: "site_id, hijri_month, optional year from date",
      columns:
        "name, father_name, type, daily_pay_grid (each day number), gross, tax, net — 8 per page",
      export: "PDF — printable",
    },
    {
      id: "RPT-SITE-024",
      name: "Monthly totals by work type",
      purpose: "Site-wide month sum per work unit",
      filters: "site_id, hijri_month, optional year from date",
      columns: "work_type, total_quantity, total_pay_afn",
      export: "Excel, PDF",
    },
    {
      id: "RPT-SITE-025",
      name: "Daily pay summary",
      purpose: "Grand pay total per day in month",
      filters: "site_id, hijri_month, optional year from date",
      columns: "date, grand_total_pay, employee_count",
      export: "Excel, PDF",
    },
  ],
  deliverableChecklist: [
    { item: "Work quantities with site rate calculation", done: true },
    { item: "Linked to approved attendance", done: true },
    { item: "Day totals and monthly salary rollup", done: true },
    { item: "Printable monthly — 8 per page with daily numbers", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
