import type { SectionDefinition } from "@/types/requirements";

export const dailyAttendanceSection: SectionDefinition = {
  id: "daily-attendance",
  name: "Daily Attendance",
  nameDari: "حاضری روزانه",
  enableReview: true,
  description:
    "Daily attendance sheet per site — select Hijri date and site, mark all active contract employees present or absent. No leave types. Simple flat list by employee name. Day footer shows total present and total absent.",
  status: "draft",
  currentTool: "Paper daily attendance registers",
  summary: [
    "Select site + Hijri date — load all active contract employees",
    "Each line: present | absent only — no leave types",
    "Day footer: total present, total absent",
    "Header: description, responsible person; optional file",
    "Must be completed before daily work report for the same site + date",
    "Reports: daily sheet per site, compare days, monthly summary, employee register, absent list, attendance rate",
  ],
  precededBy: [
    {
      moduleId: "site",
      sectionId: "contract-employees",
      label: "Contract Employees",
    },
  ],
  followedBy: [
    {
      moduleId: "site",
      sectionId: "daily-work-report",
      label: "Daily Work Report",
    },
  ],
  relatedSections: ["contract-employees", "daily-work-report", "general-tables"],
  roles: [
    {
      role: "Site Clerk",
      location: "Mine / field site",
      mainActions: "Mark daily present/absent for all active employees",
      approval: false,
      readOnly: false,
    },
    {
      role: "Site Supervisor",
      location: "Mine / field site",
      mainActions: "Review and sign attendance sheet",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View attendance history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-SITE-018",
      name: "Daily Attendance Sheet",
      description:
        "One attendance register per site per Hijri date — header with headcount totals; child lines for each active employee.",
      fields: [
        {
          name: "attendance_id",
          label: "Attendance ID",
          labelDari: "شناسه حاضری",
          meaning: "Auto-generated daily attendance number",
          type: "text",
          required: true,
          example: "ATT-KRK-1405/03/15",
          rules: "Unique per site + date",
        },
        {
          name: "site_id",
          label: "Site",
          labelDari: "سایت",
          meaning: "Reference → Mining Site (ENT-OPR-G004)",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "date",
          label: "Date",
          labelDari: "تاریخ",
          meaning: "Work day — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/03/15",
        },
        {
          name: "hijri_month",
          label: "Hijri Month",
          labelDari: "ماه هجری",
          meaning: "Month of the work day — for monthly rollups (1–12)",
          type: "text",
          required: true,
          example: "03",
          rules: "Derived from date",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Optional notes — weather, delays, special conditions",
          type: "longtext",
          required: false,
          example: "Normal shift — full crew expected",
        },
        {
          name: "responsible_person",
          label: "Responsible Person",
          labelDari: "شخص مسئول",
          meaning: "Supervisor or clerk who prepared/signed this attendance sheet",
          type: "text",
          required: true,
          example: "Mohammad Rahim — Site Supervisor",
        },
        {
          name: "file",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional scanned attendance register",
          type: "file",
          required: false,
          example: "attendance_scan.pdf",
        },
        {
          name: "total_present",
          label: "Total Present",
          labelDari: "مجموع حاضر",
          meaning: "Count of employees marked present — auto-calculated",
          type: "decimal",
          required: true,
          example: "42",
          rules: "Read-only; sum of lines with attendance=present",
        },
        {
          name: "total_absent",
          label: "Total Absent",
          labelDari: "مجموع غایب",
          meaning: "Count marked absent — auto-calculated",
          type: "decimal",
          required: true,
          example: "3",
          rules: "Read-only; no leave types — present or absent only",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | submitted | approved",
          type: "enum",
          required: true,
          example: "submitted",
        },
      ],
    },
    {
      id: "ENT-SITE-019",
      name: "Attendance Line",
      description:
        "One row per active contract employee on the attendance sheet — present or absent only.",
      fields: [
        {
          name: "attendance_sheet_id",
          label: "Attendance Sheet",
          labelDari: "برگه حاضری",
          meaning: "Parent — reference → ENT-SITE-018",
          type: "reference",
          required: true,
          example: "ATT-KRK-1405/03/15",
        },
        {
          name: "employee_id",
          label: "Employee",
          labelDari: "کارمند",
          meaning: "Reference → Contract Employee (ENT-SITE-012) — shows name and father_name",
          type: "reference",
          required: true,
          example: "CE-KRK-0042 — Ahmad بن Karim",
          rules: "Active employees at this site only; one line per employee per day",
        },
        {
          name: "attendance",
          label: "Attendance",
          labelDari: "حاضری",
          meaning: "present | absent",
          type: "enum",
          required: true,
          example: "present",
          rules: "No leave types — present or absent only",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-SITE-018",
      name: "Record daily attendance",
      trigger: "Start of or during work day at site",
      startActor: "Site Clerk",
      endState: "Attendance sheet submitted with headcount totals",
      flowDiagram:
        "Select site + date → load active employees → mark present/absent → responsible person → submit",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Open or create attendance sheet",
          input: "site_id, date (Hijri)",
          output: "ENT-SITE-018 draft; all active ENT-SITE-012 loaded",
        },
        {
          step: 2,
          actor: "Site Clerk",
          action: "Mark attendance for each employee",
          input: "present | absent per line",
          output: "total_present and total_absent updating live",
        },
        {
          step: 3,
          actor: "Site Clerk",
          action: "Add header notes and responsible person",
          input: "description, responsible_person, optional file",
          output: "Sheet ready for supervisor review",
        },
        {
          step: 4,
          actor: "Site Supervisor",
          action: "Approve attendance sheet",
          input: "Review headcount",
          output: "status: approved — unlocks daily work report for same site + date",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-SITE-018",
      rule: "One attendance sheet per site per Hijri date — no duplicate registers",
      trigger: "Create attendance sheet",
      response: "Block duplicate site_id + date",
      severity: "Critical",
    },
    {
      id: "BR-SITE-019",
      rule: "Attendance sheet lists employees by name — name and father_name shown on each line",
      trigger: "Load attendance sheet",
      response: "Sort by name; display employee name + father_name",
      severity: "Medium",
    },
    {
      id: "BR-SITE-020",
      rule: "Only active contract employees appear on attendance sheet",
      trigger: "Load attendance sheet",
      response: "Filter status=active only",
      severity: "Critical",
    },
    {
      id: "BR-SITE-021",
      rule: "Daily work report requires approved attendance for same site + date",
      trigger: "Create daily work report",
      response: "Block if no approved ENT-SITE-018 for site_id + date",
      severity: "Critical",
    },
  ],
  validationRules: [
    {
      field: "date",
      rule: "Required Hijri date",
      uiBehavior: "Date picker — loads or creates sheet for site + date",
    },
    {
      field: "attendance grid",
      rule: "All active site employees shown; checkbox present/absent",
      uiBehavior: "Flat list of all active employees; checkbox present/absent per row",
    },
    {
      field: "daily totals",
      rule: "Footer shows total present and total absent",
      uiBehavior: "Read-only summary bar on sheet",
    },
  ],
  integrations: [
    {
      id: "INT-SITE-018",
      direction: "in",
      module: "Site — Contract Employees (ENT-SITE-012)",
      data: "employee list",
      when: "Attendance sheet load",
    },
    {
      id: "INT-SITE-019",
      direction: "out",
      module: "Site — Daily Work Report (ENT-SITE-020)",
      data: "attendance lines — present employees only",
      when: "Daily work report load for same site + date",
    },
  ],
  crossModuleNotes: [
    "Attendance is separate from work entry — salary is based on work done, but only present employees appear on the work report.",
    "Hijri date drives daily attendance; monthly summaries filter by Hijri month.",
  ],
  reports: [
    {
      id: "RPT-SITE-018",
      name: "Daily attendance sheet per site (printable)",
      purpose:
        "Full attendance register for one site on one Hijri day — every active employee with present/absent and day totals. Primary daily sign-off sheet.",
      filters: "site_id (required), date (required)",
      columns:
        "site, date, name, father_name, attendance | footer: total_present, total_absent, responsible_person",
      export: "PDF — printable",
    },
    {
      id: "RPT-SITE-019",
      name: "Compare days",
      purpose:
        "Side-by-side comparison of attendance for the same site across two or more Hijri dates — headcount changes and employee-level present/absent differences.",
      filters: "site_id (required), dates (select 2+ Hijri days)",
      columns:
        "date, total_present, total_absent, change_vs_previous | optional detail: employee, status_per_date (present/absent/changed)",
      export: "PDF, Excel",
    },
    {
      id: "RPT-SITE-026",
      name: "Monthly attendance by site",
      purpose:
        "One site, one Hijri month — present and absent counts for each day; spot trends and low-attendance days.",
      filters: "site_id (required), hijri_month (required), optional year from date",
      columns: "date, total_present, total_absent, active_employee_count, attendance_pct",
      export: "Excel, PDF — printable",
    },
    {
      id: "RPT-SITE-027",
      name: "Employee attendance register",
      purpose:
        "Per employee over a Hijri date range — days present, days absent, and attendance rate. Filter by site and/or employee.",
      filters: "site_id, employee_id, Hijri date from/to, attendance status (present | absent | all)",
      columns: "employee_code, name, father_name, site, days_present, days_absent, total_days, attendance_pct",
      export: "Excel, PDF",
    },
    {
      id: "RPT-SITE-028",
      name: "Absent employees list",
      purpose:
        "Who was absent — on a single day or across a date range. Shows each absent occurrence and total absent days in the period.",
      filters: "site_id, date (single day) or Hijri date from/to, optional min absent days",
      columns: "name, father_name, site, date, absent_days_in_period",
      export: "Excel, PDF — printable",
    },
    {
      id: "RPT-SITE-029",
      name: "Attendance rate by site",
      purpose:
        "Summary across all sites for a Hijri date range — average present/absent per day and overall attendance percentage per site.",
      filters: "Hijri date from/to, site_id (optional — all sites if empty)",
      columns:
        "site, days_with_data, avg_present, avg_absent, total_present, total_absent, attendance_pct",
      export: "Excel, PDF",
    },
  ],
  deliverableChecklist: [
    { item: "Daily attendance present/absent defined", done: true },
    { item: "Flat employee list with day totals", done: true },
    { item: "Links to daily work report task", done: true },
    { item: "Six attendance reports — daily per site, compare days, and four analytics", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
