import type { SectionDefinition } from "@/types/requirements";

export const siteRequestsCirculationSection: SectionDefinition = {
  id: "site-requests-circulation",
  name: "Site Requests & Item Circulation",
  nameDari: "درخواست سایت و چګ صادره / چک وارده",
  enableReview: true,
  description:
    "Site-level register for requests to main office and simple item circulation. When the site needs something from HQ, clerks save a request (title, description, file, status, date). When HQ sends materials to the site, record چک وارده (in). When issuing items to contract workers at the site, record چګ صادره (out). Simpler than Items department ledger — no account books, product master, or stock lots; free-text item lines only.",
  status: "draft",
  currentTool: "Paper site request slips and handwritten چګ صادره / چک وارده registers",
  summary: [
    "Site Request — id, title, description, file, status, Hijri date, site, requested_by",
    "چک وارده (in) — record what main office / HQ sent to this site",
    "چګ صادره (out) — record what the site issued to contract workers",
    "Simple item lines on circulation vouchers — item name, quantity, unit, optional note",
    "Optional link from چک وارده to an approved Site Request when delivery fulfills a request",
    "Reports: open requests, circulation by direction, by person, by site and date range",
  ],
  relatedSections: ["contract-employees", "general-tables"],
  roles: [
    {
      role: "Site Clerk",
      location: "Mine / field site",
      mainActions: "Create site requests; post چک وارده and چګ صادره vouchers",
      approval: false,
      readOnly: false,
    },
    {
      role: "Site Supervisor",
      location: "Mine / field site",
      mainActions: "Review and approve site requests; sign circulation vouchers",
      approval: true,
      readOnly: false,
    },
    {
      role: "HQ / Main Office Clerk",
      location: "HQ",
      mainActions: "View site requests; mark fulfilled when items dispatched",
      approval: false,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View requests and circulation history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-SITE-030",
      name: "Site Request",
      description:
        "Request from a mine/field site to main office — what the site needs. Saved with title, description, optional attachment, and workflow status.",
      fields: [
        {
          name: "request_id",
          label: "Request ID",
          labelDari: "شناسه درخواست",
          meaning: "Auto-generated site request number",
          type: "text",
          required: true,
          example: "SRQ-KRK-0042/1405",
          rules: "Unique; system-generated on create",
        },
        {
          name: "site_id",
          label: "Site",
          labelDari: "سایت / معدن",
          meaning: "Reference → Mining Site (ENT-OPR-G004)",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "title",
          label: "Title",
          labelDari: "عنوان",
          meaning: "Short summary of what is needed",
          type: "text",
          required: true,
          example: "Safety helmets for Group A",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Full details — quantities, urgency, reason",
          type: "longtext",
          required: true,
          example: "20 helmets needed before next shift; current stock depleted",
        },
        {
          name: "date",
          label: "Request Date",
          labelDari: "تاریخ درخواست",
          meaning: "Hijri date the request was created",
          type: "hijri_date",
          required: true,
          example: "1405/03/10",
        },
        {
          name: "mali_year",
          label: "Mali Year",
          labelDari: "سال مالی",
          meaning: "Fiscal year",
          type: "enum",
          required: true,
          example: "1405",
        },
        {
          name: "requested_by",
          label: "Requested By",
          labelDari: "درخواست کننده",
          meaning: "Site clerk or supervisor who submitted",
          type: "text",
          required: true,
          example: "Ahmad — Site Clerk",
        },
        {
          name: "file",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional scan of paper request or supporting photo",
          type: "file",
          required: false,
          example: "site_request_42.pdf",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | submitted | approved | rejected | fulfilled | cancelled",
          type: "enum",
          required: true,
          example: "submitted",
        },
        {
          name: "approved_by",
          label: "Approved By",
          labelDari: "تأیید شده توسط",
          meaning: "Supervisor or HQ approver — when status is approved or fulfilled",
          type: "text",
          required: false,
          example: "Mohammad Rahim — Site Supervisor",
        },
        {
          name: "fulfilled_date",
          label: "Fulfilled Date",
          labelDari: "تاریخ تحویل",
          meaning: "Hijri date when items were received at site — optional until fulfilled",
          type: "hijri_date",
          required: false,
          example: "1405/03/18",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Internal notes — HQ response, rejection reason, etc.",
          type: "longtext",
          required: false,
          example: "Dispatched via Items department — see IMV-0088",
        },
      ],
    },
    {
      id: "ENT-SITE-031",
      name: "Site Circulation Voucher (چګ صادره / چک وارده)",
      description:
        "Simple site item movement — in when HQ/main office sends to site; out when site issues to contract workers. No ledger books or stock lots.",
      fields: [
        {
          name: "voucher_id",
          label: "Voucher ID",
          labelDari: "شناسه سند",
          meaning: "Auto-generated circulation number",
          type: "text",
          required: true,
          example: "SCV-KRK-0088/1405",
          rules: "Unique; system-generated",
        },
        {
          name: "paper_number",
          label: "Paper Number",
          labelDari: "شماره کاغذی",
          meaning: "Optional handwritten slip number",
          type: "text",
          required: false,
          example: "45/1405",
        },
        {
          name: "direction",
          label: "Direction",
          labelDari: "جهت",
          meaning: "in (چک وارده — from main office) | out (چګ صادره — to site worker)",
          type: "enum",
          required: true,
          example: "in",
        },
        {
          name: "title",
          label: "Title",
          labelDari: "عنوان",
          meaning: "Short label for this voucher",
          type: "text",
          required: true,
          example: "March safety gear delivery",
        },
        {
          name: "site_id",
          label: "Site",
          labelDari: "سایت",
          meaning: "Reference → Mining Site (ENT-OPR-G004)",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "date",
          label: "Date",
          labelDari: "تاریخ",
          meaning: "Voucher date — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/03/18",
        },
        {
          name: "mali_year",
          label: "Mali Year",
          labelDari: "سال مالی",
          meaning: "Fiscal year",
          type: "enum",
          required: true,
          example: "1405",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Summary of movement — source, destination, purpose",
          type: "longtext",
          required: true,
          example: "Received 20 helmets from HQ Items department",
        },
        {
          name: "related_person_id",
          label: "Related Person",
          labelDari: "شخص مربوط",
          meaning: "Reference → Contract Employee (ENT-SITE-012) — required on چګ صادره (out); optional on چک وارده",
          type: "reference",
          required: "conditional",
          example: "CE-KRK-0042 — Ahmad بن Karim",
          rules: "Required when direction=out; optional when direction=in",
        },
        {
          name: "source",
          label: "Source",
          labelDari: "منبع",
          meaning: "Where items came from — e.g. HQ Items, Storage, supplier name",
          type: "text",
          required: "conditional",
          example: "HQ — محاسبه اجناس",
          rules: "Required when direction=in",
        },
        {
          name: "site_request_id",
          label: "Linked Site Request",
          labelDari: "درخواست مرتبط",
          meaning: "Optional reference → Site Request (ENT-SITE-030) when this delivery fulfills a request",
          type: "reference",
          required: false,
          example: "SRQ-KRK-0042/1405",
        },
        {
          name: "created_by",
          label: "Created By",
          labelDari: "ثبت شده توسط",
          meaning: "Clerk who posted the voucher",
          type: "text",
          required: true,
          example: "Site Clerk — Ahmad",
        },
        {
          name: "file",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional scan of paper چګ / چک slip",
          type: "file",
          required: false,
          example: "chag_45.pdf",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | posted | cancelled",
          type: "enum",
          required: true,
          example: "posted",
        },
      ],
    },
    {
      id: "ENT-SITE-032",
      name: "Site Circulation Line",
      description: "One item row on a site circulation voucher — free text, no product master.",
      fields: [
        {
          name: "voucher_id",
          label: "Voucher",
          labelDari: "سند",
          meaning: "Parent — reference → ENT-SITE-031",
          type: "reference",
          required: true,
          example: "SCV-KRK-0088/1405",
        },
        {
          name: "line_number",
          label: "Line",
          labelDari: "ردیف",
          meaning: "Sequence on voucher",
          type: "text",
          required: true,
          example: "1",
        },
        {
          name: "item_name",
          label: "Item Name",
          labelDari: "نام جنس",
          meaning: "Free-text item description",
          type: "text",
          required: true,
          example: "Safety helmet",
        },
        {
          name: "quantity",
          label: "Quantity",
          labelDari: "مقدار",
          meaning: "Amount issued or received",
          type: "decimal",
          required: true,
          example: "5",
        },
        {
          name: "unit",
          label: "Unit",
          labelDari: "واحد",
          meaning: "piece, kg, litre, box, etc.",
          type: "text",
          required: true,
          example: "piece",
        },
        {
          name: "line_note",
          label: "Line Note",
          labelDari: "یادداشت ردیف",
          meaning: "Optional detail for this line",
          type: "longtext",
          required: false,
          example: "Size L — Group A",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-SITE-030",
      name: "Submit site request to main office",
      trigger: "Site needs materials or support from HQ",
      startActor: "Site Clerk",
      endState: "Request submitted — pending HQ review",
      flowDiagram:
        "Create request → title, description, date, optional file → submit → supervisor approve → HQ fulfills",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Create site request",
          input: "site_id, title, description, date, optional file",
          output: "ENT-SITE-030 draft",
        },
        {
          step: 2,
          actor: "Site Clerk",
          action: "Submit for approval",
          input: "Complete request",
          output: "status: submitted",
        },
        {
          step: 3,
          actor: "Site Supervisor",
          action: "Approve or reject",
          input: "Review request",
          output: "status: approved | rejected",
        },
        {
          step: 4,
          actor: "HQ Clerk",
          action: "Fulfill and mark complete",
          input: "Dispatch items; optional link to چک وارده voucher",
          output: "status: fulfilled; fulfilled_date set",
        },
      ],
    },
    {
      id: "WF-SITE-031",
      name: "چک وارده — receive from main office",
      trigger: "HQ or main office sends items to site",
      startActor: "Site Clerk",
      endState: "Posted in-voucher with item lines",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Create in voucher",
          input: "direction=in, site_id, title, description, source, date, optional site_request_id",
          output: "Draft SCV",
        },
        {
          step: 2,
          actor: "Site Clerk",
          action: "Add item lines",
          input: "item_name, quantity, unit per line",
          output: "Posted voucher; optional mark linked request fulfilled",
        },
      ],
    },
    {
      id: "WF-SITE-032",
      name: "چګ صادره — issue to site worker",
      trigger: "Site distributes items to contract employee",
      startActor: "Site Clerk",
      endState: "Posted out-voucher with person and item lines",
      steps: [
        {
          step: 1,
          actor: "Site Clerk",
          action: "Create out voucher",
          input: "direction=out, site_id, related_person_id, title, description, date",
          output: "Draft SCV",
        },
        {
          step: 2,
          actor: "Site Clerk",
          action: "Add item lines and post",
          input: "item_name, quantity, unit per line; optional file",
          output: "Posted چګ صادره",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-SITE-030",
      rule: "Site request_id auto-generated on create — format SRQ-{site}-{seq}/{mali_year}",
      trigger: "Create site request",
      response: "Assign unique number; read-only after save",
      severity: "Critical",
    },
    {
      id: "BR-SITE-031",
      rule: "Circulation voucher_id auto-generated — format SCV-{site}-{seq}/{mali_year}",
      trigger: "Create circulation voucher",
      response: "Assign unique number",
      severity: "Critical",
    },
    {
      id: "BR-SITE-032",
      rule: "related_person_id required when direction=out (چګ صادره)",
      trigger: "Post out voucher",
      response: "Block if missing — must select contract employee",
      severity: "Critical",
    },
    {
      id: "BR-SITE-033",
      rule: "source required when direction=in (چک وارده)",
      trigger: "Post in voucher",
      response: "Block if missing",
      severity: "Critical",
    },
    {
      id: "BR-SITE-034",
      rule: "Circulation voucher must have at least one item line before posting",
      trigger: "Post voucher",
      response: "Block empty lines",
      severity: "Critical",
    },
    {
      id: "BR-SITE-035",
      rule: "Linking site_request_id on چک وارده can auto-set request status to fulfilled",
      trigger: "Post in voucher with site_request_id",
      response: "Prompt to mark ENT-SITE-030 fulfilled with fulfilled_date",
      severity: "Medium",
    },
    {
      id: "BR-SITE-036",
      rule: "related_person_id must be active contract employee on same site",
      trigger: "Select person on out voucher",
      response: "Filter ENT-SITE-012 by site_id and status=active",
      severity: "High",
    },
    {
      id: "BR-SITE-037",
      rule: "Standalone site register — does not post to Items department ledger",
      trigger: "Any save",
      response: "Site circulation is local record only; HQ Items uses its own چګ / چک",
      severity: "High",
    },
  ],
  permissionsMatrix: [
    { action: "Create & submit site requests", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "R" },
    { action: "Approve site requests", archiveClerk: "—", executive: "A", deptStaff: "A", auditor: "—" },
    { action: "Post چک وارده / چګ صادره", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "R" },
    { action: "Mark request fulfilled (HQ)", archiveClerk: "—", executive: "C", deptStaff: "—", auditor: "R" },
  ],
  reports: [
    {
      id: "RPT-SITE-030",
      name: "Site request register",
      purpose: "All requests for one site — open and closed",
      filters: "site_id, status, mali_year, Hijri date range",
      columns: "request_id, title, date, requested_by, status, fulfilled_date",
      export: "PDF, Excel",
    },
    {
      id: "RPT-SITE-031",
      name: "Open site requests",
      purpose: "Pending requests awaiting HQ action",
      filters: "site_id (optional), status=submitted|approved",
      columns: "request_id, site, title, date, days_open",
      export: "PDF, Excel",
    },
    {
      id: "RPT-SITE-032",
      name: "Circulation by direction",
      purpose: "چک وارده vs چګ صادره summary for a site and period",
      filters: "site_id, direction, mali_year, Hijri date range",
      columns: "voucher_id, direction, title, date, person/source, line count",
      export: "PDF, Excel",
    },
    {
      id: "RPT-SITE-033",
      name: "Person circulation history",
      purpose: "Everything issued to one contract employee (چګ صادره)",
      filters: "related_person_id, site_id, Hijri date range",
      columns: "date, voucher_id, item lines, description",
      export: "PDF, Excel",
    },
    {
      id: "RPT-SITE-034",
      name: "Circulation voucher finder",
      purpose: "Search چګ صادره / چک وارده by number, person, or item text",
      filters: "voucher_id, site_id, direction, item_name contains, date range",
      columns: "voucher_id, direction, title, person, lines, status",
      export: "PDF, Excel",
    },
  ],
  validationRules: [
    {
      field: "title",
      rule: "Required on site request and circulation voucher",
      uiBehavior: "Text input at top of form",
    },
    {
      field: "direction",
      rule: "in | out — drives required fields and labels",
      uiBehavior: "Toggle or select — shows Source on in, Person on out",
    },
    {
      field: "item lines",
      rule: "At least one line before post",
      uiBehavior: "Add line grid — item_name, quantity, unit",
    },
    {
      field: "file",
      rule: "Optional on request and voucher",
      uiBehavior: "Upload scan of paper slip",
    },
  ],
  crossModuleNotes: [
    "Simpler than Items department (ITM) — no account books, product master, stock lots, or spend confirmation.",
    "Site records what HQ sent (چک وارده) and what workers received (چګ صادره) for local accountability.",
    "HQ Items department maintains its own ledger — site circulation does not auto-sync to ITM.",
    "Contract employees (ENT-SITE-012) used as recipients on چګ صادره.",
    "Optional site_request_id links incoming delivery to an earlier site request.",
  ],
  deliverableChecklist: [
    { item: "Site request entity with id, title, description, file, status, date", done: true },
    { item: "چک وارده / چګ صادره circulation vouchers with simple lines", done: true },
    { item: "Person required on out; source required on in", done: true },
    { item: "Request and circulation reports", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
