import type { SectionDefinition } from "@/types/requirements";

export const procureItemSection: SectionDefinition = {
  id: "procure-item",
  name: "Procure Unavailable Item",
  nameDari: "خریداری جنس ناموجود",
  enableReview: true,
  description:
    "Procurement department (تدارکات) receives requests forwarded from Storage or Items when stock is unavailable. Purchases the item, records purchase details, and after delivery coordinates distribution back through the originating department (Storage or Items).",
  status: "draft",
  currentTool: "Paper purchase orders and vendor invoices",
  summary: [
    "Receive out-of-stock requests from Storage or Items departments",
    "Create procurement order — vendor, price, quantity, expected delivery",
    "Record purchase and receipt when goods arrive",
    "Notify Storage or Items to create distribution form and issue to requester",
  ],
  precededBy: [
    {
      moduleId: "storage",
      sectionId: "fulfill-storage-request",
      label: "Review & Fulfill Storage Request",
    },
    {
      moduleId: "items",
      sectionId: "fulfill-items-request",
      label: "Review & Fulfill Items Request",
    },
  ],
  followedBy: [
    {
      moduleId: "storage",
      sectionId: "create-distribution-form",
      label: "Create Distribution Form (Storage)",
    },
    {
      moduleId: "items",
      sectionId: "create-items-distribution",
      label: "Create Items Distribution Form",
    },
  ],
  relatedSections: ["fulfill-storage-request", "fulfill-items-request", "create-distribution-form"],
  entities: [
    {
      id: "ENT-PROC-010",
      name: "Procurement Order",
      description: "Purchase record for an item not available in Storage or Items inventory.",
      fields: [
        {
          name: "procurement_number",
          label: "Procurement Number",
          labelDari: "شماره تدارکات",
          meaning: "Auto-generated PO number",
          type: "text",
          required: true,
          example: "PO-0091/1405",
        },
        {
          name: "source_request_id",
          label: "Source Request",
          labelDari: "درخواست مرجع",
          meaning: "Original SR- or IR- requisition",
          type: "reference",
          required: true,
          example: "SR-0042/1405",
        },
        {
          name: "source_department",
          label: "Fulfilling Department",
          labelDari: "ریاست توزیع‌کننده",
          meaning: "storage | items — who will distribute after purchase",
          type: "enum",
          required: true,
          example: "storage",
        },
        {
          name: "product_name",
          label: "Product",
          labelDari: "جنس",
          meaning: "Item to purchase",
          type: "text",
          required: true,
          example: "A4 Paper Ream",
        },
        {
          name: "quantity",
          label: "Quantity",
          labelDari: "مقدار",
          meaning: "Amount to purchase",
          type: "decimal",
          required: true,
          example: "10",
        },
        {
          name: "vendor_name",
          label: "Vendor",
          labelDari: "فروشنده",
          meaning: "Supplier name",
          type: "text",
          required: "on_close",
          example: "Kabul Office Supplies",
        },
        {
          name: "purchase_amount",
          label: "Purchase Amount",
          labelDari: "مبلغ خرید",
          meaning: "Total cost in AFN",
          type: "decimal",
          required: "on_close",
          example: "5000",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "pending | ordered | received | ready_to_distribute | closed",
          type: "enum",
          required: true,
          example: "ordered",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-PROC-010",
      name: "Purchase and hand back for distribution",
      trigger: "Storage or Items marks request as pending_procurement",
      startActor: "Procurement clerk",
      endState: "Goods received — Storage/Items distributes to requester",
      flowDiagram: "Receive → purchase → receive goods → notify Storage/Items → distribute",
      steps: [
        {
          step: 1,
          actor: "Procurement clerk",
          action: "Open forwarded request; create procurement order",
          input: "SR- or IR- request with pending_procurement",
          output: "PO draft with auto number",
        },
        {
          step: 2,
          actor: "Procurement clerk",
          action: "Place order with vendor; record vendor and amount",
          input: "Vendor quote",
          output: "status: ordered",
        },
        {
          step: 3,
          actor: "Procurement clerk",
          action: "Record goods received",
          input: "Delivery",
          output: "status: ready_to_distribute",
        },
        {
          step: 4,
          actor: "System",
          action: "Notify Storage or Items to create distribution form",
          input: "Received goods",
          output: "Distribution task queued in source department",
        },
        {
          step: 5,
          actor: "Storage or Items clerk",
          action: "Create distribution form and issue to requester",
          input: "Procured items",
          output: "Request closed — distributed",
        },
      ],
    },
  ],
  statusLifecycles: [
    {
      entity: "Procurement Order",
      from: "pending",
      action: "place order",
      to: "ordered",
      actor: "Procurement clerk",
    },
    {
      entity: "Procurement Order",
      from: "ordered",
      action: "receive goods",
      to: "ready_to_distribute",
      actor: "Procurement clerk",
    },
  ],
  businessRules: [
    {
      id: "BR-PROC-010",
      rule: "Procurement only accepts requests with pending_procurement status from Storage or Items",
      trigger: "Create PO",
      response: "Block direct department requests",
      severity: "Critical",
    },
  ],
  roles: [
    {
      role: "Procurement Clerk",
      location: "HQ — تدارکات",
      mainActions: "Purchase unavailable items, record vendor and receipt",
      approval: false,
      readOnly: false,
    },
  ],
  deliverableChecklist: [
    { item: "Procurement workflow documented", done: true },
    { item: "Distribution handback to Storage/Items defined", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
