import type { SectionDefinition } from "@/types/requirements";

export const projectsSection: SectionDefinition = {
  id: "projects",
  name: "Projects (Major Contracts)",
  nameDari: "پروژه‌ها / قراردادهای بزرگ",
  enableReview: true,
  description:
    "Major ENCC projects put out for bid and awarded to contractors — contract value 5,000,000 AFN or above. Records estimated vs awarded price, contract dates, type, optional line-item breakdown, and supporting files. Contract type is a dynamic General Tables list (items, services, construction, etc.) reused elsewhere.",
  status: "draft",
  currentTool: "Paper project files and bid registers",
  summary: [
    "Threshold: price_of_contract ≥ 5,000,000 AFN — below this use Small Procurement task",
    "Header: mali_year, name, estimated price + currency, awarded contract price + currency, dates, type, description, file",
    "Optional line items: product from Items Product master (ENT-ITM-015), qty, unit, price, optional description",
    "Reports: project list (search, mali_year, date), printable; summary by contract type (count, items, total price)",
  ],
  relatedSections: ["general-tables", "small-procurement", "items-product-ledger"],
  roles: [
    {
      role: "Procurement Clerk",
      location: "HQ — تدارکات",
      mainActions: "Register projects, upload files, enter optional line items",
      approval: false,
      readOnly: false,
    },
    {
      role: "Procurement Manager",
      location: "HQ — تدارکات",
      mainActions: "Review and approve major contracts, run type summaries",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View projects, line items, reports",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-PROC-030",
      name: "Project Contract",
      description:
        "Major bid project — awarded contract at 5M AFN or above. Put out for bid, then record the price ENCC awarded.",
      fields: [
        {
          name: "project_code",
          label: "Project Code",
          labelDari: "کود پروژه",
          meaning: "Auto-generated unique project number",
          type: "text",
          required: true,
          example: "PRJ-0042/1405",
          rules: "Auto-generated; unique",
        },
        {
          name: "mali_year",
          label: "Mali Year",
          labelDari: "سال مالی",
          meaning: "Fiscal year — select current ± 5",
          type: "enum",
          required: true,
          example: "1405",
        },
        {
          name: "name",
          label: "Project Name",
          labelDari: "نام پروژه",
          meaning: "Official project or contract title",
          type: "text",
          required: true,
          example: "Kabul Road Asphalt Rehabilitation Phase 2",
        },
        {
          name: "contract_type_id",
          label: "Contract Type",
          labelDari: "نوع قرارداد",
          meaning: "Reference → Procurement Contract Type (ENT-OPR-G011) — items, services, construction, etc.",
          type: "reference",
          required: true,
          example: "Construction / ساختمانی",
          rules: "Dynamic admin table in General Tables",
        },
        {
          name: "estimated_price",
          label: "Estimated Price",
          labelDari: "قیمت تخمینی",
          meaning: "Initial budget estimate before bidding",
          type: "decimal",
          required: false,
          example: "8500000",
        },
        {
          name: "estimated_price_currency",
          label: "Estimated Price Currency",
          labelDari: "واحد پول تخمینی",
          meaning: "AFN | USD",
          type: "enum",
          required: false,
          example: "AFN",
        },
        {
          name: "price_of_contract",
          label: "Contract Price (Awarded)",
          labelDari: "قیمت قرارداد",
          meaning: "Final price ENCC awarded to the winning bidder",
          type: "decimal",
          required: true,
          example: "7800000",
          rules: "Must be ≥ 5,000,000 AFN (or USD equivalent documented)",
        },
        {
          name: "contract_currency",
          label: "Contract Currency",
          labelDari: "واحد پول قرارداد",
          meaning: "AFN | USD — currency of price_of_contract",
          type: "enum",
          required: true,
          example: "AFN",
        },
        {
          name: "start_date",
          label: "Start Date",
          labelDari: "تاریخ شروع",
          meaning: "Contract start — Hijri",
          type: "hijri_date",
          required: false,
          example: "1405/01/01",
        },
        {
          name: "end_date",
          label: "End Date",
          labelDari: "تاریخ ختم",
          meaning: "Contract end — Hijri",
          type: "hijri_date",
          required: false,
          example: "1406/12/29",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Scope, bidder notes, or project summary",
          type: "longtext",
          required: false,
          example: "20 km asphalt rehabilitation — awarded after open bid",
        },
        {
          name: "file",
          label: "Contract File",
          labelDari: "فایل قرارداد",
          meaning: "Signed contract or bid award document",
          type: "file",
          required: false,
          example: "project_contract.pdf",
          rules: "PDF, JPG, PNG; max 20 MB",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | active | completed | cancelled",
          type: "enum",
          required: true,
          example: "active",
        },
      ],
    },
    {
      id: "ENT-PROC-031",
      name: "Project Line Item",
      description:
        "Optional breakdown of products/items within a major project — selected from Product master.",
      fields: [
        {
          name: "project_id",
          label: "Project",
          labelDari: "پروژه",
          meaning: "Parent project — reference → ENT-PROC-030",
          type: "reference",
          required: true,
          example: "PRJ-0042/1405",
        },
        {
          name: "line_id",
          label: "Line ID",
          labelDari: "شناسه ردیف",
          meaning: "Auto-generated row id",
          type: "text",
          required: true,
          example: "LN-0012",
        },
        {
          name: "product_id",
          label: "Product",
          labelDari: "جنس",
          meaning: "Reference → Product master (ENT-ITM-015) — searchable dropdown",
          type: "reference",
          required: true,
          example: "PRD-0088 — Asphalt mix Grade A",
          rules: "Active products only; unit auto-fills from product on select",
        },
        {
          name: "qty",
          label: "Quantity",
          labelDari: "مقدار",
          meaning: "Amount ordered or contracted",
          type: "decimal",
          required: true,
          example: "500",
        },
        {
          name: "unit",
          label: "Unit",
          labelDari: "واحد",
          meaning: "Copied from product master — editable if contract unit differs",
          type: "text",
          required: true,
          example: "ton",
          rules: "Auto-fill from product.unit; user may override",
        },
        {
          name: "price",
          label: "Unit Price",
          labelDari: "قیمت واحد",
          meaning: "Price per unit in contract currency",
          type: "decimal",
          required: true,
          example: "8500",
        },
        {
          name: "line_total",
          label: "Line Total",
          labelDari: "مجموع ردیف",
          meaning: "qty × price — auto-calculated",
          type: "decimal",
          required: true,
          example: "4250000",
          rules: "Read-only; system calculates",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Optional line notes — spec, delivery batch, work package detail",
          type: "longtext",
          required: false,
          example: "Delivered to site store in batches",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-PROC-030",
      name: "Register major project contract",
      trigger: "Project bid completed and contract awarded — value ≥ 5M AFN",
      startActor: "Procurement Clerk",
      endState: "Project active with contract file and optional line items",
      flowDiagram:
        "Create header → enter prices and dates → select contract type → upload file → add optional line items → activate",
      steps: [
        {
          step: 1,
          actor: "Procurement Clerk",
          action: "Create project record",
          input: "mali_year, name, contract_type_id, price_of_contract, contract_currency",
          output: "PRJ code assigned; threshold validated ≥ 5M AFN",
        },
        {
          step: 2,
          actor: "Procurement Clerk",
          action: "Enter estimated price",
          input: "estimated_price, estimated_price_currency (AFN/USD)",
          output: "Budget estimate on file",
        },
        {
          step: 3,
          actor: "Procurement Clerk",
          action: "Set dates and upload contract",
          input: "start_date, end_date, description, file",
          output: "Contract document attached",
        },
        {
          step: 4,
          actor: "Procurement Clerk",
          action: "Add optional line items",
          input: "product_id, qty, unit, price, optional description",
          output: "ENT-PROC-031 rows; line_total auto-calculated",
        },
        {
          step: 5,
          actor: "Procurement Manager",
          action: "Review and activate",
          input: "Verify price_of_contract ≥ 5M and file on record",
          output: "status: active",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-PROC-030",
      rule: "price_of_contract must be ≥ 5,000,000 AFN (or documented USD equivalent) — otherwise use Small Procurement",
      trigger: "Save project",
      response: "Block and redirect to small-procurement if below threshold",
      severity: "Critical",
    },
    {
      id: "BR-PROC-031",
      rule: "Project line item line_total = qty × price — auto-calculated read-only",
      trigger: "Save line item",
      response: "Recalculate on qty or price change",
      severity: "High",
    },
    {
      id: "BR-PROC-032",
      rule: "contract_type_id must reference active type from ENT-OPR-G011",
      trigger: "Select type",
      response: "Filter to is_active=true",
      severity: "Medium",
    },
    {
      id: "BR-PROC-033",
      rule: "Project line product_id must reference active product from ENT-ITM-015",
      trigger: "Add line item",
      response: "Filter dropdown to status=active; auto-fill unit from product",
      severity: "High",
    },
  ],
  validationRules: [
    {
      field: "mali_year",
      rule: "Required — current Solar Hijri year ± 5",
      uiBehavior: "Year dropdown",
    },
    {
      field: "contract_type_id",
      rule: "Required reference to General Tables Procurement Contract Type",
      uiBehavior: "Dropdown — items, services, construction, etc.",
    },
    {
      field: "price_of_contract",
      rule: "Required; ≥ 5,000,000 AFN",
      uiBehavior: "Show threshold hint; block save if below",
    },
    {
      field: "project line items",
      rule: "Optional child table; product_id from Items master; line_total auto-calculated; description optional",
      uiBehavior: "Inline editable grid on project form — searchable product select",
    },
  ],
  integrations: [
    {
      id: "INT-PROC-030",
      direction: "in",
      module: "General Tables — Procurement Contract Type (ENT-OPR-G011)",
      data: "contract_type_id, name, is_active",
      when: "Project create/edit",
    },
    {
      id: "INT-PROC-031",
      direction: "in",
      module: "Items — Product master (ENT-ITM-015)",
      data: "product_id, name, code, unit, status",
      when: "Project line item product select",
      note: "Same product catalog as Small Procurement — purchase totals roll up by product",
    },
  ],
  crossModuleNotes: [
    "Contracts below 5M AFN use Small Procurement task — same line-item pattern, simpler header.",
    "Contract type (ENT-OPR-G011) shared with Small Procurement and available for other modules.",
    "Line items select from Items Product master — register new products in Items ledger first.",
  ],
  reports: [
    {
      id: "RPT-PROC-030",
      name: "Projects list",
      purpose: "All major projects — searchable printable register",
      filters: "mali_year, contract_type_id, status, Hijri date range (start/end), free-text search on name",
      columns: "project_code, name, contract_type, price_of_contract, currency, start_date, end_date, status",
      export: "Excel, PDF — printable list",
    },
    {
      id: "RPT-PROC-031",
      name: "Projects by mali year",
      purpose: "Summary count and total contract value per fiscal year",
      filters: "mali_year",
      columns: "mali_year, project_count, total_contract_value_afn, total_contract_value_usd",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-032",
      name: "Projects by contract type",
      purpose: "Per type: how many projects, total line items bought, total price",
      filters: "mali_year, date range, contract_type_id",
      columns: "contract_type, project_count, total_line_items, total_price_afn, total_price_usd",
      export: "Excel, PDF — printable",
    },
    {
      id: "RPT-PROC-033",
      name: "Projects by date range",
      purpose: "Contracts active or awarded in a period",
      filters: "start_date, end_date, mali_year",
      columns: "project_code, name, contract_type, price_of_contract, start_date, end_date",
      export: "Excel, PDF",
    },
  ],
  deliverableChecklist: [
    { item: "Major project contract entity defined", done: true },
    { item: "Optional project line items defined", done: true },
    { item: "5M AFN threshold rule documented", done: true },
    { item: "Project reports and printable list", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
