import type { SectionDefinition } from "@/types/requirements";

export const propertyLeaseSection: SectionDefinition = {
  id: "property-lease",
  name: "Property Lease & Rent",
  nameDari: "اجاره جایداد",
  enableReview: true,
  description:
    "Full lifecycle for renting ENCC-owned properties to private tenants. Property (from Properties module) acts as the account header. Record bids, assign lessees, record rent payments (monthly, quarterly, 4-month, yearly, or custom), and run due/overdue reports. When a tenant changes: set old lessee status to ended and create a new active lessee — no separate change table.",
  status: "draft",
  currentTool: "Paper lease books and manual rent tracking",
  summary: [
    "Property = account header (ENT-PROP-020) — select from Properties register",
    "Lease Bid — person, bid amount, description, contact, status; optional attachment",
    "Lessee — name, father name, property_id, start/end dates, monthly rent, status; optional attachment",
    "Tenant change — set old lessee status=ended, add new lessee with status=active (history kept on lessee rows)",
    "Rent Payment — lessee_id dropdown shows active lessee only; monthly, 4-month, quarterly, yearly, or custom",
    "Reports: contracts due, near due, unpaid rent, collection by month and payment type",
  ],
  relatedSections: ["property-register", "general-tables"],
  roles: [
    {
      role: "Procurement Clerk",
      location: "HQ — تدارکات",
      mainActions: "Record bids, create leases, end/add lessees, record rent payments",
      approval: false,
      readOnly: false,
    },
    {
      role: "Procurement Manager",
      location: "HQ — تدارکات",
      mainActions: "Accept bids, approve leases, review overdue reports",
      approval: true,
      readOnly: false,
    },
    {
      role: "Properties Clerk",
      location: "HQ — جایداد ها",
      mainActions: "View lease status on properties; read-only on bids and payments",
      approval: false,
      readOnly: true,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View all leases, payments, and reports",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-PROC-020",
      name: "Property Lease Bid",
      description:
        "Bid submitted for renting an ENCC property. Simple record — who bid, how much, contact, and outcome.",
      fields: [
        {
          name: "bid_id",
          label: "Bid ID",
          labelDari: "شناسه پیشنهاد",
          meaning: "Auto-generated",
          type: "text",
          required: true,
          example: "BID-0042/1405",
        },
        {
          name: "property_id",
          label: "Property",
          labelDari: "جایداد",
          meaning: "Reference → Property Record (ENT-PROP-020) — the account being bid on",
          type: "reference",
          required: true,
          example: "PROP-KBL-0042 — Kabul Warehouse",
          rules: "Only properties with usage_status = not_in_use or already open for bidding",
        },
        {
          name: "person_name",
          label: "Bidder Name",
          labelDari: "نام پیشنهاد دهنده",
          meaning: "Full name of person or company bidding",
          type: "text",
          required: true,
          example: "Abdul Karim",
        },
        {
          name: "bid_amount",
          label: "Bid Amount (AFN/month)",
          labelDari: "مبلغ پیشنهاد (افغانی/ماه)",
          meaning: "Proposed monthly rent in Afghanis",
          type: "decimal",
          required: true,
          example: "85000",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Bidder notes or intended use",
          type: "longtext",
          required: false,
          example: "Will use as retail shop; offers 85000 AFN/month",
        },
        {
          name: "contact",
          label: "Contact",
          labelDari: "تماس",
          meaning: "Phone or other contact for the bidder",
          type: "text",
          required: false,
          example: "0700123456",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "pending | accepted | rejected | withdrawn",
          type: "enum",
          required: true,
          example: "pending",
        },
        {
          name: "attachment",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional supporting document",
          type: "file",
          required: false,
          example: "bid_letter.pdf",
          rules: "PDF, JPG, PNG; max 10 MB; optional",
        },
      ],
    },
    {
      id: "ENT-PROC-021",
      name: "Lessee (Lease Person)",
      description:
        "Active or historical tenant on a property. Linked to property_id like a sub-account under the property header.",
      fields: [
        {
          name: "lessee_id",
          label: "Lessee ID",
          labelDari: "شناسه مستاجر",
          meaning: "Auto-generated unique lessee code",
          type: "text",
          required: true,
          example: "LES-0018/1405",
        },
        {
          name: "name",
          label: "Name",
          labelDari: "نام",
          meaning: "Lessee given name",
          type: "text",
          required: true,
          example: "Abdul Karim",
        },
        {
          name: "father_name",
          label: "Father Name",
          labelDari: "نام پدر",
          meaning: "Patronymic — primary identity key with name",
          type: "text",
          required: true,
          example: "Mohammad",
        },
        {
          name: "property_id",
          label: "Property",
          labelDari: "جایداد",
          meaning: "Reference → Property Record (ENT-PROP-020)",
          type: "reference",
          required: true,
          example: "PROP-KBL-0042",
          rules: "One active lessee per property at a time",
        },
        {
          name: "start_date",
          label: "Lease Start Date",
          labelDari: "تاریخ شروع اجاره",
          meaning: "Contract start — Hijri",
          type: "hijri_date",
          required: true,
          example: "1404/01/01",
        },
        {
          name: "end_date",
          label: "Lease End Date",
          labelDari: "تاریخ ختم اجاره",
          meaning: "Contract end — Hijri",
          type: "hijri_date",
          required: true,
          example: "1409/12/29",
        },
        {
          name: "monthly_rent",
          label: "Monthly Rent (AFN)",
          labelDari: "اجاره ماهانه (افغانی)",
          meaning: "Agreed monthly rent amount",
          type: "decimal",
          required: true,
          example: "85000",
        },
        {
          name: "contact",
          label: "Contact",
          labelDari: "تماس",
          meaning: "Phone for rent reminders",
          type: "text",
          required: false,
          example: "0700123456",
        },
        {
          name: "winning_bid_id",
          label: "Winning Bid",
          labelDari: "پیشنهاد برنده",
          meaning: "Reference → Property Lease Bid (ENT-PROC-020) if lease came from bid process",
          type: "reference",
          required: false,
          example: "BID-0042/1405",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | ended | suspended | pending",
          type: "enum",
          required: true,
          example: "active",
        },
        {
          name: "attachment",
          label: "Lease Contract",
          labelDari: "قرارداد اجاره",
          meaning: "Signed lease document — optional but recommended",
          type: "file",
          required: false,
          example: "lease_contract.pdf",
          rules: "PDF, JPG, PNG; max 15 MB",
        },
      ],
    },
    {
      id: "ENT-PROC-023",
      name: "Rent Payment",
      description:
        "Rent received from a lessee. Supports monthly, 4-month, quarterly, yearly, or custom payment periods.",
      fields: [
        {
          name: "payment_id",
          label: "Payment ID",
          labelDari: "شناسه پرداخت",
          meaning: "Auto-generated receipt number",
          type: "text",
          required: true,
          example: "RP-0156/1405",
        },
        {
          name: "property_id",
          label: "Property",
          labelDari: "جایداد",
          meaning: "Reference → ENT-PROP-020",
          type: "reference",
          required: true,
          example: "PROP-KBL-0042",
        },
        {
          name: "lessee_id",
          label: "Lessee",
          labelDari: "مستاجر",
          meaning: "Reference → Lessee (ENT-PROC-021) — active lessee only",
          type: "reference",
          required: true,
          example: "LES-0018/1405 — Abdul Karim",
          rules: "Dropdown filtered to status=active only; auto-selected when property has one active lessee",
        },
        {
          name: "payment_period_type",
          label: "Payment Period Type",
          labelDari: "نوع دوره پرداخت",
          meaning: "monthly | four_months | quarterly | yearly | custom",
          type: "enum",
          required: true,
          example: "monthly",
          rules: "monthly = 1 month; four_months = 4 months; quarterly = 3 months; yearly = 12 months; custom = user sets period_end",
        },
        {
          name: "period_start",
          label: "Period Start",
          labelDari: "شروع دوره",
          meaning: "First day this payment covers — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/03/01",
        },
        {
          name: "period_end",
          label: "Period End",
          labelDari: "ختم دوره",
          meaning: "Last day this payment covers — Hijri; auto-calculated except for custom",
          type: "hijri_date",
          required: true,
          example: "1405/03/29",
        },
        {
          name: "amount",
          label: "Amount (AFN)",
          labelDari: "مبلغ (افغانی)",
          meaning: "Total rent paid for this period",
          type: "decimal",
          required: true,
          example: "85000",
          rules: "For monthly = monthly_rent; for yearly = monthly_rent × 12 (editable)",
        },
        {
          name: "payment_date",
          label: "Payment Date",
          labelDari: "تاریخ پرداخت",
          meaning: "When rent was received — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/03/05",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "pending | paid | partial | overdue | waived",
          type: "enum",
          required: true,
          example: "paid",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Payment notes — partial payment reason, etc.",
          type: "longtext",
          required: false,
          example: "Paid in cash at HQ",
        },
        {
          name: "attachment",
          label: "Receipt / Attachment",
          labelDari: "رسید / ضمیمه",
          meaning: "Optional payment receipt scan",
          type: "file",
          required: false,
          example: "rent_receipt.pdf",
          rules: "PDF, JPG, PNG; max 10 MB",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-PROC-020",
      name: "Bid and assign lease",
      trigger: "ENCC property available for rent (usage_status = not_in_use)",
      startActor: "Procurement Clerk",
      endState: "Active lessee on property; property usage_status = rented_out",
      flowDiagram:
        "Open property → record bids → accept winning bid → create lessee → upload contract → activate → sync Properties",
      steps: [
        {
          step: 1,
          actor: "Procurement Clerk",
          action: "Select property from Properties register",
          input: "property_id (not_in_use)",
          output: "Property account opened for bidding",
        },
        {
          step: 2,
          actor: "Procurement Clerk",
          action: "Record bids",
          input: "person_name, bid_amount, description, contact, optional attachment",
          output: "ENT-PROC-020 rows with status=pending",
        },
        {
          step: 3,
          actor: "Procurement Manager",
          action: "Accept winning bid",
          input: "Select bid; set status=accepted; reject others",
          output: "Winning bid marked accepted",
        },
        {
          step: 4,
          actor: "Procurement Clerk",
          action: "Create lessee from winning bid",
          input: "name, father_name, property_id, start_date, end_date, monthly_rent, winning_bid_id",
          output: "ENT-PROC-021 with status=active",
        },
        {
          step: 5,
          actor: "System",
          action: "Update property usage_status",
          input: "property_id",
          output: "ENT-PROP-020 usage_status = rented_out",
        },
      ],
    },
    {
      id: "WF-PROC-021",
      name: "Record rent payment",
      trigger: "Lessee pays rent for a period",
      startActor: "Procurement Clerk",
      endState: "Payment recorded with receipt",
      flowDiagram: "Select property → active lessee auto-filled → period type → amount and date → optional receipt → status=paid",
      steps: [
        {
          step: 1,
          actor: "Procurement Clerk",
          action: "Select property — active lessee auto-selected",
          input: "property_id",
          output: "lessee_id set to active lessee for that property; shows monthly_rent and unpaid periods",
        },
        {
          step: 2,
          actor: "Procurement Clerk",
          action: "Choose payment period type",
          input: "monthly | four_months | quarterly | yearly | custom",
          output: "period_start and period_end auto-filled (custom: manual)",
        },
        {
          step: 3,
          actor: "Procurement Clerk",
          action: "Record payment",
          input: "amount, payment_date, status, optional attachment",
          output: "ENT-PROC-023 saved",
        },
      ],
    },
    {
      id: "WF-PROC-022",
      name: "Replace lessee",
      trigger: "Tenant changes on same property mid-contract or at renewal",
      startActor: "Procurement Clerk",
      endState: "New lessee active; previous lessee ended; history on lessee rows",
      flowDiagram: "Set old lessee status=ended → create new lessee status=active on same property",
      steps: [
        {
          step: 1,
          actor: "Procurement Clerk",
          action: "Set current lessee status to ended",
          input: "lessee_id — status=ended",
          output: "Previous lessee closed; property may stay rented_out",
        },
        {
          step: 2,
          actor: "Procurement Clerk",
          action: "Create new lessee with status=active",
          input: "name, father_name, property_id, start_date, end_date, monthly_rent, optional attachment",
          output: "New ENT-PROC-021 active — only one active per property",
        },
      ],
    },
    {
      id: "WF-PROC-023",
      name: "End lease",
      trigger: "Contract expires or terminated early",
      startActor: "Procurement Clerk",
      endState: "Lessee ended; property usage_status = not_in_use",
      steps: [
        {
          step: 1,
          actor: "Procurement Clerk",
          action: "Set lessee status=ended",
          input: "lessee_id, end_date",
          output: "Lease closed",
        },
        {
          step: 2,
          actor: "System",
          action: "Revert property usage_status",
          input: "property_id",
          output: "usage_status = not_in_use (unless Properties clerk sets in_use)",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-PROC-020",
      rule: "Only one active lessee per property at a time",
      trigger: "Activate lessee",
      response: "Block if another lessee has status=active on same property_id",
      severity: "Critical",
    },
    {
      id: "BR-PROC-021",
      rule: "Activating a lease sets property usage_status to rented_out in Properties module",
      trigger: "Lessee status → active",
      response: "Sync ENT-PROP-020 usage_status",
      severity: "High",
    },
    {
      id: "BR-PROC-022",
      rule: "Ending a lease reverts property usage_status to not_in_use by default",
      trigger: "Lessee status → ended",
      response: "Sync ENT-PROP-020; Properties may override to in_use",
      severity: "High",
    },
    {
      id: "BR-PROC-023",
      rule: "Bid amount and lessee monthly_rent stored separately — winning bid amount copied to lessee on create but editable",
      trigger: "Create lessee from bid",
      response: "Copy bid_amount to monthly_rent; allow override",
      severity: "Medium",
    },
    {
      id: "BR-PROC-024",
      rule: "Rent payment period must not overlap an existing paid period for same lessee",
      trigger: "Save rent payment",
      response: "Block overlapping period_start/period_end with status=paid",
      severity: "Critical",
    },
    {
      id: "BR-PROC-025",
      rule: "Rent payment lessee_id must reference a lessee with status=active",
      trigger: "Save rent payment",
      response: "Block if lessee is ended, suspended, or pending",
      severity: "Critical",
    },
    {
      id: "BR-PROC-026",
      rule: "Replacing a tenant: end current lessee first, then create new active lessee — no separate change record",
      trigger: "Create new lessee on property with existing active lessee",
      response: "Block until current active lessee is set to ended",
      severity: "Critical",
    },
  ],
  validationRules: [
    {
      field: "property_id",
      rule: "Required — property account header from Properties register",
      uiBehavior: "Searchable dropdown; show usage_status badge",
    },
    {
      field: "bid",
      rule: "person_name and bid_amount required; attachment optional",
      uiBehavior: "Inline table on property lease page",
    },
    {
      field: "lessee",
      rule: "name, father_name, property_id, start_date, end_date, monthly_rent required",
      uiBehavior: "Form linked to property; show active lease summary on property view",
    },
    {
      field: "lessee_id",
      rule: "Active lessee only — status=active",
      uiBehavior: "Dropdown shows active lessees only; after property_id selected, auto-fill the one active lessee for that property",
    },
    {
      field: "payment_period_type",
      rule: "monthly | four_months | quarterly | yearly | custom",
      uiBehavior: "Select type → auto-calculate period_end and suggested amount from monthly_rent",
    },
    {
      field: "rent payment attachment",
      rule: "Optional; PDF, JPG, PNG; max 10 MB",
      uiBehavior: "Receipt upload on payment form",
    },
  ],
  integrations: [
    {
      id: "INT-PROC-020",
      direction: "in",
      module: "Properties — Property Record (ENT-PROP-020)",
      data: "property_id, property_code, property_name, usage_status",
      when: "Bid, lessee, or payment create",
      note: "Property is read-only account header; usage_status synced both ways",
    },
    {
      id: "INT-PROC-021",
      direction: "out",
      module: "Mali — Finance (future)",
      data: "payment_id, amount, payment_date, property_id",
      when: "Rent payment status = paid",
      note: "Future GL posting for rent income",
    },
  ],
  crossModuleNotes: [
    "Property registration is only in Properties module (one task: Register Property).",
    "This section owns all bids, lessees, and rent payments. Tenant change = end old lessee + new active lessee.",
    "usage_status on property: not_in_use → available; rented_out → active lease here.",
  ],
  reports: [
    {
      id: "RPT-PROC-020",
      name: "Lease contracts due",
      purpose: "Active leases where end_date has passed — need renewal or closure",
      filters: "end_date ≤ today, lessee status=active",
      columns: "property_code, property_name, lessee name, end_date, days_overdue, monthly_rent",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-021",
      name: "Leases near due",
      purpose: "Contracts expiring within 30 / 60 / 90 days",
      filters: "end_date range, province, property_type",
      columns: "property_code, lessee name, end_date, days_remaining, monthly_rent, contact",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-022",
      name: "Unpaid rent — who needs to pay",
      purpose: "Active lessees with missing or overdue payment for current period",
      filters: "lessee status=active, period, province",
      columns: "property_code, lessee name, contact, monthly_rent, last_paid_period, amount_due, days_overdue",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-023",
      name: "Monthly rent collection",
      purpose: "Rent collected in a given month — paid vs pending vs overdue",
      filters: "payment_date month, status, province",
      columns: "property_code, lessee name, payment_period_type, amount, payment_date, status",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-024",
      name: "Rent by payment type",
      purpose: "Breakdown of payments by monthly vs 4-month vs quarterly vs yearly vs custom",
      filters: "date range, payment_period_type",
      columns: "payment_period_type, count, total_amount, avg_amount",
      export: "Excel",
    },
    {
      id: "RPT-PROC-025",
      name: "Active leases by property",
      purpose: "All rented_out properties with current lessee and contract dates",
      filters: "province, property_type_id, branch_id",
      columns: "property_code, property_name, lessee name, start_date, end_date, monthly_rent, total_paid_ytd",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-026",
      name: "Open bids by property",
      purpose: "Pending bids awaiting decision",
      filters: "bid status=pending, property_id",
      columns: "property_code, person_name, bid_amount, contact, description, bid date",
      export: "Excel",
    },
    {
      id: "RPT-PROC-027",
      name: "Lessee history by property",
      purpose: "All lessees (active and ended) for a property — tenant replacement audit",
      filters: "property_id, lessee status",
      columns: "property_code, lessee name, father_name, start_date, end_date, status, monthly_rent",
      export: "Excel, PDF",
    },
  ],
  deliverableChecklist: [
    { item: "Property lease bids defined", done: true },
    { item: "Lessee table with end + new active replacement flow", done: true },
    { item: "Rent payment with multiple period types", done: true },
    { item: "Due / near-due / unpaid reports", done: true },
    { item: "Integration with Properties usage_status", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
