import type { SectionDefinition } from "@/types/requirements";

export const smallProcurementSection: SectionDefinition = {
  id: "small-procurement",
  name: "Small Procurement",
  nameDari: "تدارکات کوچک",
  enableReview: true,
  description:
    "Routine purchases and procurements under 5,000,000 AFN — stationery, electrical supplies, services, and similar. Simpler header than major Projects; same optional line-item grid (product, qty, unit, price). Total of all lines auto-calculated. Contract type from General Tables (ENT-OPR-G011).",
  status: "draft",
  currentTool: "Paper procurement slips and akam registers",
  summary: [
    "Threshold: total purchase < 5,000,000 AFN — at or above use Projects task",
    "Header: mali_year, number (procurement or akam number), type, date, need_section, optional seller, file, description",
    "Line items: product from Items Product master (ENT-ITM-015), qty, unit (auto from product), price, optional description",
    "Reports: daily, weekly, monthly, yearly, mali_year totals; which item how much; printable list",
  ],
  relatedSections: ["general-tables", "projects", "items-product-ledger"],
  roles: [
    {
      role: "Procurement Clerk",
      location: "HQ — تدارکات",
      mainActions: "Record small purchases, line items, upload receipts",
      approval: false,
      readOnly: false,
    },
    {
      role: "Procurement Manager",
      location: "HQ — تدارکات",
      mainActions: "Review totals, run period reports",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View records and period purchase reports",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-PROC-040",
      name: "Small Procurement Record",
      description:
        "Purchase under 5M AFN — procurement number or akam number, requesting section, optional seller, and line items.",
      fields: [
        {
          name: "record_number",
          label: "Procurement / Akam Number",
          labelDari: "شماره تدارکات / اکام",
          meaning: "Official procurement number or akam reference — auto or manual",
          type: "text",
          required: true,
          example: "SP-0156/1405",
          rules: "Auto-generated if blank; unique per mali_year",
        },
        {
          name: "mali_year",
          label: "Mali Year",
          labelDari: "سال مالی",
          meaning: "Fiscal year — select current ± 5",
          type: "enum",
          required: true,
          example: "1405",
        },
        {
          name: "date",
          label: "Date",
          labelDari: "تاریخ",
          meaning: "Purchase or procurement date — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/03/15",
        },
        {
          name: "contract_type_id",
          label: "Type",
          labelDari: "نوع",
          meaning: "Reference → Procurement Contract Type (ENT-OPR-G011) — stationery, electrical, services, etc.",
          type: "reference",
          required: true,
          example: "Stationery / قرطاسیه",
          rules: "Same dynamic type table as Projects — admin adds types in General Tables",
        },
        {
          name: "need_section",
          label: "Need Section",
          labelDari: "بخش نیازمند",
          meaning: "Who needs this — department, CEO office, ministry, site, or named person (free text)",
          type: "text",
          required: true,
          example: "CEO Office / دفتر رئیس",
          rules: "e.g. Commercial Directorate, Ministry of Mines, Branch Kabul, Person: Ahmad",
        },
        {
          name: "seller_name",
          label: "Seller Name",
          labelDari: "نام فروشنده",
          meaning: "Vendor or shop name — optional",
          type: "text",
          required: false,
          example: "Kabul Office Supplies",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Optional purchase notes",
          type: "longtext",
          required: false,
          example: "Monthly stationery order for HQ",
        },
        {
          name: "file",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Invoice, receipt, or akam scan — optional",
          type: "file",
          required: false,
          example: "invoice_scan.pdf",
          rules: "PDF, JPG, PNG; max 15 MB",
        },
        {
          name: "grand_total",
          label: "Grand Total",
          labelDari: "مجموع کل",
          meaning: "Sum of all line item totals — auto-calculated read-only",
          type: "decimal",
          required: true,
          example: "125000",
          rules: "Must be < 5,000,000 AFN; auto-sum of line items",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | recorded | verified | cancelled",
          type: "enum",
          required: true,
          example: "recorded",
        },
      ],
    },
    {
      id: "ENT-PROC-041",
      name: "Small Procurement Line Item",
      description:
        "Products on a small procurement — product selected from Items Product master for easy lookup and stock tracking.",
      fields: [
        {
          name: "procurement_id",
          label: "Procurement Record",
          labelDari: "سند تدارکات",
          meaning: "Parent record — reference → ENT-PROC-040",
          type: "reference",
          required: true,
          example: "SP-0156/1405",
        },
        {
          name: "line_id",
          label: "Line ID",
          labelDari: "شناسه ردیف",
          meaning: "Auto-generated row id",
          type: "text",
          required: true,
          example: "SL-0044",
        },
        {
          name: "product_id",
          label: "Product",
          labelDari: "جنس",
          meaning: "Reference → Product master (ENT-ITM-015) — searchable dropdown; tracks what ENCC buys and holds",
          type: "reference",
          required: true,
          example: "PRD-0042 — A4 Paper Ream",
          rules: "Active products only; unit auto-fills from product on select",
        },
        {
          name: "qty",
          label: "Quantity",
          labelDari: "مقدار",
          meaning: "Amount purchased",
          type: "decimal",
          required: true,
          example: "50",
        },
        {
          name: "unit",
          label: "Unit",
          labelDari: "واحد",
          meaning: "Copied from product master on select — editable if purchase unit differs",
          type: "text",
          required: true,
          example: "ream",
          rules: "Auto-fill from product.unit; user may override",
        },
        {
          name: "price",
          label: "Unit Price",
          labelDari: "قیمت واحد",
          meaning: "Price per unit in AFN",
          type: "decimal",
          required: true,
          example: "350",
        },
        {
          name: "line_total",
          label: "Line Total",
          labelDari: "مجموع ردیف",
          meaning: "qty × price — auto-calculated",
          type: "decimal",
          required: true,
          example: "17500",
          rules: "Read-only; system calculates",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Optional line notes — batch, brand, delivery detail, etc.",
          type: "longtext",
          required: false,
          example: "Blue rim reams — delivered to CEO office",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-PROC-040",
      name: "Record small procurement",
      trigger: "Purchase under 5M AFN completed",
      startActor: "Procurement Clerk",
      endState: "Recorded with line items and auto total",
      flowDiagram:
        "Create header → add line items → grand_total auto-sums → optional file → save",
      steps: [
        {
          step: 1,
          actor: "Procurement Clerk",
          action: "Create procurement header",
          input: "mali_year, date, contract_type_id, need_section, optional seller_name",
          output: "Record number assigned",
        },
        {
          step: 2,
          actor: "Procurement Clerk",
          action: "Add line items",
          input: "product_id, qty, unit, price, optional description",
          output: "Line totals and grand_total auto-calculated",
        },
        {
          step: 3,
          actor: "Procurement Clerk",
          action: "Validate total and attach file",
          input: "grand_total < 5M; optional file and description",
          output: "status: recorded",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-PROC-040",
      rule: "grand_total must be < 5,000,000 AFN — at or above use Projects task",
      trigger: "Save procurement",
      response: "Block and redirect to projects if ≥ 5M",
      severity: "Critical",
    },
    {
      id: "BR-PROC-041",
      rule: "Line item line_total = qty × price; grand_total = sum of all line totals — auto-calculated",
      trigger: "Add or edit line item",
      response: "Recalculate immediately; grand_total read-only on header",
      severity: "Critical",
    },
    {
      id: "BR-PROC-042",
      rule: "At least one line item required before save",
      trigger: "Save procurement",
      response: "Block if no line items",
      severity: "High",
    },
    {
      id: "BR-PROC-043",
      rule: "contract_type_id must reference active type from ENT-OPR-G011",
      trigger: "Select type",
      response: "Filter to is_active=true",
      severity: "Medium",
    },
    {
      id: "BR-PROC-044",
      rule: "product_id must reference active product from Items Product master (ENT-ITM-015)",
      trigger: "Add line item",
      response: "Filter dropdown to status=active; auto-fill unit from product",
      severity: "High",
    },
  ],
  validationRules: [
    {
      field: "mali_year",
      rule: "Required — current Solar Hijri year ± 5",
      uiBehavior: "Year dropdown",
    },
    {
      field: "need_section",
      rule: "Required free text — department, ministry, or person",
      uiBehavior: "Text field with examples in placeholder",
    },
    {
      field: "product_id",
      rule: "Required — search by product name or code",
      uiBehavior: "Searchable select from ENT-ITM-015; unit auto-fills; optional description per line",
    },
    {
      field: "line items",
      rule: "At least one row; line_total auto-calculated",
      uiBehavior: "Inline grid; grand_total shown in header footer",
    },
    {
      field: "grand_total",
      rule: "Read-only; must be < 5,000,000 AFN",
      uiBehavior: "Red highlight if approaching 5M threshold",
    },
  ],
  integrations: [
    {
      id: "INT-PROC-040",
      direction: "in",
      module: "General Tables — Procurement Contract Type (ENT-OPR-G011)",
      data: "contract_type_id, name, is_active",
      when: "Small procurement create/edit",
    },
    {
      id: "INT-PROC-041",
      direction: "in",
      module: "Items — Product master (ENT-ITM-015)",
      data: "product_id, name, code, unit, status",
      when: "Line item product select — purchase history rolls up by product for stock tracking",
      note: "Register new products in Items ledger if not in catalog",
    },
  ],
  crossModuleNotes: [
    "Same contract type table (ENT-OPR-G011) as major Projects — stationery, electrical, services, construction, etc.",
    "Line items select from Items Product master — not free-text product names.",
    "Optional description on each line for purchase-specific notes.",
  ],
  reports: [
    {
      id: "RPT-PROC-040",
      name: "Small procurement list",
      purpose: "Printable register with search and filters",
      filters: "mali_year, contract_type_id, need_section, Hijri date range, seller_name, free-text search",
      columns: "record_number, date, type, need_section, seller_name, grand_total, status",
      export: "Excel, PDF — printable list",
    },
    {
      id: "RPT-PROC-041",
      name: "Purchases by mali year",
      purpose: "Total spent and count per fiscal year",
      filters: "mali_year",
      columns: "mali_year, record_count, grand_total_sum",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-042",
      name: "Daily purchases",
      purpose: "What was bought today — total and line detail",
      filters: "date = today, mali_year",
      columns: "record_number, need_section, product (name/code), qty, unit, line_total, grand_total",
      export: "Excel, PDF — printable",
    },
    {
      id: "RPT-PROC-043",
      name: "Weekly purchases",
      purpose: "Purchases in current or selected week",
      filters: "week, mali_year",
      columns: "date, record_number, type, need_section, grand_total",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-044",
      name: "Monthly purchases",
      purpose: "Total bought per Hijri month",
      filters: "month, mali_year",
      columns: "month, record_count, grand_total_sum, top_products",
      export: "Excel, PDF — printable",
    },
    {
      id: "RPT-PROC-045",
      name: "Yearly purchases",
      purpose: "Annual procurement summary",
      filters: "mali_year or solar year",
      columns: "year, record_count, grand_total_sum, by_type breakdown",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-046",
      name: "Purchases by product",
      purpose: "Which item bought how much — qty and total spend",
      filters: "product_id, mali_year, date range",
      columns: "product code, product name, total_qty, unit, total_spent, purchase_count",
      export: "Excel, PDF — printable",
    },
    {
      id: "RPT-PROC-047",
      name: "Purchases by contract type",
      purpose: "Spend and item count per type — stationery, electrical, etc.",
      filters: "mali_year, date range, contract_type_id",
      columns: "contract_type, record_count, total_line_items, total_price",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROC-048",
      name: "Purchases by need section",
      purpose: "Which department or person requested how much",
      filters: "need_section, mali_year, date range",
      columns: "need_section, record_count, grand_total_sum",
      export: "Excel, PDF",
    },
  ],
  deliverableChecklist: [
    { item: "Small procurement header defined", done: true },
    { item: "Line items with auto grand total", done: true },
    { item: "5M AFN ceiling rule documented", done: true },
    { item: "Daily/weekly/monthly/yearly reports", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
