import type { SectionDefinition } from "@/types/requirements";
import { purchaseRequestCoreFields } from "../shared/purchase-request-fields";

export const createPurchaseRequestSection: SectionDefinition = {
  id: "operations",
  name: "Creating Sales",
  nameDari: "ایجاد فروش / درخواست خرید",
  enableReview: true,
  description:
    "First department in the purchase workflow. Creates the initial request form — customer, product, mine, quantity, prices. Only Operations can create new customers (+ button). Boss approval happens here before handoff to Mali.",
  status: "draft",
  currentTool: "Paper request forms, physical customer register",
  summary: [
    "Create purchase request — select what customer is buying (category, type, mine, quantity)",
    "Only department that can create customers (+ button) and view customer purchase history",
    "Editable price snapshots copied from General Tables — not live-linked",
    "Submit to boss (default Commercial) for approval; prices editable at approval",
    "After boss approval → routes to Mali department",
  ],
  followedBy: [
    { moduleId: "mali", sectionId: "mali", label: "Print Bank Receipts" },
  ],
  relatedSections: ["general-tables", "mali", "execution-office"],
  roles: [
    {
      role: "Operations Clerk",
      location: "HQ — عملیات",
      mainActions: "Create requests, add customers, submit for boss approval, view customer history",
      approval: false,
      readOnly: false,
    },
    {
      role: "Selected Boss",
      location: "HQ",
      mainActions: "Approve or reject request; confirm or adjust product and weighing prices",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View requests and customer history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-OPR-015",
      name: "Purchase Request",
      description:
        "Main transaction — created and owned by Operations through boss approval stage. Shared record continues through Mali, Control, and Sales.",
      fields: [
        ...purchaseRequestCoreFields,
        {
          name: "approved_by",
          label: "Approved By (Boss)",
          labelDari: "تأیید شده توسط",
          meaning: "Boss who approved the request",
          type: "reference",
          required: "conditional",
          example: "Commercial Manager",
        },
        {
          name: "approved_at",
          label: "Boss Approval Date",
          labelDari: "تاریخ تأیید مدیر",
          meaning: "Timestamp when boss approved",
          type: "datetime",
          required: "conditional",
          example: "1405/02/19 10:30",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-OPR-020",
      name: "Create purchase request and boss approval",
      trigger: "Customer arrives to buy coal, wood, or other product",
      startActor: "Operations Clerk",
      endState: "Boss approved — routed to Mali (pending_mali)",
      flowDiagram: "Create form → select/add customer → set prices → submit to boss → approve/reject",
      steps: [
        {
          step: 1,
          actor: "Operations Clerk",
          action: "Create purchase request — search customer or click + to add new",
          input: "Customer, category, type, mine, quantity",
          output: "Draft with request number, date; prices copied as editable snapshots",
        },
        {
          step: 2,
          actor: "Operations Clerk",
          action: "Adjust unit_price and weighing_unit_price if needed; select boss (default Commercial)",
          input: "Editable price fields",
          output: "Complete draft ready for submission",
        },
        {
          step: 3,
          actor: "Operations Clerk",
          action: "Submit for boss approval",
          input: "Complete draft",
          output: "status: pending_boss_approval",
          decision: true,
        },
        {
          step: 4,
          actor: "Assigned Boss",
          action: "Review and approve or reject; finalize prices",
          input: "Request details",
          output: "approved_by, approved_at — status: pending_mali — or rejected",
          decision: true,
          exception: "Rejection → Operations revises and resubmits",
        },
      ],
    },
  ],
  statusLifecycles: [
    {
      entity: "Purchase Request",
      from: "draft",
      action: "submit to boss",
      to: "pending_boss_approval",
      actor: "Operations Clerk",
    },
    {
      entity: "Purchase Request",
      from: "pending_boss_approval",
      action: "approve",
      to: "pending_mali",
      actor: "Assigned boss",
      notes: "Handoff to Mali department",
    },
    {
      entity: "Purchase Request",
      from: "pending_boss_approval",
      action: "reject",
      to: "boss_rejected",
      actor: "Assigned boss",
    },
  ],
  businessRules: [
    {
      id: "BR-OPR-030",
      rule: "Only Operations can create new customers (+ button on request form)",
      trigger: "Add customer",
      response: "Block Sales and other departments from customer create",
      severity: "Critical",
    },
    {
      id: "BR-OPR-031",
      rule: "Customer minimum: first name + father name to add new",
      trigger: "Create customer",
      response: "Save to General Tables / Customer",
      severity: "High",
    },
    {
      id: "BR-OPR-032",
      rule: "unit_price and weighing_unit_price are editable snapshots on the request",
      trigger: "Type selection",
      response: "Copy from master; allow edit before and at boss approval",
      severity: "Critical",
    },
    {
      id: "BR-OPR-033",
      rule: "Assigned boss defaults to Commercial",
      trigger: "Create",
      response: "Pre-select Commercial",
      severity: "High",
    },
    {
      id: "BR-OPR-034",
      rule: "Only assigned boss can approve",
      trigger: "Boss approve",
      response: "Block unauthorized",
      severity: "Critical",
    },
  ],
  permissionsMatrix: [
    { action: "Create / edit request", archiveClerk: "C", executive: "—", deptStaff: "—", auditor: "—" },
    { action: "Create customer (+)", archiveClerk: "C", executive: "—", deptStaff: "—", auditor: "—" },
    { action: "Submit to boss", archiveClerk: "C", executive: "—", deptStaff: "—", auditor: "—" },
    { action: "Boss approve", archiveClerk: "—", executive: "A", deptStaff: "—", auditor: "—" },
    { action: "View customer history", archiveClerk: "R", executive: "R", deptStaff: "—", auditor: "R" },
    { action: "Export operations reports", archiveClerk: "E", executive: "E", deptStaff: "—", auditor: "R" },
  ],
  reports: [
    {
      id: "RPT-OPR-020",
      name: "Customer Purchase History",
      purpose: "All purchases by a customer — who bought what, when, from which mine",
      filters: "Customer, Hijri date range, product category, mine, status",
      columns: "request no., date, category, type, mine, qty, grand total, status",
      export: "PDF, Excel",
    },
    {
      id: "RPT-OPR-021",
      name: "Customer Register",
      purpose: "All registered customers with purchase count and last order date",
      filters: "Active only, search by name or code",
      columns: "customer code, name, phone, total orders, last order date",
      export: "PDF, Excel",
    },
    {
      id: "RPT-OPR-022",
      name: "Operations Request Register",
      purpose: "All requests created by Operations — by date and status",
      filters: "Hijri date range, status, boss, mine, customer",
      columns: "request no., date, customer, product, mine, qty, grand total, status",
      export: "PDF, Excel",
    },
    {
      id: "RPT-OPR-023",
      name: "Pending Boss Approvals",
      purpose: "Requests awaiting boss action",
      filters: "Boss, age in days",
      columns: "request no., customer, product, grand total, submitted date",
      export: "PDF",
    },
  ],
  validationRules: [
    {
      field: "customer_id",
      rule: "Required; search by name, code, phone",
      uiBehavior: "Autocomplete + plus (+) button → add-customer modal (Operations only)",
    },
    {
      field: "unit_price / weighing_unit_price",
      rule: "Editable after copy from master",
      uiBehavior: "Number inputs on create and boss approval screen",
    },
  ],
  crossModuleNotes: [
    "Customer master data in General Tables — Operations is the only department with create permission.",
    "Sales department can read customers but cannot add new ones.",
  ],
  deliverableChecklist: [
    { item: "Operations workflow documented", done: true },
    { item: "Customer create permission defined", done: true },
    { item: "Customer history reports listed", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
