import type { SectionDefinition } from "@/types/requirements";

export const executionOfficeSection: SectionDefinition = {
  id: "execution-office",
  name: "Execution Office",
  nameDari: "امریت اجرایه",
  enableReview: true,
  description:
    "Sub-office of ریایست اجرایه. Registers customer purchase requests for coal, wood, and other products. Workflow: create → boss approval → Mali (مالی) bank receipts → control check → bank payment → verify → sales form. All master data lives in General Tables.",
  status: "draft",
  currentTool: "Paper forms, manual bank receipts, physical register",
  summary: [
    "Purchase request with editable price snapshots copied from Product Type and Weighing Rate",
    "Customer: searchable dropdown + plus button to add new (see General Tables)",
    "Boss selection defaults to Commercial — options: Commercial, Mali, Operational, General",
    "Flow: create → boss approval → Mali receipts (product + weighing) → control → payment → verify → sales",
    "Uploaded bank receipts stored in shared Uploaded Bank Receipt table (General Tables)",
  ],
  relatedSections: ["general-tables", "archive"],
  roles: [
    {
      role: "Execution Office Clerk",
      location: "HQ — امریت اجرایه",
      mainActions:
        "Create purchase requests, search/add customers, submit for boss approval",
      approval: false,
      readOnly: false,
    },
    {
      role: "Selected Boss",
      location: "HQ",
      mainActions: "Approve or reject; confirm or adjust product and weighing prices",
      approval: true,
      readOnly: false,
    },
    {
      role: "Mali Clerk",
      location: "HQ — مالی",
      mainActions:
        "Generate and print bank payment receipts (product + weighing); upload and verify bank receipts after payment",
      approval: true,
      readOnly: false,
    },
    {
      role: "Control Officer",
      location: "HQ — کنترول",
      mainActions: "Verify request and Mali receipts before customer pays at bank",
      approval: true,
      readOnly: false,
    },
    {
      role: "Sales Clerk",
      location: "HQ — فروشات",
      mainActions: "Issue sales form with unique number; data auto-filled from verified payment",
      approval: false,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View full request trail, receipts, approvals, attachments",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-OPR-015",
      name: "Purchase Request",
      description:
        "Main transaction — customer order for product from a mine. Prices are editable snapshots copied from General Tables at creation.",
      fields: [
        {
          name: "request_number",
          label: "Request Number",
          labelDari: "شماره درخواست",
          meaning: "System-generated unique tracking number",
          type: "text",
          required: true,
          example: "PR-1245/1405",
          rules: "Auto-generated, unique, sequential per year",
        },
        {
          name: "request_date",
          label: "Request Date",
          labelDari: "تاریخ",
          meaning: "Date request registered",
          type: "date",
          required: true,
          example: "1405/02/19",
        },
        {
          name: "customer_id",
          label: "Customer",
          labelDari: "مشتری",
          meaning:
            "Reference → General Tables / Customer. Searchable dropdown; + button to add new customer inline",
          type: "reference",
          required: true,
          example: "CUS-004521 — احمد بن محمد",
          rules: "See General Tables ENT-OPR-G001",
        },
        {
          name: "product_category_id",
          label: "Product Category",
          labelDari: "جنس",
          meaning: "Reference → General Tables / Product Category",
          type: "reference",
          required: true,
          example: "Coal",
        },
        {
          name: "product_type_id",
          label: "Product Type",
          labelDari: "نوع",
          meaning: "Reference → General Tables / Product Type — filters by category",
          type: "reference",
          required: true,
          example: "Grade A Coal",
        },
        {
          name: "mining_site_id",
          label: "Mining Site",
          labelDari: "معدن",
          meaning: "Reference → General Tables / Mining Site",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "quantity",
          label: "Quantity (tons)",
          labelDari: "مقدار (تن)",
          meaning: "Amount of product ordered in tons",
          type: "decimal",
          required: true,
          example: "50",
        },
        {
          name: "unit_price",
          label: "Unit Price (Product)",
          labelDari: "قیمت واحد جنس",
          meaning:
            "Editable copy of product type default price — snapshotted on type selection; editable at create and boss approval. Not live-linked to master price.",
          type: "decimal",
          required: true,
          example: "8500",
          rules: "Copied from Product Type default; stored on request for audit",
        },
        {
          name: "product_total",
          label: "Product Total",
          labelDari: "مجموع جنس",
          meaning: "quantity × unit_price",
          type: "decimal",
          required: true,
          example: "425000",
          rules: "System-calculated",
        },
        {
          name: "weighing_unit_price",
          label: "Weighing Rate (per ton)",
          labelDari: "نرخ ویگن (به ازای تن)",
          meaning:
            "Editable copy of current Weighing Rate — default 10 AFN/ton; snapshotted on create; editable at boss approval",
          type: "decimal",
          required: true,
          example: "10",
          rules: "Copied from General Tables / Weighing Rate",
        },
        {
          name: "weighing_total",
          label: "Weighing Total",
          labelDari: "مجموع ویگن",
          meaning: "quantity × weighing_unit_price",
          type: "decimal",
          required: true,
          example: "500",
          rules: "System-calculated",
        },
        {
          name: "grand_total",
          label: "Grand Total",
          labelDari: "مجموع کل",
          meaning: "product_total + weighing_total",
          type: "decimal",
          required: true,
          example: "425500",
          rules: "System-calculated",
        },
        {
          name: "assigned_boss",
          label: "Assigned Boss",
          labelDari: "مدیر مسئول تأیید",
          meaning: "Boss selected for approval — defaults to Commercial",
          type: "enum",
          required: true,
          example: "Commercial",
          rules: "Commercial (default) | Mali | Operational | General",
        },
        {
          name: "approved_by",
          label: "Approved By (Boss)",
          labelDari: "تأیید شده توسط",
          meaning: "Boss who approved the request",
          type: "reference",
          required: "conditional",
          example: "Commercial Manager",
        },
        {
          name: "approved_at",
          label: "Boss Approval Date",
          labelDari: "تاریخ تأیید مدیر",
          meaning: "Timestamp when boss approved",
          type: "datetime",
          required: "conditional",
          example: "1405/02/19 10:30",
        },
        {
          name: "product_receipt_generated",
          label: "Product Bank Receipt (Generated)",
          labelDari: "رسید بانکی جنس",
          meaning: "Mali-generated PDF for product payment — uses product bank account from General Tables",
          type: "file",
          required: "conditional",
          example: "receipt_product_PR-1245.pdf",
        },
        {
          name: "weighing_receipt_generated",
          label: "Weighing Bank Receipt (Generated)",
          labelDari: "رسید بانکی ویگن",
          meaning: "Mali-generated PDF for weighing fees — uses weighing bank account from General Tables",
          type: "file",
          required: "conditional",
          example: "receipt_weighing_PR-1245.pdf",
        },
        {
          name: "control_checked_by",
          label: "Control Checked By",
          labelDari: "بررسی شده توسط کنترول",
          meaning: "Control officer who verified after Mali receipts printed",
          type: "reference",
          required: "conditional",
          example: "Control Officer — Karim",
        },
        {
          name: "control_checked_at",
          label: "Control Check Date",
          labelDari: "تاریخ بررسی کنترول",
          meaning: "When control verification completed — after Mali receipts, before bank payment",
          type: "datetime",
          required: "conditional",
          example: "1405/02/19 14:00",
        },
        {
          name: "uploaded_receipts",
          label: "Uploaded Bank Receipts",
          labelDari: "رسیدهای بانک آپلود شده",
          meaning:
            "References → General Tables / Uploaded Bank Receipt (one or more per request — product purchase, weighing, etc.)",
          type: "reference",
          required: "conditional",
          example: "BR-987654 (product), BR-987655 (weighing)",
          rules: "See ENT-OPR-G008 — separate table with number, date, Tarafa, file, type, approver",
        },
        {
          name: "payment_verified",
          label: "All Payments Verified",
          labelDari: "پرداخت تأیید شده",
          meaning: "True when all linked uploaded bank receipts have approved_by set",
          type: "boolean",
          required: "conditional",
          example: "true",
        },
        {
          name: "sales_form_number",
          label: "Sales Form Number",
          labelDari: "شماره فورم فروشات",
          meaning: "Unique number on sales department form — auto-generated",
          type: "text",
          required: "conditional",
          example: "SF-789/1405",
          rules: "Auto-generated after all payments verified",
        },
        {
          name: "sales_form_date",
          label: "Sales Form Date",
          labelDari: "تاریخ فورم فروشات",
          meaning: "Date sales form issued",
          type: "date",
          required: "conditional",
          example: "1405/02/20",
        },
        {
          name: "sales_form_file",
          label: "Sales Form (Generated)",
          labelDari: "فورم فروشات",
          meaning: "Generated sales form PDF — layout TBD from ENCC sample",
          type: "file",
          required: "conditional",
          example: "sales_form_SF-789.pdf",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "Current stage in workflow",
          type: "enum",
          required: true,
          example: "pending_boss_approval",
          rules:
            "draft | pending_boss_approval | boss_rejected | pending_mali | pending_control | control_rejected | pending_payment | payment_submitted | payment_verified | sales_issued | complete",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-OPR-010",
      name: "Purchase request — coal / wood / product order",
      trigger: "Customer arrives at Execution Office to buy coal, wood, or other product",
      startActor: "Execution Office Clerk",
      endState: "Complete — sales form issued; request visible in MINS",
      currentTool: "Paper forms, manual bank receipts, physical register",
      flowDiagram:
        "Create → Boss approve (price editable) → Mali bank receipts → Control check → Customer pays → Upload receipts & verify → Sales form → MINS",
      mermaid: `flowchart TD
  A[Create Request] --> B[Submit to Boss]
  B --> C{Boss}
  C -->|Approve| D[Mali: Print Receipts]
  C -->|Reject| A
  D --> E{Control}
  E -->|Approve| F[Customer Pays at Bank]
  E -->|Reject| A
  F --> G[Upload Bank Receipts]
  G --> H[Verify Payment]
  H --> I[Sales: Issue Form]
  I --> J[Complete / MINS]`,
      steps: [
        {
          step: 1,
          actor: "Execution Office Clerk",
          action:
            "Create purchase request — search customer (+ to add new), select category, type, mine, quantity",
          input: "Customer, category, type, mine, quantity, boss (default Commercial)",
          output:
            "Draft with request number, date; unit_price and weighing_unit_price copied as editable snapshots",
        },
        {
          step: 2,
          actor: "Execution Office Clerk",
          action: "Adjust prices if needed; submit for boss approval",
          input: "Complete draft with editable price fields",
          output: "Routed to selected boss — status: pending_boss_approval",
          decision: true,
        },
        {
          step: 3,
          actor: "Assigned Boss",
          action: "Review and approve or reject; confirm or change product and weighing prices",
          input: "Request details with price snapshots",
          output: "approved_by, approved_at logged; prices finalized — or rejected with reason",
          decision: true,
          exception: "Rejection → return to clerk for correction",
        },
        {
          step: 4,
          actor: "Mali Clerk",
          action: "Generate and print two bank receipts — product account and weighing account",
          input: "Boss-approved request, bank accounts from General Tables",
          output: "Product receipt PDF + weighing receipt PDF — status: pending_control",
        },
        {
          step: 5,
          actor: "Control Officer",
          action: "Verify request details and Mali receipts before customer goes to bank",
          input: "Printed receipts + request data",
          output: "control_checked_by, control_checked_at — status: pending_payment",
          decision: true,
          exception: "Return to clerk if incorrect — may require reprint from Mali",
        },
        {
          step: 6,
          actor: "Customer",
          action: "Take receipts to bank and pay (product + weighing amounts)",
          input: "Printed Mali bank receipts",
          output: "Bank receipts with receipt number and Tarafa number",
        },
        {
          step: 7,
          actor: "Mali Clerk",
          action: "Create Uploaded Bank Receipt records — number, date, Tarafa, file, type",
          input: "Bank receipt scans (one per payment: product, weighing)",
          output: "Records in General Tables / Uploaded Bank Receipt linked to request",
        },
        {
          step: 8,
          actor: "Mali Clerk",
          action: "Verify each uploaded receipt with bank; set approved_by and approved_at on each",
          input: "Uploaded receipts, bank confirmation",
          output: "All receipts approved — status: payment_verified",
          decision: true,
        },
        {
          step: 9,
          actor: "Sales Clerk",
          action: "Generate sales form — unique number, date, auto-filled from request and receipts",
          input: "Verified payment, customer, product, amounts, receipt numbers, Tarafa numbers, approvers",
          output: "Sales form PDF — status: sales_issued → complete",
        },
        {
          step: 10,
          actor: "System",
          action: "Publish request to MINS module",
          input: "Completed purchase request",
          output: "Request visible in MINS with mine, product, quantity, customer",
        },
      ],
    },
  ],
  statusLifecycles: [
    {
      entity: "Purchase Request",
      from: "draft",
      action: "submit to boss",
      to: "pending_boss_approval",
      actor: "Execution Office Clerk",
      notes: "Customer, product, mine, quantity, prices, boss selected",
    },
    {
      entity: "Purchase Request",
      from: "pending_boss_approval",
      action: "approve",
      to: "pending_mali",
      actor: "Assigned boss",
      notes: "approved_by, approved_at; product and weighing prices finalized",
    },
    {
      entity: "Purchase Request",
      from: "pending_boss_approval",
      action: "reject",
      to: "boss_rejected",
      actor: "Assigned boss",
      notes: "Reason required; clerk may revise → draft",
    },
    {
      entity: "Purchase Request",
      from: "pending_mali",
      action: "print receipts",
      to: "pending_control",
      actor: "Mali Clerk",
      notes: "Product + weighing PDFs generated",
    },
    {
      entity: "Purchase Request",
      from: "pending_control",
      action: "approve",
      to: "pending_payment",
      actor: "Control Officer",
      notes: "control_checked_by, control_checked_at — customer may go to bank",
    },
    {
      entity: "Purchase Request",
      from: "pending_control",
      action: "reject",
      to: "control_rejected",
      actor: "Control Officer",
      notes: "Return to clerk; may need Mali reprint",
    },
    {
      entity: "Purchase Request",
      from: "pending_payment",
      action: "upload bank receipts",
      to: "payment_submitted",
      actor: "Mali Clerk",
      notes: "Uploaded Bank Receipt records created in General Tables",
    },
    {
      entity: "Purchase Request",
      from: "payment_submitted",
      action: "verify all receipts",
      to: "payment_verified",
      actor: "Mali Clerk",
      notes: "Each uploaded receipt has approved_by and approved_at",
    },
    {
      entity: "Purchase Request",
      from: "payment_verified",
      action: "issue sales form",
      to: "sales_issued",
      actor: "Sales Clerk",
      notes: "sales_form_number auto-generated",
    },
    {
      entity: "Purchase Request",
      from: "sales_issued",
      action: "complete",
      to: "complete",
      actor: "System",
      notes: "Visible in MINS",
    },
  ],
  businessRules: [
    {
      id: "BR-OPR-010",
      rule: "Request number must be unique and auto-generated",
      trigger: "Create",
      response: "Block duplicate",
      severity: "Critical",
    },
    {
      id: "BR-OPR-011",
      rule: "Product type dropdown filters by selected category",
      trigger: "Category change",
      response: "Reload types; copy new default unit_price to request",
      severity: "Critical",
    },
    {
      id: "BR-OPR-012",
      rule: "unit_price and weighing_unit_price are editable snapshots — copied from master at selection, not live-linked",
      trigger: "Type selection / create",
      response: "Copy defaults; allow edit on request and at boss approval",
      severity: "Critical",
    },
    {
      id: "BR-OPR-013",
      rule: "product_total = quantity × unit_price; weighing_total = quantity × weighing_unit_price; grand_total = sum",
      trigger: "Quantity or price change",
      response: "Recalculate automatically",
      severity: "Critical",
    },
    {
      id: "BR-OPR-014",
      rule: "Assigned boss defaults to Commercial; options: Commercial, Mali, Operational, General",
      trigger: "Create",
      response: "Pre-select Commercial; user may change",
      severity: "High",
    },
    {
      id: "BR-OPR-015",
      rule: "Boss approval must record approved_by, approved_at, and finalized prices",
      trigger: "Boss approve",
      response: "Require fields",
      severity: "Critical",
    },
    {
      id: "BR-OPR-016",
      rule: "Mali prints receipts only after boss approval — before control check",
      trigger: "Print receipts",
      response: "Block if boss not approved",
      severity: "Critical",
    },
    {
      id: "BR-OPR-017",
      rule: "Control check happens after Mali receipts printed — before customer pays at bank",
      trigger: "Control approve",
      response: "Block if receipts not generated",
      severity: "Critical",
    },
    {
      id: "BR-OPR-018",
      rule: "Two Mali receipts: product account and weighing account from General Tables / Bank Account",
      trigger: "Generate receipts",
      response: "Use accounts tagged product and weighing",
      severity: "Critical",
    },
    {
      id: "BR-OPR-019",
      rule: "Uploaded bank receipts stored in General Tables — not embedded on purchase request",
      trigger: "Upload payment",
      response: "Create ENT-OPR-G008 records linked to request",
      severity: "Critical",
    },
    {
      id: "BR-OPR-020",
      rule: "Each uploaded receipt requires number, date, Tarafa number, file, and type",
      trigger: "Create receipt record",
      response: "Block if missing",
      severity: "Critical",
    },
    {
      id: "BR-OPR-021",
      rule: "Sales form cannot be issued until all linked uploaded receipts are verified",
      trigger: "Issue sales form",
      response: "Block",
      severity: "Critical",
    },
    {
      id: "BR-OPR-022",
      rule: "Sales form auto-fills from request + uploaded receipt data (numbers, Tarafa, approvers)",
      trigger: "Generate sales form",
      response: "Read-only inherited fields",
      severity: "High",
    },
    {
      id: "BR-OPR-023",
      rule: "Customer search with + button — minimum first name + father name to add new",
      trigger: "Create request",
      response: "Save to General Tables / Customer then link",
      severity: "High",
    },
    {
      id: "BR-OPR-024",
      rule: "Only assigned boss can approve routed request",
      trigger: "Boss approve attempt",
      response: "Block unauthorized",
      severity: "Critical",
      override: true,
      approver: "General",
    },
  ],
  permissionsMatrix: [
    {
      action: "View purchase requests",
      archiveClerk: "R",
      executive: "R",
      deptStaff: "R",
      auditor: "R",
    },
    {
      action: "Create / edit draft request",
      archiveClerk: "C",
      executive: "—",
      deptStaff: "—",
      auditor: "—",
    },
    {
      action: "Boss approve (routed to self)",
      archiveClerk: "—",
      executive: "A",
      deptStaff: "—",
      auditor: "—",
    },
    {
      action: "Mali — print receipts",
      archiveClerk: "—",
      executive: "—",
      deptStaff: "C",
      auditor: "—",
    },
    {
      action: "Control verify",
      archiveClerk: "—",
      executive: "—",
      deptStaff: "A",
      auditor: "—",
    },
    {
      action: "Upload / verify bank receipts",
      archiveClerk: "—",
      executive: "—",
      deptStaff: "U",
      auditor: "—",
    },
    {
      action: "Issue sales form",
      archiveClerk: "—",
      executive: "—",
      deptStaff: "C",
      auditor: "—",
    },
    {
      action: "Export register / reports",
      archiveClerk: "E",
      executive: "E",
      deptStaff: "E",
      auditor: "R",
    },
  ],
  reports: [
    {
      id: "RPT-OPR-010",
      name: "Purchase Request Register",
      purpose: "All orders by date and status",
      filters: "Hijri date range, category, mine, status, boss",
      columns:
        "request no., date, customer, category, type, mine, qty, product total, weighing total, status",
      export: "PDF, Excel",
    },
    {
      id: "RPT-OPR-011",
      name: "Pending Boss Approvals",
      purpose: "Requests awaiting boss action",
      filters: "Boss, age in days",
      columns: "request no., customer, product, grand total, submitted date",
      export: "PDF",
    },
    {
      id: "RPT-OPR-012",
      name: "Pending Control / Payment",
      purpose: "Items awaiting control or payment verification",
      filters: "Stage, mine",
      columns: "request no., customer, Mali status, control status, payment status",
      export: "PDF, Excel",
    },
    {
      id: "RPT-OPR-013",
      name: "Sales Forms Issued",
      purpose: "Daily sales form register",
      filters: "Date range, mine, product type",
      columns: "sales form no., request no., customer, grand total, date",
      export: "PDF, Excel",
    },
  ],
  validationRules: [
    {
      field: "customer_id",
      rule: "Required; search by name, code, or phone",
      uiBehavior: "Autocomplete dropdown + plus (+) button opens add-customer modal",
    },
    {
      field: "unit_price",
      rule: "Copied from Product Type default; editable on request form and boss approval",
      uiBehavior: "Number input — not read-only after copy",
    },
    {
      field: "weighing_unit_price",
      rule: "Copied from Weighing Rate (default 10 AFN/ton); editable on request and boss approval",
      uiBehavior: "Number input",
    },
    {
      field: "assigned_boss",
      rule: "Default Commercial; enum: Commercial, Mali, Operational, General",
      uiBehavior: "Dropdown pre-selected to Commercial",
    },
    {
      field: "uploaded_receipts",
      rule: "One or more Uploaded Bank Receipt records per request",
      uiBehavior: "Link to General Tables form — type = purchase or weighing",
    },
    {
      field: "sales_form_number",
      rule: "Auto-generated; read-only",
      uiBehavior: "Displayed on generated sales form PDF",
    },
  ],
  integrations: [
    {
      id: "INT-OPR-010",
      direction: "in",
      module: "General Tables",
      data: "Customer, Product Category, Product Type, Mining Site, Bank Account, Weighing Rate, Uploaded Bank Receipt",
      when: "On every request field and payment step",
      note: "All master data referenced from general-tables section",
    },
    {
      id: "INT-OPR-011",
      direction: "out",
      module: "MINS — Mines",
      data: "Completed purchase requests",
      when: "On status = complete",
      note: "Mine sites see orders for their site",
    },
    {
      id: "INT-OPR-012",
      direction: "link",
      module: "SCA — Sales, Contracts & Allocations",
      data: "Sales form data",
      when: "On sales form issued",
      note: "When SCA module active",
    },
  ],
  crossModuleNotes: [
    "Master data maintained in General Tables section — not duplicated here.",
    "Permissions: Clerk = archiveClerk column, Boss = executive, Mali/Control/Sales = deptStaff.",
    "Uploaded Bank Receipt table shared with rent and other payment workflows (future sections).",
    "Bank receipt and sales form PDF layouts pending ENCC samples.",
  ],
  nfrs: [
    {
      area: "Security",
      requirement: "Role-based access per workflow stage; audit trail on all price edits",
    },
    {
      area: "Localization",
      requirement: "Dari labels; Hijri dates per module standard",
    },
    {
      area: "Performance",
      requirement: "Customer search under 500ms; request search under 3 seconds for 50,000 records",
    },
    {
      area: "Pricing",
      requirement: "Price snapshots on request preserved even when master prices change later",
    },
  ],
  migration: [
    "Purchase registers digitized — prices stored as snapshots on each historical request.",
    "Sales form layout pending ENCC sample.",
  ],
  edgeCases: [
    {
      id: "EC-OPR-010",
      scenario: "Boss gives special price to one customer.",
      behavior: "Edit unit_price on request before or at approval; snapshot stored on request only.",
      handler: "Assigned boss",
    },
    {
      id: "EC-OPR-011",
      scenario: "Seasonal price change in Product Type master.",
      behavior: "New requests get new default copy; existing requests keep their snapshotted prices.",
      handler: "Master Data Admin",
    },
    {
      id: "EC-OPR-012",
      scenario: "Control rejects after Mali printed receipts.",
      behavior: "Return to clerk; Mali may reprint if amounts changed.",
      handler: "Control Officer",
    },
    {
      id: "EC-OPR-013",
      scenario: "Customer pays product and weighing at bank separately.",
      behavior: "Two Uploaded Bank Receipt records — types purchase and weighing — both must be verified.",
      handler: "Mali Clerk",
    },
    {
      id: "EC-OPR-014",
      scenario: "Duplicate customer name (same first + father name).",
      behavior: "Search shows matches; clerk selects existing or confirms new entry.",
      handler: "Execution Office Clerk",
    },
  ],
  deliverableChecklist: [
    { item: "Process flows documented", done: true },
    { item: "Purchase request entity (workflow-only)", done: true },
    { item: "General Tables section created", done: true },
    { item: "Correct workflow order (Mali before Control)", done: true },
    { item: "Price snapshot model documented", done: true },
    { item: "Bank receipt PDF samples from ENCC", done: false },
    { item: "Sales form PDF sample from ENCC", done: false },
    { item: "Evidence samples attached", done: false },
    { item: "ENCC sign-off", done: false },
  ],
};
