import type { SectionDefinition } from "@/types/requirements";

export const propertyRegisterSection: SectionDefinition = {
  id: "property-register",
  name: "Register Property",
  nameDari: "ثبت جایداد",
  enableReview: true,
  description:
    "Register ENCC-owned property assets — buildings, land, warehouses, offices, and related sites. ENCC is a government corporation and owns most assets; usage_status shows whether ENCC is using the property, it is vacant, or it is rented out to private tenants (lease managed in Procurement). Property type is a dynamic admin table in General Tables.",
  status: "draft",
  currentTool: "Paper property register / scattered files",
  summary: [
    "Single task — register and maintain property master records only",
    "Property type from General Tables (ENT-OPR-G010) — admin adds types dynamically",
    "usage_status: in_use (ENCC using) | not_in_use (vacant) | rented_out (leased to private — see Procurement)",
    "Location: province, district, village, address, optional GPS",
    "Physical and legal details — most optional; documents and images as child tables",
    "No lease dates or rent amounts here — all renting handled in Procurement → Property Lease",
  ],
  relatedSections: ["general-tables", "property-lease"],
  roles: [
    {
      role: "Properties Clerk",
      location: "HQ — جایداد ها",
      mainActions: "Create and edit property records, upload documents and images",
      approval: false,
      readOnly: false,
    },
    {
      role: "Properties Manager",
      location: "HQ — جایداد ها",
      mainActions: "Review property records, approve status changes, view reports",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View property register, documents, and change history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-PROP-020",
      name: "Property Record",
      description:
        "Master record for an ENCC-owned property. Acts as the account header — lessees, bids, and rent payments in Procurement link here via property_id.",
      fields: [
        {
          name: "property_code",
          label: "Property Code",
          labelDari: "کود جایداد",
          meaning: "Auto-generated unique identifier",
          type: "text",
          required: true,
          example: "PROP-KBL-0042",
          rules: "Auto-generated; unique; read-only after create",
        },
        {
          name: "property_name",
          label: "Property Name",
          labelDari: "نام جایداد",
          meaning: "Official or common name of the property",
          type: "text",
          required: true,
          example: "ENCC Kabul Warehouse",
        },
        {
          name: "property_type_id",
          label: "Property Type",
          labelDari: "نوع جایداد",
          meaning: "Reference → Property Type (ENT-OPR-G010) — dynamic admin table",
          type: "reference",
          required: true,
          example: "Warehouse / گدام",
          rules: "Dropdown from active property types in General Tables; admin can add new types",
        },
        {
          name: "usage_status",
          label: "Usage Status",
          labelDari: "وضعیت استفاده",
          meaning: "in_use | not_in_use | rented_out",
          type: "enum",
          required: true,
          example: "in_use",
          rules:
            "in_use = ENCC currently using; not_in_use = vacant / idle; rented_out = leased to private tenant (Procurement manages contract and rent)",
        },
        {
          name: "branch_id",
          label: "Managing Branch",
          labelDari: "شعبه مسئول",
          meaning: "Reference → Branch (ENT-OPR-G009)",
          type: "reference",
          required: false,
          example: "Kabul HQ Branch",
        },
        {
          name: "status",
          label: "Record Status",
          labelDari: "وضعیت ثبت",
          meaning: "active | inactive | under_maintenance | disposed | pending_registration",
          type: "enum",
          required: true,
          example: "active",
        },
        {
          name: "province",
          label: "Province",
          labelDari: "ولایت",
          meaning: "One of 34 Afghan provinces — dropdown",
          type: "enum",
          required: false,
          example: "Kabul",
          rules: "Badakhshan | Badghis | Baghlan | Balkh | Bamyan | Daykundi | Farah | Faryab | Ghazni | Ghor | Helmand | Herat | Jowzjan | Kabul | Kandahar | Kapisa | Khost | Kunar | Kunduz | Laghman | Logar | Nangarhar | Nimroz | Nuristan | Paktia | Paktika | Panjshir | Parwan | Samangan | Sar-e Pol | Takhar | Uruzgan | Wardak | Zabul",
        },
        {
          name: "district",
          label: "District",
          labelDari: "ولسوالی",
          meaning: "District within the province",
          type: "text",
          required: false,
          example: "District 4",
        },
        {
          name: "village_or_neighborhood",
          label: "Village / Neighborhood",
          labelDari: "قریه / محله",
          meaning: "Local area name",
          type: "text",
          required: false,
          example: "Karte Parwan",
        },
        {
          name: "address",
          label: "Full Address",
          labelDari: "آدرس کامل",
          meaning: "Street, block, and detailed address",
          type: "longtext",
          required: false,
          example: "Street 5, Block C, District 4, Kabul",
        },
        {
          name: "landmark",
          label: "Nearby Landmark",
          labelDari: "نشانه نزدیک",
          meaning: "Reference point for locating the property",
          type: "text",
          required: false,
          example: "Near Pul-e Surkh",
        },
        {
          name: "gps_latitude",
          label: "GPS Latitude",
          labelDari: "عرض جغرافیایی",
          meaning: "Optional GPS coordinate",
          type: "decimal",
          required: false,
          example: "34.5553",
        },
        {
          name: "gps_longitude",
          label: "GPS Longitude",
          labelDari: "طول جغرافیایی",
          meaning: "Optional GPS coordinate",
          type: "decimal",
          required: false,
          example: "69.2075",
        },
        {
          name: "land_area_sqm",
          label: "Land Area (sqm)",
          labelDari: "مساحت زمین (متر مربع)",
          meaning: "Total land area in square meters",
          type: "decimal",
          required: false,
          example: "2500",
        },
        {
          name: "built_area_sqm",
          label: "Built Area (sqm)",
          labelDari: "مساحت بنا (متر مربع)",
          meaning: "Total constructed area",
          type: "decimal",
          required: false,
          example: "800",
        },
        {
          name: "number_of_floors",
          label: "Number of Floors",
          labelDari: "تعداد طبقات",
          meaning: "Floor count for buildings",
          type: "text",
          required: false,
          example: "2",
        },
        {
          name: "number_of_rooms",
          label: "Number of Rooms",
          labelDari: "تعداد اتاق",
          meaning: "Room count",
          type: "text",
          required: false,
          example: "12",
        },
        {
          name: "year_built",
          label: "Year Built",
          labelDari: "سال ساخت",
          meaning: "Construction year",
          type: "text",
          required: false,
          example: "1395",
        },
        {
          name: "construction_type",
          label: "Construction Type",
          labelDari: "نوع ساختمان",
          meaning: "concrete | brick | steel | mixed | traditional | other",
          type: "enum",
          required: false,
          example: "concrete",
        },
        {
          name: "current_use",
          label: "Current Use Description",
          labelDari: "توضیح کاربری",
          meaning: "How ENCC uses the property when usage_status = in_use",
          type: "longtext",
          required: false,
          example: "Coal storage and dispatch",
        },
        {
          name: "condition",
          label: "Physical Condition",
          labelDari: "وضعیت فیزیکی",
          meaning: "excellent | good | fair | poor | under_construction | demolished",
          type: "enum",
          required: false,
          example: "good",
        },
        {
          name: "acquisition_date",
          label: "Acquisition Date",
          labelDari: "تاریخ تحصیل",
          meaning: "When ENCC acquired the property — Hijri",
          type: "hijri_date",
          required: false,
          example: "1400/03/15",
        },
        {
          name: "estimated_value_afn",
          label: "Estimated Value (AFN)",
          labelDari: "ارزش تخمینی (افغانی)",
          meaning: "Approximate book or market value",
          type: "decimal",
          required: false,
          example: "15000000",
        },
        {
          name: "title_deed_number",
          label: "Title Deed Number",
          labelDari: "شماره سند مالکیت",
          meaning: "Tapu or ownership document number",
          type: "text",
          required: false,
          example: "TD-445566/1402",
        },
        {
          name: "registration_number",
          label: "Registration Number",
          labelDari: "شماره ثبت",
          meaning: "Official registration at municipality or land authority",
          type: "text",
          required: false,
          example: "REG-KBL-2023-8899",
        },
        {
          name: "tax_id",
          label: "Property Tax ID",
          labelDari: "شناسه مالیاتی",
          meaning: "Municipal or property tax reference",
          type: "text",
          required: false,
          example: "TAX-7788",
        },
        {
          name: "electricity_meter",
          label: "Electricity Meter",
          labelDari: "نمبر میتر برق",
          meaning: "Utility electricity meter number",
          type: "text",
          required: false,
          example: "EL-998877",
        },
        {
          name: "water_meter",
          label: "Water Meter",
          labelDari: "نمبر میتر آب",
          meaning: "Utility water meter number",
          type: "text",
          required: false,
          example: "WM-554433",
        },
        {
          name: "boundary_description",
          label: "Boundary Description",
          labelDari: "توضیحات حدود",
          meaning: "North/south/east/west boundaries or survey description",
          type: "longtext",
          required: false,
          example: "North: public road; South: neighbor plot #12",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Internal notes",
          type: "longtext",
          required: false,
          example: "Roof repaired 1404",
        },
      ],
    },
    {
      id: "ENT-PROP-021",
      name: "Property Document",
      description: "Child table — title deeds, survey maps, permits, insurance, and other property files (not lease contracts — those live in Procurement).",
      fields: [
        {
          name: "property_id",
          label: "Property",
          labelDari: "جایداد",
          meaning: "Parent property — reference → ENT-PROP-020",
          type: "reference",
          required: true,
          example: "PROP-KBL-0042",
        },
        {
          name: "document_id",
          label: "Document ID",
          labelDari: "شناسه سند",
          meaning: "Auto-generated unique id",
          type: "text",
          required: true,
          example: "DOC-PROP-0089",
        },
        {
          name: "document_type",
          label: "Document Type",
          labelDari: "نوع سند",
          meaning:
            "title_deed | survey_map | building_permit | tax_receipt | insurance | valuation_report | maintenance_record | utility_bill | correspondence | other",
          type: "enum",
          required: true,
          example: "title_deed",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "What this document is",
          type: "longtext",
          required: false,
          example: "Original tapu — 1400/03/15",
        },
        {
          name: "document_date",
          label: "Document Date",
          labelDari: "تاریخ سند",
          meaning: "Date on the document — Hijri",
          type: "hijri_date",
          required: false,
          example: "1400/03/15",
        },
        {
          name: "file",
          label: "File",
          labelDari: "فایل",
          meaning: "Scanned document upload",
          type: "file",
          required: true,
          example: "title_deed_scan.pdf",
          rules: "PDF, JPG, PNG; max 15 MB",
        },
      ],
    },
    {
      id: "ENT-PROP-022",
      name: "Property Image",
      description: "Optional photos — exterior, interior, aerial, map.",
      fields: [
        {
          name: "property_id",
          label: "Property",
          labelDari: "جایداد",
          meaning: "Parent property — reference → ENT-PROP-020",
          type: "reference",
          required: true,
          example: "PROP-KBL-0042",
        },
        {
          name: "image_id",
          label: "Image ID",
          labelDari: "شناسه عکس",
          meaning: "Auto-generated",
          type: "text",
          required: true,
          example: "IMG-PROP-0012",
        },
        {
          name: "image_type",
          label: "Image Type",
          labelDari: "نوع عکس",
          meaning: "exterior | interior | aerial | map | floor_plan | boundary | other",
          type: "enum",
          required: false,
          example: "exterior",
        },
        {
          name: "caption",
          label: "Caption",
          labelDari: "توضیح عکس",
          meaning: "Short description",
          type: "text",
          required: false,
          example: "Main entrance",
        },
        {
          name: "file",
          label: "Image File",
          labelDari: "فایل عکس",
          meaning: "Photo upload — optional",
          type: "file",
          required: true,
          example: "warehouse_exterior.jpg",
          rules: "JPG, PNG, WEBP; max 10 MB",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-PROP-020",
      name: "Register property",
      trigger: "New ENCC property to register",
      startActor: "Properties Clerk",
      endState: "Property active in register",
      flowDiagram:
        "Create header (type, name, usage_status) → location & details → documents → optional images → activate",
      steps: [
        {
          step: 1,
          actor: "Properties Clerk",
          action: "Create property master",
          input: "property_type_id, property_name, usage_status, province",
          output: "ENT-PROP-020 with auto property_code",
        },
        {
          step: 2,
          actor: "Properties Clerk",
          action: "Fill location and physical details",
          input: "district, address, areas, condition, title deed, etc.",
          output: "Complete profile — most fields optional",
        },
        {
          step: 3,
          actor: "Properties Clerk",
          action: "Upload documents and optional images",
          input: "ENT-PROP-021 / ENT-PROP-022 rows",
          output: "Files on record",
        },
        {
          step: 4,
          actor: "Properties Manager",
          action: "Review and activate",
          input: "Verify key details",
          output: "status: active",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-PROP-020",
      rule: "property_code auto-generated and unique",
      trigger: "Create property",
      response: "Assign PROP- prefix code",
      severity: "High",
    },
    {
      id: "BR-PROP-021",
      rule: "property_type_id, property_name, and usage_status required",
      trigger: "Save property",
      response: "Block if any missing",
      severity: "Critical",
    },
    {
      id: "BR-PROP-022",
      rule: "usage_status = rented_out set automatically when Procurement activates a lease; manual set allowed for migration",
      trigger: "Lease activated in Procurement",
      response: "Sync property usage_status to rented_out",
      severity: "High",
    },
    {
      id: "BR-PROP-023",
      rule: "When lease ends in Procurement, usage_status reverts to not_in_use unless ENCC resumes direct use",
      trigger: "Lease ended in Procurement",
      response: "Default to not_in_use; clerk may set in_use",
      severity: "Medium",
    },
    {
      id: "BR-PROP-024",
      rule: "No lease dates, rent amounts, or lessee data on property record — all in Procurement",
      trigger: "Property save",
      response: "Reject lease-specific fields if added",
      severity: "Critical",
    },
  ],
  validationRules: [
    {
      field: "property_type_id",
      rule: "Required reference to General Tables Property Type",
      uiBehavior: "Dropdown from active types; admin adds types in General Tables",
    },
    {
      field: "usage_status",
      rule: "Required — in_use | not_in_use | rented_out",
      uiBehavior: "Badge on list: green=in_use, gray=not_in_use, blue=rented_out",
    },
    {
      field: "property documents",
      rule: "PDF, JPG, PNG; max 15 MB",
      uiBehavior: "Inline child table",
    },
    {
      field: "property images",
      rule: "Optional; JPG, PNG, WEBP; max 10 MB",
      uiBehavior: "Gallery child table",
    },
  ],
  integrations: [
    {
      id: "INT-PROP-020",
      direction: "in",
      module: "General Tables — Branch (ENT-OPR-G009), Property Type (ENT-OPR-G010)",
      data: "branch_id, property_type_id",
      when: "Property create/edit",
    },
    {
      id: "INT-PROP-021",
      direction: "out",
      module: "Procurement — Property Lease",
      data: "property_code, property_name, usage_status",
      when: "Procurement selects property for bid or lease",
      note: "Property is the account header; lessees and rent live in Procurement",
    },
  ],
  crossModuleNotes: [
    "ENCC owns all registered properties — no external ownership types.",
    "usage_status rented_out means a private tenant holds an active lease managed in Procurement.",
    "Property Type (ENT-OPR-G010) is dynamic — admin adds warehouse, land, office, etc. in General Tables.",
  ],
  reports: [
    {
      id: "RPT-PROP-020",
      name: "Property register",
      purpose: "All properties with type, usage, province, branch",
      filters: "property_type_id, usage_status, province, branch_id, status",
      columns: "property_code, property_name, type, usage_status, province, branch, status",
      export: "Excel, PDF",
    },
    {
      id: "RPT-PROP-021",
      name: "Properties by usage",
      purpose: "Count in_use vs not_in_use vs rented_out",
      filters: "usage_status, province",
      columns: "usage_status, count, total_land_area_sqm",
      export: "Excel",
    },
    {
      id: "RPT-PROP-022",
      name: "Available for rent",
      purpose: "Properties with usage_status = not_in_use — candidates for Procurement lease",
      filters: "province, property_type_id",
      columns: "property_code, property_name, province, address, condition",
      export: "Excel, PDF",
    },
  ],
  deliverableChecklist: [
    { item: "Property register task documented", done: true },
    { item: "Dynamic property type in General Tables", done: true },
    { item: "usage_status separates renting from ENCC use", done: true },
    { item: "Lease/rent moved to Procurement", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
