import type { SectionDefinition } from "@/types/requirements";

export const branchesSection: SectionDefinition = {
  id: "branches",
  name: "Branches",
  nameDari: "نمایندگی‌ها / شعبات",
  enableReview: true,
  description:
    "Properties department (جایداد ها) manages ENCC branches and property records. Branches are regional or site offices linked to HQ departments.",
  status: "draft",
  summary: [
    "Register and maintain ENCC branch offices",
    "Branch name, location, manager, and status",
    "Link branches to departments and mine sites where applicable",
  ],
  entities: [
    {
      id: "ENT-PROP-010",
      name: "Branch",
      description: "ENCC branch or regional office.",
      fields: [
        {
          name: "branch_code",
          label: "Branch Code",
          labelDari: "کود نمایندگی",
          meaning: "Auto-generated unique branch code",
          type: "text",
          required: true,
          example: "BR-KBL-01",
        },
        {
          name: "branch_name",
          label: "Branch Name",
          labelDari: "نام نمایندگی",
          meaning: "Official branch name",
          type: "text",
          required: true,
          example: "Kabul HQ Branch",
        },
        {
          name: "branch_name_dari",
          label: "Branch Name (Dari)",
          labelDari: "نام نمایندگی (دری)",
          meaning: "Dari display name",
          type: "text",
          required: false,
          example: "نمایندگی کابل",
        },
        {
          name: "province",
          label: "Province",
          labelDari: "ولایت",
          meaning: "Province or region",
          type: "text",
          required: true,
          example: "Kabul",
        },
        {
          name: "address",
          label: "Address",
          labelDari: "آدرس",
          meaning: "Physical address",
          type: "longtext",
          required: true,
          example: "District 4, Kabul",
        },
        {
          name: "manager_name",
          label: "Branch Manager",
          labelDari: "مدیر نمایندگی",
          meaning: "Person in charge",
          type: "text",
          required: false,
          example: "Abdul Wahid",
        },
        {
          name: "phone",
          label: "Phone",
          labelDari: "تلفن",
          meaning: "Contact number",
          type: "text",
          required: false,
          example: "0700123456",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | inactive | under_setup",
          type: "enum",
          required: true,
          example: "active",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-PROP-010",
      name: "Register branch",
      trigger: "New ENCC branch or regional office established",
      startActor: "Properties clerk",
      endState: "Branch active in system",
      steps: [
        {
          step: 1,
          actor: "Properties clerk",
          action: "Create branch record with name, province, address",
          input: "Branch details",
          output: "Draft with auto branch code",
        },
        {
          step: 2,
          actor: "Properties clerk",
          action: "Assign manager and activate",
          input: "Manager name",
          output: "status: active",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-PROP-010",
      rule: "Branch code auto-generated and unique",
      trigger: "Create",
      response: "Assign BR- prefix code",
      severity: "High",
    },
  ],
  deliverableChecklist: [
    { item: "Branches task documented", done: true },
    { item: "Property asset management (future)", done: false },
    { item: "ENCC sign-off", done: false },
  ],
};
