import type { SectionDefinition } from "@/types/requirements";

export const employeeAttendanceSection: SectionDefinition = {
  id: "employee-attendance",
  name: "Employee Attendance",
  nameDari: "حاضری کارمندان",
  enableReview: true,
  description:
    "Simple monthly attendance for permanent employees (کارمندان دائمی). Select month, from/to dates, and title — one line per employee with day counts: present, absent, and leave columns. Data comes from the fingerprint system; approved month feeds salary in معاشات.",
  status: "draft",
  currentTool: "Fingerprint system export → HR monthly register → payroll",
  summary: [
    "Monthly Attendance (ENT-HR-016) — month, date from, date to, title",
    "Attendance Line (ENT-HR-017) — one row per permanent employee",
    "Line columns: days_present, days_absent, leave_required, holiday_leave, makul, khademati — all day counts",
    "Footer: column totals for the month",
    "Year reports: month-by-month and yearly totals per employee",
    "Approved month → auto salary in Salaries",
  ],
  precededBy: [{ moduleId: "hr", sectionId: "hr", label: "Employee master" }],
  followedBy: [{ moduleId: "salaries", sectionId: "salaries", label: "Salaries" }],
  relatedSections: ["hr", "leave-requests", "salaries"],
  roles: [
    {
      role: "HR Clerk",
      location: "HQ — منابع بشری",
      mainActions: "Create monthly attendance, enter or import lines, submit",
      approval: false,
      readOnly: false,
    },
    {
      role: "HR Manager",
      location: "HQ",
      mainActions: "Approve monthly attendance before payroll",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View attendance reports",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-HR-016",
      name: "Monthly Attendance",
      description:
        "One register per Hijri month — simple header with month, date range, and title. Child lines list all permanent employees.",
      fields: [
        {
          name: "attendance_id",
          label: "Attendance ID",
          labelDari: "شناسه",
          meaning: "Auto-generated number",
          type: "text",
          required: true,
          example: "ATT-1405/03",
          rules: "Auto-generated; unique per month",
        },
        {
          name: "title",
          label: "Title",
          labelDari: "عنوان",
          meaning: "Short title for this month — e.g. حاضری ماه حوت 1405",
          type: "text",
          required: true,
          example: "حاضری ماه حوت 1405",
        },
        {
          name: "hijri_year",
          label: "Year",
          labelDari: "سال",
          meaning: "Hijri year",
          type: "text",
          required: true,
          example: "1405",
        },
        {
          name: "hijri_month",
          label: "Month",
          labelDari: "ماه",
          meaning: "Hijri month 1–12",
          type: "text",
          required: true,
          example: "03",
        },
        {
          name: "date_from",
          label: "From Date",
          labelDari: "از تاریخ",
          meaning: "Start of attendance period — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/03/01",
        },
        {
          name: "date_to",
          label: "To Date",
          labelDari: "تا تاریخ",
          meaning: "End of attendance period — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/03/30",
          rules: "Must be on or after date_from",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | approved",
          type: "enum",
          required: true,
          example: "approved",
        },
      ],
    },
    {
      id: "ENT-HR-017",
      name: "Attendance Line",
      description:
        "One row per permanent employee — six day-count columns only. Employee name shown from HR master.",
      fields: [
        {
          name: "employee_id",
          label: "Employee",
          labelDari: "کارمند",
          meaning: "Reference → ENT-HR-010 — permanent employees only",
          type: "reference",
          required: true,
          example: "EMP-0045 — Mohammad بن رحیم",
          rules: "employment_type=permanent only",
        },
        {
          name: "days_present",
          label: "Present",
          labelDari: "حاضر",
          meaning: "Present days — day count, same as days_absent",
          type: "decimal",
          required: true,
          example: "20",
        },
        {
          name: "days_absent",
          label: "Absent",
          labelDari: "غیرحاضر",
          meaning: "Absent days",
          type: "decimal",
          required: true,
          example: "1",
        },
        {
          name: "leave_required",
          label: "Leave Required",
          labelDari: "رخصتی مورد نیاز",
          meaning: "Required / earned leave days used",
          type: "decimal",
          required: true,
          example: "2",
        },
        {
          name: "holiday_leave",
          label: "Holiday Leave",
          labelDari: "رخصتی تعطیلات",
          meaning: "Public holiday leave days",
          type: "decimal",
          required: true,
          example: "2",
        },
        {
          name: "makul",
          label: "Makul",
          labelDari: "مکول",
          meaning: "Makul days",
          type: "decimal",
          required: true,
          example: "0",
        },
        {
          name: "khademati",
          label: "Khademati",
          labelDari: "خدمتی",
          meaning: "Service / official duty days",
          type: "decimal",
          required: true,
          example: "1",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-HR-016",
      name: "Record monthly attendance",
      trigger: "End of Hijri month",
      startActor: "HR Clerk",
      endState: "Approved attendance — salaries auto-created",
      flowDiagram: "Select month + dates + title → load permanent employees → enter six columns → approve → salaries",
      steps: [
        {
          step: 1,
          actor: "HR Clerk",
          action: "Create monthly attendance",
          input: "title, hijri_year, hijri_month, date_from, date_to",
          output: "ENT-HR-016 draft",
        },
        {
          step: 2,
          actor: "System",
          action: "Load permanent employees",
          input: "ENT-HR-010 where employment_type=permanent",
          output: "One ENT-HR-017 line per employee",
        },
        {
          step: 3,
          actor: "HR Clerk",
          action: "Enter attendance lines",
          input: "days_present, days_absent, leave_required, holiday_leave, makul, khademati per employee",
          output: "Lines saved — footer totals updated",
        },
        {
          step: 4,
          actor: "HR Manager",
          action: "Approve",
          input: "status=approved",
          output: "Salary drafts created in معاشات for this month",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-HR-030",
      rule: "One monthly attendance per Hijri year + month",
      trigger: "Create attendance",
      response: "Block duplicate month",
      severity: "Critical",
    },
    {
      id: "BR-HR-031",
      rule: "Lines are permanent employees only",
      trigger: "Load lines",
      response: "Filter employment_type=permanent",
      severity: "Critical",
    },
    {
      id: "BR-HR-032",
      rule: "date_to must be on or after date_from",
      trigger: "Save header",
      response: "Block invalid range",
      severity: "Critical",
    },
    {
      id: "BR-HR-033",
      rule: "Footer totals = sum of each column on all lines",
      trigger: "Save line",
      response: "Auto-update month totals",
      severity: "High",
    },
    {
      id: "BR-HR-034",
      rule: "Approved attendance auto-creates salary drafts in Salaries",
      trigger: "Approve",
      response: "Create ENT-SAL-010 for same month",
      severity: "Critical",
    },
  ],
  permissionsMatrix: [
    { action: "Create / edit monthly attendance", archiveClerk: "—", executive: "R", deptStaff: "—", auditor: "—" },
    { action: "Approve monthly attendance", archiveClerk: "—", executive: "A", deptStaff: "—", auditor: "—" },
    { action: "View reports", archiveClerk: "—", executive: "R", deptStaff: "R", auditor: "R" },
  ],
  reports: [
    {
      id: "RPT-HR-018",
      name: "Monthly Attendance Sheet",
      purpose: "One month — all permanent employees with six columns and footer totals",
      filters: "hijri_year, hijri_month, title",
      columns:
        "employee, days_present, days_absent, leave_required, holiday_leave, makul, khademati | footer totals",
      export: "PDF, Excel",
    },
    {
      id: "RPT-HR-019",
      name: "Employee Year Register",
      purpose: "One employee — each month in the year with six columns; year totals at bottom",
      filters: "employee_id, hijri_year",
      columns:
        "month, days_present, days_absent, leave_required, holiday_leave, makul, khademati | year totals",
      export: "PDF, Excel",
    },
    {
      id: "RPT-HR-020",
      name: "Yearly Summary",
      purpose: "All permanent employees — yearly totals per column for one Hijri year",
      filters: "hijri_year, branch, department",
      columns:
        "employee, total_present, total_absent, total_leave_required, total_holiday_leave, total_makul, total_khademati",
      export: "PDF, Excel",
    },
  ],
  validationRules: [
    { field: "title", rule: "Required", uiBehavior: "Text input — عنوان" },
    { field: "hijri_year", rule: "Required", uiBehavior: "Year — Hijri" },
    { field: "hijri_month", rule: "Required 1–12", uiBehavior: "Month dropdown — ماه" },
    { field: "date_from", rule: "Required Hijri date", uiBehavior: "Date picker — از تاریخ" },
    { field: "date_to", rule: "Required; ≥ date_from", uiBehavior: "Date picker — تا تاریخ" },
    { field: "employee_id", rule: "Required; permanent only", uiBehavior: "Employee name from HR master" },
    { field: "days_present", rule: "Required; ≥ 0", uiBehavior: "Number — حاضر (days)" },
    { field: "days_absent", rule: "Required; ≥ 0", uiBehavior: "Number — غیرحاضر" },
    { field: "leave_required", rule: "Required; ≥ 0", uiBehavior: "Number — رخصتی مورد نیاز" },
    { field: "holiday_leave", rule: "Required; ≥ 0", uiBehavior: "Number — رخصتی تعطیلات" },
    { field: "makul", rule: "Required; ≥ 0", uiBehavior: "Number — مکول" },
    { field: "khademati", rule: "Required; ≥ 0", uiBehavior: "Number — خدمتی" },
  ],
  integrations: [
    {
      id: "INT-HR-018",
      direction: "in",
      module: "Fingerprint system",
      data: "employee + present, absent, leave day counts per month",
      when: "Import or manual entry after export",
      note: "Primary data source",
    },
    {
      id: "INT-HR-019",
      direction: "in",
      module: "HR — Employee Record (ENT-HR-010)",
      data: "permanent employees for line list",
      when: "Create monthly attendance",
      note: "Auto-load all permanent staff",
    },
    {
      id: "INT-HR-021",
      direction: "out",
      module: "Salaries — Salary Payment (ENT-SAL-010)",
      data: "days_present, days_absent, leave_required, holiday_leave, makul, khademati",
      when: "Month approved",
      note: "Auto salary generation",
    },
  ],
  crossModuleNotes: [
    "Simple monthly form — month, from/to dates, title, then one line per permanent employee.",
    "Six columns on each line — all day counts: days_present, days_absent, leave_required, holiday_leave, makul, khademati.",
    "Separate from Site daily attendance (contract workers).",
    "Approved month feeds معاشات automatically.",
  ],
  deliverableChecklist: [
    { item: "Simple header — month, date from/to, title", done: true },
    { item: "Six-column attendance lines for permanent employees", done: true },
    { item: "Monthly footer totals and yearly reports", done: true },
    { item: "Salary auto-generation on approve", done: true },
    { item: "ENCC sign-off on fingerprint import format", done: false },
  ],
};
