import type { SectionDefinition } from "@/types/requirements";

export const hrSection: SectionDefinition = {
  id: "hr",
  name: "Human Resources",
  nameDari: "منابع بشری",
  enableReview: true,
  description:
    "HR department (منابع بشری) — canonical employee master data used across ENCC modules (جمع اشخاص, معاشات, and future sections). Employee header holds identity and assignment; Position master (بست) defines available roles; Assignment History tracks branch/department/position moves; Education records hold degree level (bachelor, master, PhD, etc.); Person Documents store typed file attachments.",
  status: "draft",
  currentTool: "Paper personnel files, position charts, and physical document folders per employee",
  summary: [
    "Employee master (ENT-HR-010) — single source of truth for all modules that reference staff",
    "Identity: first name, father name, grandfather name, display name, tazkira, birth date, gender",
    "Assignment: department, branch, position_id → Position master (بست), hire date, employment type, status",
    "Position master (ENT-HR-012) — register of بست slots: title, grade, department, min education level",
    "Assignment History (ENT-HR-013) — each branch transfer, department move, or position change with from/to and effective date",
    "Employee Education (ENT-HR-014) — degree rows: primary, secondary, diploma, bachelor, master, PhD + certificate file",
    "highest_education_level on employee — computed from education records for quick display",
    "Person Documents (ENT-HR-011) — child table per employee: document type, description, file, dates",
    "Leave requests registered in section leave-requests (ENT-HR-015)",
    "Active employees filtered by branch for pickers; on_leave and terminated excluded by default",
  ],
  precededBy: [],
  followedBy: [{ moduleId: "salaries", sectionId: "salaries", label: "Salaries" }],
  relatedSections: ["leave-requests", "person-register", "salaries", "general-tables"],
  roles: [
    {
      role: "HR Clerk",
      location: "HQ — منابع بشری",
      mainActions: "Create and update employee records, upload person documents, record transfers",
      approval: false,
      readOnly: false,
    },
    {
      role: "HR Manager",
      location: "HQ",
      mainActions: "Approve hiring, termination, and sensitive document changes",
      approval: true,
      readOnly: false,
    },
    {
      role: "Department Staff",
      location: "HQ — any department",
      mainActions: "View employee list and documents for own department (read-only)",
      approval: false,
      readOnly: true,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "Read-only view of all employees, documents, and change history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-HR-010",
      name: "Employee Record",
      description:
        "Core HR employee master — referenced by جمع اشخاص (ENT-ITM-040), Salary Payment (ENT-SAL-010), and future modules. One row per person employed at ENCC.",
      fields: [
        {
          name: "employee_code",
          label: "Employee Code",
          labelDari: "کود کارمند",
          meaning: "System-generated unique employee identifier",
          type: "text",
          required: true,
          example: "EMP-0045",
          rules: "Auto-generated on create; unique; immutable",
        },
        {
          name: "first_name",
          label: "First Name",
          labelDari: "نام",
          meaning: "Employee given name",
          type: "text",
          required: true,
          example: "Mohammad",
        },
        {
          name: "father_name",
          label: "Father Name",
          labelDari: "نام پدر",
          meaning: "Patronymic — primary search key with first name",
          type: "text",
          required: true,
          example: "Rahim",
        },
        {
          name: "grandfather_name",
          label: "Grandfather Name",
          labelDari: "نام پدرکلان",
          meaning: "Third name — common on Afghan identity documents",
          type: "text",
          required: false,
          example: "Karim",
        },
        {
          name: "display_name",
          label: "Display Name",
          labelDari: "نام نمایشی",
          meaning: "Auto: first_name + father_name (+ grandfather_name when present) — shown in dropdowns",
          type: "text",
          required: true,
          example: "Mohammad بن رحیم",
          rules: "System-generated; used in employee pickers across modules",
        },
        {
          name: "full_name",
          label: "Full Legal Name",
          labelDari: "نام کامل قانونی",
          meaning: "Full name as on official documents — may differ from display_name formatting",
          type: "text",
          required: false,
          example: "Mohammad Rahim Karim",
        },
        {
          name: "national_id",
          label: "National ID / Tazkira Number",
          labelDari: "شماره تذکره",
          meaning: "Identity document number from paper tazkira",
          type: "text",
          required: false,
          example: "1234567",
          rules: "Unique when provided; scan stored in Person Documents (type=tazkira)",
        },
        {
          name: "birth_date",
          label: "Birth Date",
          labelDari: "تاریخ تولد",
          meaning: "Date of birth — Hijri",
          type: "hijri_date",
          required: false,
          example: "1370/03/15",
        },
        {
          name: "gender",
          label: "Gender",
          labelDari: "جنسیت",
          meaning: "male | female",
          type: "enum",
          required: false,
          example: "male",
        },
        {
          name: "marital_status",
          label: "Marital Status",
          labelDari: "وضعیت تأهل",
          meaning: "single | married | divorced | widowed",
          type: "enum",
          required: false,
          example: "married",
        },
        {
          name: "phone",
          label: "Phone",
          labelDari: "شماره تماس",
          meaning: "Primary mobile or landline",
          type: "text",
          required: false,
          example: "0700123456",
        },
        {
          name: "email",
          label: "Email",
          labelDari: "ایمیل",
          meaning: "Work or personal email",
          type: "text",
          required: false,
          example: "m.rahimi@encc.af",
        },
        {
          name: "address",
          label: "Address",
          labelDari: "آدرس",
          meaning: "Residential address",
          type: "longtext",
          required: false,
          example: "District 5, Kabul",
        },
        {
          name: "department_id",
          label: "Department",
          labelDari: "ریاست",
          meaning: "Current department (ریاست) assignment",
          type: "reference",
          required: true,
          example: "Operations",
        },
        {
          name: "branch_id",
          label: "Branch",
          labelDari: "شعبه",
          meaning: "Branch assignment — filters employee pickers (e.g. جمع اشخاص)",
          type: "reference",
          required: true,
          example: "Branch A",
        },
        {
          name: "position_id",
          label: "Position",
          labelDari: "بست",
          meaning: "Current position slot — reference → Position master (ENT-HR-012)",
          type: "reference",
          required: true,
          example: "POS-012 — Clerk, Grade 3",
          rules: "Dropdown from active positions; updated via Assignment History on transfer/promotion",
        },
        {
          name: "highest_education_level",
          label: "Highest Education",
          labelDari: "بالاترین تحصیلات",
          meaning:
            "Computed from Employee Education rows — primary | secondary | diploma | bachelor | master | phd | other",
          type: "enum",
          required: false,
          example: "bachelor",
          rules: "Read-only; auto-updated when education records change",
        },
        {
          name: "employment_type",
          label: "Employment Type",
          labelDari: "نوع استخدام",
          meaning: "permanent | contract | temporary | daily_wage",
          type: "enum",
          required: true,
          example: "permanent",
        },
        {
          name: "hire_date",
          label: "Hire Date",
          labelDari: "تاریخ استخدام",
          meaning: "Start of employment — Hijri",
          type: "hijri_date",
          required: true,
          example: "1400/05/01",
        },
        {
          name: "end_date",
          label: "End Date",
          labelDari: "تاریخ ختم",
          meaning: "Termination or contract end date — Hijri; required when status=terminated",
          type: "hijri_date",
          required: "conditional",
          example: "1405/01/20",
          rules: "Required when status is terminated or contract ended",
        },
        {
          name: "termination_reason",
          label: "Termination Reason",
          labelDari: "دلیل ختم خدمت",
          meaning: "Why employment ended — optional text",
          type: "longtext",
          required: false,
          example: "Contract completed",
          rules: "Recommended when status=terminated",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | on_leave | suspended | terminated",
          type: "enum",
          required: true,
          example: "active",
          rules: "Only active employees appear in cross-module pickers; on_leave may be configurable per module",
        },
        {
          name: "bank_account_ref",
          label: "Salary Bank Account",
          labelDari: "حساب بانکی معاش",
          meaning: "Reference → Bank Account (ENT-OPR-G006) for salary deposits",
          type: "reference",
          required: false,
          example: "ENCC Main — Account 12345",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Internal HR notes not shown on external pickers",
          type: "longtext",
          required: false,
          example: "Transferred from Branch B in 1404",
        },
        {
          name: "photo",
          label: "Photo",
          labelDari: "عکس",
          meaning: "Employee portrait for personnel file — separate from document scans",
          type: "file",
          required: false,
          example: "emp_0045_photo.jpg",
          rules: "JPG, PNG; max 5 MB",
        },
      ],
    },
    {
      id: "ENT-HR-011",
      name: "Person Document",
      description:
        "Child table on Employee Record — one row per scanned document attached to an employee account. Same attachment pattern as other modules: document type (file type), description, and file upload. Multiple documents per employee; each may have its own start date, expiry, and issue metadata.",
      fields: [
        {
          name: "employee_id",
          label: "Employee",
          labelDari: "کارمند",
          meaning: "Parent employee — reference → ENT-HR-010",
          type: "reference",
          required: true,
          example: "EMP-0045 — Mohammad بن رحیم",
        },
        {
          name: "document_id",
          label: "Document ID",
          labelDari: "شناسه سند",
          meaning: "System-generated unique id for this document row",
          type: "text",
          required: true,
          example: "DOC-HR-0089",
          rules: "Auto-generated; unique per document row",
        },
        {
          name: "document_type",
          label: "Document Type",
          labelDari: "نوع سند",
          meaning:
            "tazkira | appointment_order | contract | education_certificate | medical_certificate | training_certificate | clearance | license | disciplinary | other",
          type: "enum",
          required: true,
          example: "contract",
          rules: "Classifies the file — drives filters and required-date rules per type",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Human-readable summary of this document — what it is and why it was filed",
          type: "longtext",
          required: true,
          example: "Permanent employment contract — signed 1400/05/01",
        },
        {
          name: "file",
          label: "File",
          labelDari: "فایل",
          meaning: "Scanned or uploaded document file",
          type: "file",
          required: true,
          example: "contract_emp_0045_1400.pdf",
          rules: "PDF, JPG, PNG; max 10 MB — same constraints as Archive and Mali attachments",
        },
        {
          name: "start_date",
          label: "Start Date",
          labelDari: "تاریخ شروع",
          meaning: "When this document becomes effective — e.g. contract start, appointment date",
          type: "hijri_date",
          required: true,
          example: "1400/05/01",
        },
        {
          name: "expiry_date",
          label: "Expiry Date",
          labelDari: "تاریخ انقضا",
          meaning: "When document expires — contracts, licenses, medical certs",
          type: "hijri_date",
          required: false,
          example: "1405/05/01",
          rules: "Recommended for contract, license, medical_certificate types",
        },
        {
          name: "issue_date",
          label: "Issue Date",
          labelDari: "تاریخ صادره",
          meaning: "Date printed on the document by issuing authority",
          type: "hijri_date",
          required: false,
          example: "1400/04/28",
        },
        {
          name: "document_number",
          label: "Document Number",
          labelDari: "شماره سند",
          meaning: "Official reference number on the paper document",
          type: "text",
          required: false,
          example: "حکم 45/1400",
        },
        {
          name: "issuing_authority",
          label: "Issuing Authority",
          labelDari: "مرجع صادرکننده",
          meaning: "Organization or person that issued the document",
          type: "text",
          required: false,
          example: "ENCC HR Directorate",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | expired | superseded",
          type: "enum",
          required: true,
          example: "active",
          rules: "superseded when a newer document of same type replaces this one",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Optional internal notes about this document row",
          type: "longtext",
          required: false,
          example: "Renewed annually — previous version DOC-HR-0062 superseded",
        },
        {
          name: "uploaded_by",
          label: "Uploaded By",
          labelDari: "آپلود شده توسط",
          meaning: "HR user who attached this file",
          type: "reference",
          required: true,
          example: "HR Clerk — Fatima",
        },
        {
          name: "uploaded_at",
          label: "Uploaded At",
          labelDari: "تاریخ آپلود",
          meaning: "System timestamp when file was stored",
          type: "datetime",
          required: true,
          example: "1405/03/11 14:30",
        },
      ],
    },
    {
      id: "ENT-HR-012",
      name: "Position (بست)",
      description:
        "Master register of position slots at ENCC — title, grade, department, and minimum education. Employees reference position_id; transfers record from/to positions in Assignment History.",
      fields: [
        {
          name: "position_code",
          label: "Position Code",
          labelDari: "کود بست",
          meaning: "System-generated unique position identifier",
          type: "text",
          required: true,
          example: "POS-012",
          rules: "Auto-generated; unique; immutable",
        },
        {
          name: "title",
          label: "Position Title",
          labelDari: "عنوان بست",
          meaning: "Job title in English or official form",
          type: "text",
          required: true,
          example: "Clerk",
        },
        {
          name: "title_dari",
          label: "Position Title (Dari)",
          labelDari: "عنوان بست (دری)",
          meaning: "Job title in Dari — shown in HR reports",
          type: "text",
          required: true,
          example: "کارمند",
        },
        {
          name: "grade",
          label: "Grade",
          labelDari: "رتبه",
          meaning: "Position grade or rank — used for payroll and seniority",
          type: "text",
          required: true,
          example: "Grade 3",
        },
        {
          name: "department_id",
          label: "Department",
          labelDari: "ریاست",
          meaning: "Department this position belongs to — optional when position is org-wide",
          type: "reference",
          required: false,
          example: "Operations",
        },
        {
          name: "min_education_level",
          label: "Minimum Education",
          labelDari: "حداقل تحصیلات",
          meaning:
            "Minimum required education — primary | secondary | diploma | bachelor | master | phd | none",
          type: "enum",
          required: false,
          example: "bachelor",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Role summary and responsibilities",
          type: "longtext",
          required: false,
          example: "General office clerk — filing and correspondence",
        },
        {
          name: "max_headcount",
          label: "Max Headcount",
          labelDari: "حداکثر ظرفیت",
          meaning: "How many employees may hold this position at once — optional",
          type: "decimal",
          required: false,
          example: "5",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Inactive positions hidden from new assignments",
          type: "boolean",
          required: true,
          example: "true",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Internal HR notes about this position slot",
          type: "longtext",
          required: false,
          example: "Created under 1404 reorganization",
        },
      ],
    },
    {
      id: "ENT-HR-013",
      name: "Assignment History (Transfer / Move)",
      description:
        "History row each time an employee moves branch, department, or position (بست). Current assignment on ENT-HR-010 is updated when a transfer is recorded; this table keeps the full audit trail with from/to values and effective date.",
      fields: [
        {
          name: "assignment_id",
          label: "Assignment ID",
          labelDari: "شناسه انتقال",
          meaning: "System-generated unique id for this history row",
          type: "text",
          required: true,
          example: "ASG-0033",
          rules: "Auto-generated; unique",
        },
        {
          name: "employee_id",
          label: "Employee",
          labelDari: "کارمند",
          meaning: "Reference → ENT-HR-010",
          type: "reference",
          required: true,
          example: "EMP-0045",
        },
        {
          name: "effective_date",
          label: "Effective Date",
          labelDari: "تاریخ نافذ",
          meaning: "When the new assignment starts — Hijri",
          type: "hijri_date",
          required: true,
          example: "1404/11/01",
        },
        {
          name: "change_type",
          label: "Change Type",
          labelDari: "نوع تغییر",
          meaning:
            "branch_transfer | department_transfer | position_change | promotion | demotion | combined",
          type: "enum",
          required: true,
          example: "branch_transfer",
        },
        {
          name: "from_branch_id",
          label: "From Branch",
          labelDari: "از شعبه",
          meaning: "Previous branch — required when branch changes",
          type: "reference",
          required: "conditional",
          example: "Branch B",
        },
        {
          name: "to_branch_id",
          label: "To Branch",
          labelDari: "به شعبه",
          meaning: "New branch",
          type: "reference",
          required: "conditional",
          example: "Branch A",
        },
        {
          name: "from_department_id",
          label: "From Department",
          labelDari: "از ریاست",
          meaning: "Previous department",
          type: "reference",
          required: "conditional",
          example: "Commercial",
        },
        {
          name: "to_department_id",
          label: "To Department",
          labelDari: "به ریاست",
          meaning: "New department",
          type: "reference",
          required: "conditional",
          example: "Operations",
        },
        {
          name: "from_position_id",
          label: "From Position",
          labelDari: "از بست",
          meaning: "Previous position — reference → ENT-HR-012",
          type: "reference",
          required: "conditional",
          example: "POS-008 — Assistant",
        },
        {
          name: "to_position_id",
          label: "To Position",
          labelDari: "به بست",
          meaning: "New position",
          type: "reference",
          required: "conditional",
          example: "POS-012 — Clerk",
        },
        {
          name: "order_number",
          label: "Order Number",
          labelDari: "شماره حکم",
          meaning: "Official transfer or appointment order number",
          type: "text",
          required: false,
          example: "حکم 78/1404",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Reason and context for the move",
          type: "longtext",
          required: true,
          example: "Transferred to Branch A per HQ directive",
        },
        {
          name: "attachment",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional scan of transfer or appointment order (حکم)",
          type: "file",
          required: false,
          example: "transfer_order_78_1404.pdf",
          rules: "PDF, JPG, PNG; max 10 MB",
        },
        {
          name: "recorded_by",
          label: "Recorded By",
          labelDari: "ثبت شده توسط",
          meaning: "HR user who recorded the transfer",
          type: "reference",
          required: true,
          example: "HR Clerk — Fatima",
        },
        {
          name: "recorded_at",
          label: "Recorded At",
          labelDari: "تاریخ ثبت",
          meaning: "System timestamp when row was created",
          type: "datetime",
          required: true,
          example: "1404/10/28 15:00",
        },
      ],
    },
    {
      id: "ENT-HR-014",
      name: "Employee Education",
      description:
        "Education history per employee — one row per degree or certificate. education_level uses standard tiers: primary, secondary, diploma, bachelor (لیسانس), master (ماجستیر), PhD (دکترا). Certificate scan stored as file with description.",
      fields: [
        {
          name: "education_id",
          label: "Education ID",
          labelDari: "شناسه تحصیلات",
          meaning: "System-generated unique id",
          type: "text",
          required: true,
          example: "EDU-0018",
          rules: "Auto-generated; unique",
        },
        {
          name: "employee_id",
          label: "Employee",
          labelDari: "کارمند",
          meaning: "Reference → ENT-HR-010",
          type: "reference",
          required: true,
          example: "EMP-0045",
        },
        {
          name: "education_level",
          label: "Education Level",
          labelDari: "سطح تحصیلات",
          meaning:
            "primary | secondary | diploma | bachelor | master | phd | other — لیسانس / ماجستیر / دکترا",
          type: "enum",
          required: true,
          example: "bachelor",
        },
        {
          name: "field_of_study",
          label: "Field of Study",
          labelDari: "رشته",
          meaning: "Major or specialization",
          type: "text",
          required: true,
          example: "Business Administration",
        },
        {
          name: "institution",
          label: "Institution",
          labelDari: "مؤسسه / دانشگاه",
          meaning: "School, college, or university name",
          type: "text",
          required: true,
          example: "Kabul University",
        },
        {
          name: "country",
          label: "Country",
          labelDari: "کشور",
          meaning: "Where degree was obtained",
          type: "text",
          required: false,
          example: "Afghanistan",
        },
        {
          name: "start_date",
          label: "Start Date",
          labelDari: "تاریخ شروع",
          meaning: "When studies began — Hijri; optional",
          type: "hijri_date",
          required: false,
          example: "1390/07/01",
        },
        {
          name: "graduation_date",
          label: "Graduation Date",
          labelDari: "تاریخ فارغ‌التحصیلی",
          meaning: "When degree was completed — Hijri",
          type: "hijri_date",
          required: false,
          example: "1394/06/15",
        },
        {
          name: "certificate_number",
          label: "Certificate Number",
          labelDari: "شماره مدرک",
          meaning: "Number on the diploma or certificate",
          type: "text",
          required: false,
          example: "KU-2015-4521",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Additional context — honors, thesis topic, etc.",
          type: "longtext",
          required: false,
          example: "Bachelor of Business Administration — full-time",
        },
        {
          name: "file",
          label: "Certificate File",
          labelDari: "فایل مدرک",
          meaning: "Scan of diploma or certificate",
          type: "file",
          required: false,
          example: "bachelor_cert_0045.pdf",
          rules: "PDF, JPG, PNG; max 10 MB",
        },
        {
          name: "is_verified",
          label: "Verified",
          labelDari: "تأیید شده",
          meaning: "HR has verified certificate against original",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-HR-010",
      name: "Register new employee",
      trigger: "New hire approved",
      startActor: "HR Clerk",
      endState: "Employee active with required documents on file",
      flowDiagram: "Create employee header → upload Person Documents (tazkira, contract, appointment order) → status=active",
      steps: [
        {
          step: 1,
          actor: "HR Clerk",
          action: "Create employee master",
          input: "first_name, father_name, department, branch, position_id, hire_date, employment_type",
          output: "ENT-HR-010 with employee_code and display_name",
        },
        {
          step: 2,
          actor: "HR Clerk",
          action: "Add person documents",
          input: "document_type, description, file, start_date per row",
          output: "ENT-HR-011 rows linked to employee_id",
        },
        {
          step: 3,
          actor: "HR Manager",
          action: "Review and confirm",
          input: "Employee + documents complete",
          output: "status=active; employee available in cross-module pickers",
        },
      ],
    },
    {
      id: "WF-HR-011",
      name: "Add or renew person document",
      trigger: "New contract, renewed license, or updated tazkira scan",
      startActor: "HR Clerk",
      endState: "New document row active; prior version superseded if applicable",
      steps: [
        {
          step: 1,
          actor: "HR Clerk",
          action: "Open employee file",
          input: "employee_id",
          output: "Employee detail with document table",
        },
        {
          step: 2,
          actor: "HR Clerk",
          action: "Add document row",
          input: "document_type, description, file, start_date, expiry_date optional",
          output: "ENT-HR-011 created",
        },
        {
          step: 3,
          actor: "HR Clerk",
          action: "Supersede old version",
          input: "Prior row of same document_type",
          output: "Old row status=superseded",
        },
      ],
    },
    {
      id: "WF-HR-012",
      name: "Terminate employee",
      trigger: "Employment ends",
      startActor: "HR Manager",
      endState: "status=terminated; excluded from active pickers; historical data retained",
      steps: [
        {
          step: 1,
          actor: "HR Manager",
          action: "Set termination",
          input: "end_date, termination_reason, status=terminated",
          output: "Employee no longer in active pickers",
        },
        {
          step: 2,
          actor: "HR Clerk",
          action: "File clearance document",
          input: "document_type=clearance, description, file, start_date",
          output: "Clearance row on ENT-HR-011",
        },
      ],
    },
    {
      id: "WF-HR-013",
      name: "Record branch / department / position transfer",
      trigger: "Employee moves branch, ریاست, or بست",
      startActor: "HR Clerk",
      endState: "Assignment History row created; employee current fields updated",
      flowDiagram: "Record transfer → from/to branch/dept/position → effective_date → update ENT-HR-010",
      steps: [
        {
          step: 1,
          actor: "HR Clerk",
          action: "Open employee and start transfer",
          input: "employee_id, change_type, effective_date",
          output: "Draft assignment history",
        },
        {
          step: 2,
          actor: "HR Clerk",
          action: "Enter from/to values",
          input: "from_branch_id, to_branch_id, from_department_id, to_department_id, from_position_id, to_position_id",
          output: "Full before/after snapshot on ENT-HR-013",
        },
        {
          step: 3,
          actor: "HR Clerk",
          action: "Attach حکم if available",
          input: "order_number, attachment optional",
          output: "Document on ENT-HR-013",
        },
        {
          step: 4,
          actor: "System",
          action: "Update employee current assignment",
          input: "to_branch_id, to_department_id, to_position_id on effective_date",
          output: "ENT-HR-010 updated; جمع اشخاص branch filter uses new branch",
        },
      ],
    },
    {
      id: "WF-HR-014",
      name: "Register employee education",
      trigger: "New degree or certificate filed",
      startActor: "HR Clerk",
      endState: "Education row saved; highest_education_level updated on employee",
      steps: [
        {
          step: 1,
          actor: "HR Clerk",
          action: "Add education row",
          input: "education_level, field_of_study, institution, graduation_date",
          output: "ENT-HR-014 created",
        },
        {
          step: 2,
          actor: "HR Clerk",
          action: "Upload certificate scan",
          input: "description, file",
          output: "Certificate stored",
        },
        {
          step: 3,
          actor: "HR Clerk",
          action: "Verify certificate",
          input: "is_verified=true",
          output: "highest_education_level recomputed on employee",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-HR-010",
      rule: "employee_code is system-generated and immutable after create",
      trigger: "Create employee",
      response: "Assign EMP-XXXX; block manual override",
      severity: "Critical",
    },
    {
      id: "BR-HR-011",
      rule: "display_name auto-generated from first_name + father_name (+ grandfather_name)",
      trigger: "Save employee",
      response: "Compute display_name for all pickers",
      severity: "High",
    },
    {
      id: "BR-HR-012",
      rule: "Only employees with status=active appear in cross-module employee pickers (جمع اشخاص, معاشات)",
      trigger: "Open employee dropdown in Items or Salaries",
      response: "Filter list; terminated and suspended excluded by default",
      severity: "Critical",
    },
    {
      id: "BR-HR-013",
      rule: "branch_id on employee drives branch filter in جمع اشخاص — only employees in selected branch listed",
      trigger: "Select branch on ENT-ITM-040",
      response: "Filter by employee.branch_id",
      severity: "Critical",
    },
    {
      id: "BR-HR-014",
      rule: "Person Document requires document_type, description, file, and start_date on every row",
      trigger: "Add document",
      response: "Block save if any required attachment field missing",
      severity: "Critical",
    },
    {
      id: "BR-HR-015",
      rule: "Each Person Document file: PDF, JPG, PNG; max 10 MB",
      trigger: "Upload file on ENT-HR-011",
      response: "Reject invalid format or oversized file",
      severity: "High",
    },
    {
      id: "BR-HR-016",
      rule: "When status=terminated, end_date is required",
      trigger: "Set status terminated",
      response: "Block until end_date provided",
      severity: "Critical",
    },
    {
      id: "BR-HR-017",
      rule: "Renewing a document of the same type should mark prior active row as superseded",
      trigger: "Add document where type matches existing active row",
      response: "Prompt to supersede; keep both files in history",
      severity: "Medium",
    },
    {
      id: "BR-HR-018",
      rule: "national_id unique when provided — duplicate tazkira numbers blocked",
      trigger: "Save employee",
      response: "Warn if another employee has same national_id",
      severity: "High",
    },
    {
      id: "BR-HR-024",
      rule: "position_id must reference an active Position (ENT-HR-012)",
      trigger: "Assign or transfer employee",
      response: "Block inactive positions for new assignments",
      severity: "High",
    },
    {
      id: "BR-HR-025",
      rule: "Assignment History must record at least one from/to change (branch, department, or position)",
      trigger: "Save transfer",
      response: "Block empty transfer with no field changed",
      severity: "Critical",
    },
    {
      id: "BR-HR-026",
      rule: "On transfer save, update employee branch_id, department_id, position_id to to_* values on effective_date",
      trigger: "Record assignment history",
      response: "Sync ENT-HR-010 current assignment",
      severity: "Critical",
    },
    {
      id: "BR-HR-027",
      rule: "highest_education_level on employee = max education_level across verified ENT-HR-014 rows",
      trigger: "Add or verify education",
      response: "Recompute read-only field on employee",
      severity: "Medium",
    },
    {
      id: "BR-HR-028",
      rule: "Employee education_level ordering: primary < secondary < diploma < bachelor < master < phd",
      trigger: "Compute highest education",
      response: "Use ordered enum for comparison",
      severity: "Medium",
    },
    {
      id: "BR-HR-029",
      rule: "Warn when employee highest_education_level is below position min_education_level",
      trigger: "Assign position or add education",
      response: "Show warning — does not block unless ENCC policy requires",
      severity: "Low",
    },
  ],
  permissionsMatrix: [
    { action: "Create / edit employees", archiveClerk: "—", executive: "R", deptStaff: "—", auditor: "—" },
    { action: "Maintain positions (بست)", archiveClerk: "—", executive: "R", deptStaff: "—", auditor: "—" },
    { action: "Record transfers & education", archiveClerk: "—", executive: "R", deptStaff: "—", auditor: "—" },
    { action: "Upload person documents", archiveClerk: "—", executive: "R", deptStaff: "—", auditor: "—" },
    { action: "Terminate employee", archiveClerk: "—", executive: "A", deptStaff: "—", auditor: "—" },
    { action: "View all employees & documents", archiveClerk: "—", executive: "R", deptStaff: "R*", auditor: "R" },
  ],
  reports: [
    {
      id: "RPT-HR-010",
      name: "Employee Register",
      purpose: "All employees with department, branch, position, status, hire date",
      filters: "Department, branch, status, employment_type, hire date range",
      columns: "employee_code, display_name, department, branch, position, employment_type, hire_date, highest_education, status",
      export: "PDF, Excel",
    },
    {
      id: "RPT-HR-011",
      name: "Person Documents by Employee",
      purpose: "All document rows per employee with type, dates, and file reference",
      filters: "Employee, document_type, status, expiry date range (expiring soon)",
      columns: "employee_code, display_name, document_type, description, start_date, expiry_date, document_number, status, file",
      export: "PDF, Excel",
    },
    {
      id: "RPT-HR-012",
      name: "Expiring Documents",
      purpose: "Contracts, licenses, and medical certs nearing expiry",
      filters: "document_type, days until expiry, branch, department",
      columns: "employee, document_type, description, expiry_date, days_remaining, phone",
      export: "PDF, Excel",
    },
    {
      id: "RPT-HR-013",
      name: "Position Register (بست)",
      purpose: "All defined positions with grade, department, capacity, and current headcount",
      filters: "Department, grade, is_active, min_education_level",
      columns: "position_code, title, title_dari, grade, department, min_education, max_headcount, current_count, is_active",
      export: "PDF, Excel",
    },
    {
      id: "RPT-HR-014",
      name: "Assignment History",
      purpose: "All branch, department, and position transfers",
      filters: "Employee, change_type, branch, department, effective date range",
      columns: "employee, change_type, from_branch, to_branch, from_department, to_department, from_position, to_position, effective_date, order_number",
      export: "PDF, Excel",
    },
    {
      id: "RPT-HR-017",
      name: "Employee Education Summary",
      purpose: "Education levels and institutions per employee",
      filters: "education_level, institution, branch, department, verified only",
      columns: "employee, education_level, field_of_study, institution, graduation_date, verified, file",
      export: "PDF, Excel",
    },
  ],
  validationRules: [
    { field: "first_name", rule: "Required", uiBehavior: "Text input" },
    { field: "father_name", rule: "Required", uiBehavior: "Text input" },
    { field: "department_id", rule: "Required reference", uiBehavior: "Department dropdown" },
    { field: "branch_id", rule: "Required reference", uiBehavior: "Branch dropdown" },
    { field: "position_id", rule: "Required reference to active Position (ENT-HR-012)", uiBehavior: "Position dropdown — بست" },
    { field: "hire_date", rule: "Required Hijri date", uiBehavior: "Date picker" },
    { field: "employment_type", rule: "Required enum", uiBehavior: "Dropdown" },
    { field: "status", rule: "Required enum", uiBehavior: "Dropdown" },
    {
      field: "document_type",
      rule: "Required on Person Document row",
      uiBehavior: "Dropdown — نوع سند",
    },
    {
      field: "description",
      rule: "Required on Person Document row",
      uiBehavior: "Text area — توضیحات",
    },
    {
      field: "file",
      rule: "Required on Person Document row; PDF, JPG, PNG; max 10 MB",
      uiBehavior: "File upload — فایل",
    },
    {
      field: "start_date",
      rule: "Required on Person Document row",
      uiBehavior: "Hijri date — تاریخ شروع",
    },
    {
      field: "education_level",
      rule: "Required on Employee Education row — primary | secondary | diploma | bachelor | master | phd | other",
      uiBehavior: "Dropdown — سطح تحصیلات",
    },
    {
      field: "title",
      rule: "Required on Position master",
      uiBehavior: "Text input — عنوان بست",
    },
  ],
  integrations: [
    {
      id: "INT-HR-010",
      direction: "out",
      module: "Items — Person Register (ENT-ITM-040)",
      data: "employee_id, display_name, branch_id, status=active",
      when: "Employee picker on جمع اشخاص",
      note: "Read-only consumer — person does not come from driver register",
    },
    {
      id: "INT-HR-011",
      direction: "out",
      module: "Salaries — Salary Payment (ENT-SAL-010)",
      data: "employee_id, display_name, position grade from ENT-HR-012, bank_account_ref, status",
      when: "Payroll employee selection",
      note: "Salary amounts defined in Salaries module",
    },
    {
      id: "INT-HR-012",
      direction: "in",
      module: "General Tables — Branch (ENT-OPR-G009), Department, Bank Account",
      data: "branch_id, department_id, bank_account_ref",
      when: "Employee create/edit",
      note: "References shared master data",
    },
  ],
  crossModuleNotes: [
    "ENT-HR-010 is the single employee master — Items جمع اشخاص and Salaries معاشات reference it, not driver register.",
    "Position master (ENT-HR-012) defines available بست — employees hold position_id; grade comes from position, not a separate employee field.",
    "Assignment History (ENT-HR-013) records every branch, department, and position move — current values on employee are always the latest effective assignment.",
    "Employee Education (ENT-HR-014) stores bachelor (لیسانس), master (ماجستیر), PhD (دکترا), diploma, etc. — highest_education_level on employee is computed.",
    "Leave requests are in section leave-requests (ENT-HR-015) — approved leave sets status=on_leave.",
    "Person Documents (ENT-HR-011) are HR personnel files — separate from education certificate files on ENT-HR-014.",
    "Active + branch filter drives all employee pickers; terminated employees stay on historical records.",
  ],
  deliverableChecklist: [
    { item: "Employee master fields — identity, assignment, contact, employment", done: true },
    { item: "Position master (بست) register", done: true },
    { item: "Assignment History — branch / department / position transfers", done: true },
    { item: "Employee Education — bachelor, master, PhD levels + certificate file", done: true },
    { item: "Person Documents table — type, description, file, dates, metadata", done: true },
    { item: "Leave requests section (ENT-HR-015)", done: true },
    { item: "Cross-module integration notes (Items, Salaries)", done: true },
    { item: "Detailed HR workflows with ENCC sign-off", done: false },
  ],
};
