import type { SectionDefinition } from "@/types/requirements";

export const leaveRequestsSection: SectionDefinition = {
  id: "leave-requests",
  name: "Leave Requests",
  nameDari: "درخواست‌های رخصتی",
  enableReview: true,
  description:
    "Register and track employee leave (رخصتی) — annual, sick, emergency, and other types. Linked to HR Employee Record (ENT-HR-010). Approved leave may set employee status to on_leave for the leave period.",
  status: "draft",
  currentTool: "Paper leave request forms and HR leave register",
  summary: [
    "Leave Request (ENT-HR-015) — one row per leave application",
    "Employee selected from HR master — not free text",
    "leave_type: annual | sick | emergency | unpaid | maternity | bereavement | other",
    "Start and end dates (Hijri); duration_days computed",
    "Workflow: draft → submitted → approved | rejected",
    "Optional attachment — leave application scan or medical note",
    "Approved leave updates employee status=on_leave for the covered period",
  ],
  precededBy: [{ moduleId: "hr", sectionId: "hr", label: "Employee master" }],
  followedBy: [],
  relatedSections: ["hr", "salaries"],
  roles: [
    {
      role: "Employee / Department Staff",
      location: "HQ or Branch",
      mainActions: "Submit leave request for self or department staff",
      approval: false,
      readOnly: false,
    },
    {
      role: "HR Clerk",
      location: "HQ — منابع بشری",
      mainActions: "Register leave on paper, enter requests, attach scans",
      approval: false,
      readOnly: false,
    },
    {
      role: "HR Manager",
      location: "HQ",
      mainActions: "Approve or reject leave requests",
      approval: true,
      readOnly: false,
    },
    {
      role: "Department Manager",
      location: "HQ — ریاست",
      mainActions: "Recommend or forward leave for HR approval",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View all leave history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-HR-015",
      name: "Leave Request",
      description:
        "Employee leave application — registered in HR and tracked through approval. Historical leave rows retained for reports and payroll (Salaries may deduct unpaid leave).",
      fields: [
        {
          name: "request_number",
          label: "Request Number",
          labelDari: "شماره درخواست",
          meaning: "System-generated unique leave request id",
          type: "text",
          required: true,
          example: "LV-0024/1405",
          rules: "Auto-generated; unique",
        },
        {
          name: "employee_id",
          label: "Employee",
          labelDari: "کارمند",
          meaning: "Reference → ENT-HR-010",
          type: "reference",
          required: true,
          example: "EMP-0045 — Mohammad بن رحیم",
          rules: "Active employees only; shows current branch and department",
        },
        {
          name: "leave_type",
          label: "Leave Type",
          labelDari: "نوع رخصتی",
          meaning: "annual | sick | emergency | unpaid | maternity | bereavement | other",
          type: "enum",
          required: true,
          example: "annual",
        },
        {
          name: "start_date",
          label: "Start Date",
          labelDari: "تاریخ شروع",
          meaning: "First day of leave — Hijri",
          type: "hijri_date",
          required: true,
          example: "1405/04/01",
        },
        {
          name: "end_date",
          label: "End Date",
          labelDari: "تاریخ ختم",
          meaning: "Last day of leave — Hijri; must be on or after start_date",
          type: "hijri_date",
          required: true,
          example: "1405/04/10",
        },
        {
          name: "duration_days",
          label: "Duration (Days)",
          labelDari: "مدت (روز)",
          meaning: "Inclusive calendar days between start and end — computed",
          type: "decimal",
          required: true,
          example: "10",
          rules: "Read-only; end_date − start_date + 1",
        },
        {
          name: "reason",
          label: "Reason",
          labelDari: "دلیل",
          meaning: "Why leave is requested",
          type: "longtext",
          required: true,
          example: "Annual family visit",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | submitted | approved | rejected | cancelled",
          type: "enum",
          required: true,
          example: "approved",
        },
        {
          name: "submitted_by",
          label: "Submitted By",
          labelDari: "ارسال شده توسط",
          meaning: "User who submitted the request",
          type: "reference",
          required: "conditional",
          example: "HR Clerk — Fatima",
          rules: "Required when status ≥ submitted",
        },
        {
          name: "submitted_at",
          label: "Submitted At",
          labelDari: "تاریخ ارسال",
          meaning: "When request was submitted for approval",
          type: "datetime",
          required: false,
          example: "1405/03/25 09:00",
        },
        {
          name: "approved_by",
          label: "Approved By",
          labelDari: "تأیید شده توسط",
          meaning: "HR Manager or delegated approver",
          type: "reference",
          required: "conditional",
          example: "HR Manager",
          rules: "Required when status=approved",
        },
        {
          name: "approved_at",
          label: "Approved At",
          labelDari: "تاریخ تأیید",
          meaning: "When leave was approved",
          type: "datetime",
          required: false,
          example: "1405/03/26 11:30",
        },
        {
          name: "rejection_reason",
          label: "Rejection Reason",
          labelDari: "دلیل رد",
          meaning: "Why leave was rejected",
          type: "longtext",
          required: "conditional",
          example: "Insufficient annual leave balance",
          rules: "Required when status=rejected",
        },
        {
          name: "attachment",
          label: "Attachment",
          labelDari: "ضمیمه",
          meaning: "Optional scan — leave form or medical certificate for sick leave",
          type: "file",
          required: false,
          example: "leave_request_0045.pdf",
          rules: "PDF, JPG, PNG; max 10 MB; recommended for sick leave",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Internal HR notes",
          type: "longtext",
          required: false,
          example: "Employee returned on 1405/04/11 — one day early",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-HR-015",
      name: "Register and approve leave",
      trigger: "Employee requests leave",
      startActor: "Department Staff or HR Clerk",
      endState: "Leave approved — employee on_leave for period",
      flowDiagram: "Create request → submit → HR/Dept manager approve → employee status on_leave",
      steps: [
        {
          step: 1,
          actor: "Clerk",
          action: "Create leave request",
          input: "employee_id, leave_type, start_date, end_date, reason",
          output: "ENT-HR-015 status=draft",
        },
        {
          step: 2,
          actor: "Clerk",
          action: "Attach document if needed",
          input: "attachment optional",
          output: "Scan on request",
        },
        {
          step: 3,
          actor: "Clerk",
          action: "Submit for approval",
          input: "status=submitted",
          output: "Awaiting approver",
        },
        {
          step: 4,
          actor: "HR Manager",
          action: "Approve or reject",
          input: "approved_by or rejection_reason",
          output: "status=approved | rejected",
        },
        {
          step: 5,
          actor: "System",
          action: "Update employee status",
          input: "Approved leave within date range",
          output: "ENT-HR-010 status=on_leave; revert to active after end_date",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-HR-019",
      rule: "end_date must be on or after start_date",
      trigger: "Save leave request",
      response: "Block invalid date range",
      severity: "Critical",
    },
    {
      id: "BR-HR-020",
      rule: "Overlapping approved leave for same employee blocked",
      trigger: "Approve leave",
      response: "Block if dates overlap another approved request",
      severity: "Critical",
    },
    {
      id: "BR-HR-021",
      rule: "When leave approved, set employee status=on_leave from start_date through end_date",
      trigger: "Approve leave",
      response: "Update ENT-HR-010; auto-revert to active day after end_date unless suspended/terminated",
      severity: "High",
    },
    {
      id: "BR-HR-022",
      rule: "Employees on_leave excluded from جمع اشخاص active picker by default",
      trigger: "Open employee dropdown in Items",
      response: "Filter status=active only",
      severity: "High",
    },
    {
      id: "BR-HR-023",
      rule: "Sick leave attachment recommended — required when leave_type=sick and duration > 3 days",
      trigger: "Submit sick leave",
      response: "Warn or block until attachment uploaded",
      severity: "Medium",
    },
  ],
  permissionsMatrix: [
    { action: "Create leave request", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "—" },
    { action: "Approve / reject leave", archiveClerk: "—", executive: "A", deptStaff: "—", auditor: "—" },
    { action: "View leave register", archiveClerk: "—", executive: "R", deptStaff: "R", auditor: "R" },
  ],
  reports: [
    {
      id: "RPT-HR-015",
      name: "Leave Register",
      purpose: "All leave requests with type, dates, status",
      filters: "Employee, branch, department, leave_type, status, date range",
      columns: "request_number, employee, leave_type, start_date, end_date, duration_days, status, approved_by",
      export: "PDF, Excel",
    },
    {
      id: "RPT-HR-016",
      name: "Employees Currently on Leave",
      purpose: "Who is on leave today",
      filters: "Branch, department, leave_type",
      columns: "employee, branch, department, leave_type, start_date, end_date, days_remaining",
      export: "PDF, Excel",
    },
  ],
  validationRules: [
    { field: "employee_id", rule: "Required reference to HR employee", uiBehavior: "Employee dropdown" },
    { field: "leave_type", rule: "Required enum", uiBehavior: "Dropdown — نوع رخصتی" },
    { field: "start_date", rule: "Required Hijri date", uiBehavior: "Date picker" },
    { field: "end_date", rule: "Required; ≥ start_date", uiBehavior: "Date picker" },
    { field: "reason", rule: "Required", uiBehavior: "Text area" },
  ],
  integrations: [
    {
      id: "INT-HR-015",
      direction: "in",
      module: "HR — Employee Record (ENT-HR-010)",
      data: "employee_id, branch_id, department_id, status",
      when: "Create leave request",
      note: "Employee picker from HR master",
    },
    {
      id: "INT-HR-016",
      direction: "out",
      module: "HR — Employee Record (ENT-HR-010)",
      data: "status=on_leave during approved leave period",
      when: "Leave approved",
      note: "Temporary status change",
    },
    {
      id: "INT-HR-017",
      direction: "out",
      module: "Salaries — Salary Payment (ENT-SAL-010)",
      data: "leave_type, duration_days, unpaid leave flag",
      when: "Payroll period includes leave",
      note: "Future — unpaid leave deductions",
    },
  ],
  crossModuleNotes: [
    "Leave requests are HR-only transactions — separate from Person Documents (ENT-HR-011).",
    "Approved leave sets employee on_leave; جمع اشخاص and other pickers use active staff only.",
    "Unpaid leave may affect Salaries — integration documented for future payroll rules.",
  ],
  deliverableChecklist: [
    { item: "Leave request fields and approval workflow", done: true },
    { item: "on_leave status integration with employee master", done: true },
    { item: "ENCC sign-off on leave types and approval chain", done: false },
  ],
};
