import type { SectionDefinition } from "@/types/requirements";

export const controlSection: SectionDefinition = {
  id: "control",
  name: "Control",
  nameDari: "کنترول",
  enableReview: true,
  description:
    "Control department (کنترول). Verifies purchase requests and Mali bank receipts before customer pays at bank. Central checkpoint — most workflow items pass through Control; additional control workflows will be added over time.",
  status: "draft",
  currentTool: "Manual verification against paper forms",
  summary: [
    "Receives requests after Mali prints bank receipts",
    "Verify request details match receipts before customer goes to bank",
    "Approve or return — records who checked and when",
    "Future: additional control workflows for rent, properties, and other sections (TBD)",
  ],
  precededBy: [
    { moduleId: "mali", sectionId: "mali", label: "Print Bank Receipts" },
  ],
  followedBy: [
    { moduleId: "mali", sectionId: "mali", label: "Verify Bank Payment" },
  ],
  relatedSections: ["operations", "mali", "sales", "execution-office"],
  roles: [
    {
      role: "Control Officer",
      location: "HQ — کنترول",
      mainActions: "Review requests and Mali receipts; approve or return before bank payment",
      approval: true,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View control approval trail",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-OPR-017",
      name: "Control Check Record",
      description: "Audit record of each control verification on a purchase request",
      fields: [
        {
          name: "purchase_request_id",
          label: "Purchase Request",
          labelDari: "درخواست",
          meaning: "Request being verified",
          type: "reference",
          required: true,
          example: "PR-1245/1405",
        },
        {
          name: "checked_by",
          label: "Checked By",
          labelDari: "بررسی شده توسط",
          meaning: "Control officer who performed the check",
          type: "reference",
          required: true,
          example: "Control Officer — Karim",
        },
        {
          name: "checked_at",
          label: "Check Date",
          labelDari: "تاریخ بررسی",
          meaning: "When control verification completed",
          type: "datetime",
          required: true,
          example: "1405/02/19 14:00",
        },
        {
          name: "decision",
          label: "Decision",
          labelDari: "نتیجه",
          meaning: "approved | rejected",
          type: "enum",
          required: true,
          example: "approved",
        },
        {
          name: "rejection_reason",
          label: "Rejection Reason",
          labelDari: "دلیل رد",
          meaning: "Required if rejected — why details or receipts are incorrect",
          type: "longtext",
          required: "conditional",
          example: "Wrong mining site on receipt",
        },
        {
          name: "notes",
          label: "Notes",
          labelDari: "یادداشت",
          meaning: "Optional control notes",
          type: "longtext",
          required: false,
          example: "Verified amounts match boss-approved prices",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-OPR-040",
      name: "Control check — purchase request",
      trigger: "Mali receipts generated (status: pending_control)",
      startActor: "Control Officer",
      endState: "Approved → customer may pay at bank (pending_payment) — or returned to Operations/Mali",
      flowDiagram: "Review request + Mali receipts → approve or reject → customer pays if approved",
      steps: [
        {
          step: 1,
          actor: "Control Officer",
          action: "Open request in Control queue with Mali-generated receipts",
          input: "Request data, product receipt PDF, weighing receipt PDF",
          output: "Control review screen",
        },
        {
          step: 2,
          actor: "Control Officer",
          action: "Verify customer, product, mine, quantities, and amounts match receipts",
          input: "Request + receipts + boss approval record",
          output: "Checklist complete",
        },
        {
          step: 3,
          actor: "Control Officer",
          action: "Approve or reject",
          input: "Verification result",
          output: "Control Check Record — status: pending_payment or control_rejected",
          decision: true,
          exception: "Reject → return to Operations; Mali may reprint if amounts changed",
        },
        {
          step: 4,
          actor: "Customer",
          action: "Take approved receipts to bank and pay",
          input: "Printed Mali receipts",
          output: "Bank payment completed — Mali uploads receipts next",
        },
      ],
    },
  ],
  statusLifecycles: [
    {
      entity: "Purchase Request",
      from: "pending_control",
      action: "approve",
      to: "pending_payment",
      actor: "Control Officer",
      notes: "Customer may go to bank",
    },
    {
      entity: "Purchase Request",
      from: "pending_control",
      action: "reject",
      to: "control_rejected",
      actor: "Control Officer",
      notes: "Return to Operations or Mali for correction",
    },
  ],
  businessRules: [
    {
      id: "BR-OPR-050",
      rule: "Control can only act on requests with Mali receipts generated",
      trigger: "Control open",
      response: "Block if status ≠ pending_control",
      severity: "Critical",
    },
    {
      id: "BR-OPR-051",
      rule: "Rejection requires reason note",
      trigger: "Reject",
      response: "Require rejection_reason",
      severity: "High",
    },
    {
      id: "BR-OPR-052",
      rule: "Control approval must record checked_by and checked_at",
      trigger: "Approve",
      response: "Require fields on Control Check Record",
      severity: "Critical",
    },
    {
      id: "BR-OPR-053",
      rule: "Customer cannot pay at bank until Control approves",
      trigger: "Bank payment",
      response: "Block Mali upload if control not approved",
      severity: "Critical",
    },
  ],
  permissionsMatrix: [
    { action: "View control queue", archiveClerk: "—", executive: "R", deptStaff: "R", auditor: "R" },
    { action: "Approve / reject control check", archiveClerk: "—", executive: "—", deptStaff: "A", auditor: "—" },
    { action: "Create customer", archiveClerk: "—", executive: "—", deptStaff: "—", auditor: "—" },
  ],
  reports: [
    {
      id: "RPT-OPR-040",
      name: "Control Check Register",
      purpose: "All control verifications with approver and decision",
      filters: "Hijri date range, decision, officer",
      columns: "request no., customer, checked by, date, decision, notes",
      export: "PDF, Excel",
    },
    {
      id: "RPT-OPR-041",
      name: "Pending Control Queue",
      purpose: "Requests awaiting control verification",
      filters: "Age in days, mine",
      columns: "request no., customer, Mali receipt date, age",
      export: "PDF",
    },
    {
      id: "RPT-OPR-042",
      name: "Control Rejections",
      purpose: "Rejected items and reasons — for process improvement",
      filters: "Date range, officer",
      columns: "request no., customer, reason, returned date",
      export: "PDF, Excel",
    },
  ],
  crossModuleNotes: [
    "Control is the central verification hub — most purchase and future payment workflows pass through here.",
    "Additional control workflows (rent, properties, other sections) to be added as those sections are documented.",
  ],
  deliverableChecklist: [
    { item: "Purchase control workflow documented", done: true },
    { item: "Control Check Record entity defined", done: true },
    { item: "Future control workflows placeholder", done: "partial" },
    { item: "ENCC sign-off", done: false },
  ],
};
