import type { SectionDefinition } from "@/types/requirements";

export const fulfillStorageRequestSection: SectionDefinition = {
  id: "fulfill-storage-request",
  name: "Review & Fulfill Storage Request",
  nameDari: "بررسی و توزیع درخواست تحویلخانه",
  enableReview: true,
  description:
    "Storage / Warehouse department (تحویلخانه) receives boss-approved requisitions. Staff check whether the item is in stock. If available — create a distribution form and hand items to the requester. If not available — forward to Procurement to purchase, then distribute after delivery.",
  status: "draft",
  currentTool: "Manual stock ledger and paper distribution slips",
  summary: [
    "Receive approved storage requests from any department",
    "Check stock availability against warehouse inventory",
    "If in stock → create distribution form and issue to requester",
    "If not in stock → route to Procurement department to buy",
    "After procurement delivery → create distribution form and issue",
  ],
  precededBy: [
    {
      moduleId: "operations",
      sectionId: "request-item-from-storage",
      label: "Request Item from Storage",
    },
  ],
  followedBy: [
    {
      moduleId: "storage",
      sectionId: "create-distribution-form",
      label: "Create Distribution Form",
    },
    {
      moduleId: "procurement",
      sectionId: "procure-item",
      label: "Procure Unavailable Item",
    },
  ],
  relatedSections: ["request-item-from-storage", "create-distribution-form", "procure-item"],
  entities: [
    {
      id: "ENT-STR-010",
      name: "Storage Fulfillment Review",
      description: "Warehouse decision on an approved storage request — accept, reject, or route to procurement.",
      fields: [
        {
          name: "storage_request_id",
          label: "Storage Request",
          labelDari: "درخواست تحویلخانه",
          meaning: "Linked approved storage item request",
          type: "reference",
          required: true,
          example: "SR-0042/1405",
        },
        {
          name: "availability",
          label: "Availability",
          labelDari: "موجودی",
          meaning: "in_stock | not_in_stock",
          type: "enum",
          required: true,
          example: "in_stock",
        },
        {
          name: "quantity_available",
          label: "Quantity Available",
          labelDari: "مقدار موجود",
          meaning: "Stock on hand at review time",
          type: "decimal",
          required: "conditional",
          example: "25",
        },
        {
          name: "reviewed_by",
          label: "Reviewed By",
          labelDari: "بررسی شده توسط",
          meaning: "Storage clerk who checked stock",
          type: "reference",
          required: true,
          example: "Warehouse Clerk",
        },
        {
          name: "reviewed_at",
          label: "Review Date",
          labelDari: "تاریخ بررسی",
          meaning: "When stock check completed",
          type: "datetime",
          required: true,
          example: "1405/02/20 09:00",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "accepted | rejected | pending_procurement | ready_to_distribute",
          type: "enum",
          required: true,
          example: "accepted",
        },
        {
          name: "rejection_reason",
          label: "Rejection Reason",
          labelDari: "دلیل رد",
          meaning: "If Storage rejects (e.g. invalid request)",
          type: "longtext",
          required: "conditional",
          example: "Item discontinued",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-STR-010",
      name: "Storage availability check",
      trigger: "Boss-approved storage request arrives in Storage queue",
      startActor: "Storage / Warehouse clerk",
      endState: "Distribution form created OR sent to Procurement",
      flowDiagram: "Review → check stock → distribute OR procurement",
      steps: [
        {
          step: 1,
          actor: "Storage clerk",
          action: "Open approved request; verify details",
          input: "Storage Item Request",
          output: "Review record started",
        },
        {
          step: 2,
          actor: "Storage clerk",
          action: "Check warehouse stock for product and quantity",
          input: "Inventory ledger",
          output: "availability: in_stock or not_in_stock",
          decision: true,
        },
        {
          step: 3,
          actor: "Storage clerk",
          action: "If in stock — mark accepted, proceed to distribution form",
          input: "Sufficient quantity",
          output: "status: ready_to_distribute",
        },
        {
          step: 4,
          actor: "Storage clerk",
          action: "If not in stock — forward to Procurement",
          input: "Insufficient or zero stock",
          output: "status: pending_procurement — Procurement queue",
        },
        {
          step: 5,
          actor: "Storage clerk",
          action: "If request invalid — reject with reason",
          input: "Invalid item or policy block",
          output: "status: rejected",
          exception: "Requester notified",
        },
      ],
    },
  ],
  statusLifecycles: [
    {
      entity: "Storage Request",
      from: "pending_warehouse",
      action: "accept — in stock",
      to: "ready_to_distribute",
      actor: "Storage clerk",
    },
    {
      entity: "Storage Request",
      from: "pending_warehouse",
      action: "forward to procurement",
      to: "pending_procurement",
      actor: "Storage clerk",
    },
    {
      entity: "Storage Request",
      from: "pending_warehouse",
      action: "reject",
      to: "rejected",
      actor: "Storage clerk",
    },
  ],
  businessRules: [
    {
      id: "BR-STR-010",
      rule: "Only Storage department can perform stock check on storage requests",
      trigger: "Review",
      response: "Restrict to Storage role",
      severity: "Critical",
    },
    {
      id: "BR-STR-011",
      rule: "Not-in-stock must route to Procurement — not rejected automatically",
      trigger: "Stock check",
      response: "Set pending_procurement",
      severity: "High",
    },
  ],
  roles: [
    {
      role: "Storage / Warehouse Clerk",
      location: "HQ — تحویلخانه",
      mainActions: "Review requests, check stock, route to distribution or procurement",
      approval: false,
      readOnly: false,
    },
  ],
  deliverableChecklist: [
    { item: "Storage fulfillment workflow documented", done: true },
    { item: "Procurement handoff defined", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};

export const createDistributionFormSection: SectionDefinition = {
  id: "create-distribution-form",
  name: "Create Distribution Form",
  nameDari: "فورم توزیع",
  enableReview: true,
  description:
    "After stock is confirmed (from warehouse or after Procurement delivery), Storage creates a distribution form and issues the item to the person who requested it. Records who received what, when, and quantity distributed.",
  status: "draft",
  currentTool: "Paper distribution slip signed by recipient",
  summary: [
    "Create distribution form linked to approved storage request",
    "Record recipient name, department, quantity issued, and date",
    "Recipient signs or confirms receipt — closes the request as distributed",
    "Also used after Procurement delivers purchased items to Storage",
  ],
  precededBy: [
    {
      moduleId: "storage",
      sectionId: "fulfill-storage-request",
      label: "Review & Fulfill Storage Request",
    },
    {
      moduleId: "procurement",
      sectionId: "procure-item",
      label: "Procure Unavailable Item",
    },
  ],
  relatedSections: ["fulfill-storage-request", "procure-item"],
  entities: [
    {
      id: "ENT-STR-011",
      name: "Distribution Form (Storage)",
      description: "Issuance record when Storage hands items to the requester.",
      fields: [
        {
          name: "distribution_number",
          label: "Distribution Number",
          labelDari: "شماره توزیع",
          meaning: "Auto-generated on create",
          type: "text",
          required: true,
          example: "SD-0018/1405",
        },
        {
          name: "storage_request_id",
          label: "Storage Request",
          labelDari: "درخواست تحویلخانه",
          meaning: "Original requisition",
          type: "reference",
          required: true,
          example: "SR-0042/1405",
        },
        {
          name: "recipient_name",
          label: "Recipient Name",
          labelDari: "نام گیرنده",
          meaning: "Person receiving the items",
          type: "text",
          required: true,
          example: "Ahmad Khan",
        },
        {
          name: "recipient_department_id",
          label: "Recipient Department",
          labelDari: "ریاست گیرنده",
          meaning: "Department of the recipient",
          type: "reference",
          required: true,
          example: "Control Department",
        },
        {
          name: "product_name",
          label: "Product",
          labelDari: "جنس",
          meaning: "Copied from request",
          type: "text",
          required: true,
          example: "A4 Paper Ream",
        },
        {
          name: "quantity_distributed",
          label: "Quantity Distributed",
          labelDari: "مقدار توزیع شده",
          meaning: "Amount issued",
          type: "decimal",
          required: true,
          example: "10",
        },
        {
          name: "unit",
          label: "Unit",
          labelDari: "واحد",
          meaning: "Unit of measure",
          type: "text",
          required: true,
          example: "box",
        },
        {
          name: "distributed_at",
          label: "Distribution Date",
          labelDari: "تاریخ توزیع",
          meaning: "Hijri date of issuance",
          type: "hijri_date",
          required: true,
          example: "1405/02/21",
        },
        {
          name: "issued_by",
          label: "Issued By",
          labelDari: "توزیع شده توسط",
          meaning: "Storage clerk who created the form",
          type: "reference",
          required: true,
          example: "Warehouse Clerk",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | issued | distributed",
          type: "enum",
          required: true,
          example: "distributed",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-STR-011",
      name: "Issue items to requester",
      trigger: "Request marked ready_to_distribute or procurement delivery received",
      startActor: "Storage clerk",
      endState: "status: distributed — request closed",
      steps: [
        {
          step: 1,
          actor: "Storage clerk",
          action: "Create distribution form from approved request",
          input: "Storage request + stock",
          output: "Distribution draft with auto number",
        },
        {
          step: 2,
          actor: "Storage clerk",
          action: "Hand items to recipient; record recipient and quantity",
          input: "Physical items",
          output: "status: distributed",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-STR-020",
      rule: "Distribution quantity cannot exceed approved request quantity",
      trigger: "Save distribution",
      response: "Block over-issue",
      severity: "Critical",
    },
  ],
  roles: [
    {
      role: "Storage / Warehouse Clerk",
      location: "HQ — تحویلخانه",
      mainActions: "Create distribution forms and issue items",
      approval: false,
      readOnly: false,
    },
  ],
  deliverableChecklist: [
    { item: "Distribution form fields documented", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
