import type { SectionDefinition } from "@/types/requirements";

export const salesFormSection: SectionDefinition = {
  id: "sales-form",
  name: "Issue Sales Form & Send to MINS",
  nameDari: "صادر کردن فورم فروشات",
  enableReview: true,
  description:
    "Generate the final sales form after Mali verifies payment. All fields auto-fill from the purchase request and verified receipts, then the form is sent to MINS.",
  status: "draft",
  currentTool: "Manual sales forms",
  summary: [
    "Auto-generated unique form number and date",
    "Customer, product, mine, amounts, and approvers filled from prior steps",
    "Sent to MINS when complete — Sales cannot create customers",
  ],
  precededBy: [
    {
      moduleId: "mali",
      sectionId: "mali",
      label: "Verify Bank Payment",
    },
    {
      moduleId: "control",
      sectionId: "control",
      label: "Control Check",
    },
  ],
  followedBy: [
    {
      moduleId: "sales",
      sectionId: "sales-reports",
      label: "Sales Reports",
    },
  ],
  relatedSections: ["operations", "mali", "control"],
  roles: [
    {
      role: "Sales Clerk",
      location: "HQ — فروشات",
      mainActions: "Issue sales forms and send to MINS",
      approval: false,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View issued sales forms",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-OPR-018",
      name: "Sales Form",
      description: "Final sales department form — generated after payment verified",
      fields: [
        {
          name: "sales_form_number",
          label: "Sales Form Number",
          labelDari: "شماره فورم فروشات",
          meaning: "Auto-generated unique number",
          type: "text",
          required: true,
          example: "SF-789/1405",
          rules: "Auto-generated, unique, sequential per year",
        },
        {
          name: "sales_form_date",
          label: "Sales Form Date",
          labelDari: "تاریخ فورم",
          meaning: "Date form issued",
          type: "date",
          required: true,
          example: "1405/02/20",
        },
        {
          name: "purchase_request_id",
          label: "Purchase Request",
          labelDari: "درخواست",
          meaning: "Source purchase request",
          type: "reference",
          required: true,
          example: "PR-1245/1405",
        },
        {
          name: "customer_id",
          label: "Customer",
          labelDari: "مشتری",
          meaning: "Read-only from request — Sales cannot create customers",
          type: "reference",
          required: true,
          example: "CUS-004521 — احمد بن محمد",
        },
        {
          name: "product_category_id",
          label: "Product Category",
          labelDari: "جنس",
          meaning: "Read-only from request",
          type: "reference",
          required: true,
          example: "Coal",
        },
        {
          name: "product_type_id",
          label: "Product Type",
          labelDari: "نوع",
          meaning: "Read-only from request",
          type: "reference",
          required: true,
          example: "Grade A Coal",
        },
        {
          name: "mining_site_id",
          label: "Mining Site",
          labelDari: "معدن",
          meaning: "Read-only from request",
          type: "reference",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "quantity",
          label: "Quantity",
          labelDari: "مقدار",
          meaning: "Read-only from request",
          type: "decimal",
          required: true,
          example: "50",
        },
        {
          name: "grand_total",
          label: "Grand Total",
          labelDari: "مجموع کل",
          meaning: "Read-only from request",
          type: "decimal",
          required: true,
          example: "425500",
        },
        {
          name: "bank_receipt_numbers",
          label: "Bank Receipt Numbers",
          labelDari: "شماره رسیدهای بانک",
          meaning: "Auto-filled from verified Uploaded Bank Receipts",
          type: "text",
          required: true,
          example: "BR-987654, BR-987655",
        },
        {
          name: "tarafa_numbers",
          label: "Tarafa Numbers",
          labelDari: "شماره تعرفه",
          meaning: "Auto-filled from verified receipts",
          type: "text",
          required: true,
          example: "T-445566, T-445567",
        },
        {
          name: "approved_by_boss",
          label: "Boss Approver",
          labelDari: "تأیید مدیر",
          meaning: "From request approved_by",
          type: "reference",
          required: true,
          example: "Commercial Manager",
        },
        {
          name: "control_checked_by",
          label: "Control Checker",
          labelDari: "بررسی کنترول",
          meaning: "From Control Check Record",
          type: "reference",
          required: true,
          example: "Control Officer — Karim",
        },
        {
          name: "payment_verified_by",
          label: "Payment Verified By",
          labelDari: "تأیید پرداخت",
          meaning: "From Mali uploaded receipt verification",
          type: "reference",
          required: true,
          example: "Mali Clerk — Hassan",
        },
        {
          name: "sales_form_file",
          label: "Sales Form PDF",
          labelDari: "فورم فروشات",
          meaning: "Generated PDF — layout TBD from ENCC sample",
          type: "file",
          required: true,
          example: "sales_form_SF-789.pdf",
        },
        {
          name: "sent_to_mins",
          label: "Sent to MINS",
          labelDari: "ارسال به معادن",
          meaning: "True when form published to MINS module",
          type: "boolean",
          required: true,
          example: "true",
        },
        {
          name: "sent_to_mins_at",
          label: "Sent to MINS Date",
          labelDari: "تاریخ ارسال",
          meaning: "When form was sent to MINS",
          type: "datetime",
          required: "conditional",
          example: "1405/02/20 10:00",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-OPR-050",
      name: "Issue sales form and send to MINS",
      trigger: "All bank receipts verified (status: payment_verified)",
      startActor: "Sales Clerk",
      endState: "Sales form issued and sent to MINS — status: complete",
      flowDiagram: "Open verified request → generate form → auto-fill → send to MINS",
      steps: [
        {
          step: 1,
          actor: "Sales Clerk",
          action: "Open payment-verified request in Sales queue",
          input: "Request + verified receipts + control record",
          output: "Form preview with auto-filled fields",
        },
        {
          step: 2,
          actor: "Sales Clerk",
          action: "Generate sales form PDF with unique number",
          input: "All inherited data read-only",
          output: "Sales form PDF — status: sales_issued",
        },
        {
          step: 3,
          actor: "System",
          action: "Send sales form to MINS module",
          input: "Completed sales form + request data",
          output: "sent_to_mins = true — status: complete",
        },
      ],
    },
  ],
  statusLifecycles: [
    {
      entity: "Purchase Request",
      from: "payment_verified",
      action: "issue sales form",
      to: "sales_issued",
      actor: "Sales Clerk",
    },
    {
      entity: "Purchase Request",
      from: "sales_issued",
      action: "send to MINS",
      to: "complete",
      actor: "System",
    },
  ],
  businessRules: [
    {
      id: "BR-OPR-060",
      rule: "Sales cannot create customers — read-only from request",
      trigger: "Customer field",
      response: "Hide + button",
      severity: "Critical",
    },
    {
      id: "BR-OPR-061",
      rule: "Sales form cannot be issued until payment_verified",
      trigger: "Issue form",
      response: "Block",
      severity: "Critical",
    },
    {
      id: "BR-OPR-062",
      rule: "All form fields auto-filled — no manual override of core data",
      trigger: "Generate form",
      response: "Read-only inherited fields",
      severity: "High",
    },
    {
      id: "BR-OPR-063",
      rule: "Sales form must be sent to MINS on completion",
      trigger: "Issue form",
      response: "Auto-push to MINS",
      severity: "High",
    },
  ],
  permissionsMatrix: [
    { action: "View sales queue", archiveClerk: "—", executive: "R", deptStaff: "R", auditor: "R" },
    { action: "Issue sales form", archiveClerk: "—", executive: "—", deptStaff: "C", auditor: "—" },
  ],
  validationRules: [
    {
      field: "sales_form_number",
      rule: "Auto-generated; read-only",
      uiBehavior: "Shown on PDF and register",
    },
  ],
  integrations: [
    {
      id: "INT-OPR-050",
      direction: "out",
      module: "MINS — Mines",
      data: "Sales form: mine, product, quantity, customer, form number, amounts",
      when: "On sales form issued",
      note: "Mine site receives order allocation",
    },
  ],
  deliverableChecklist: [
    { item: "Sales form workflow documented", done: true },
    { item: "Sales form PDF sample from ENCC", done: false },
    { item: "ENCC sign-off", done: false },
  ],
};
