import type { SectionDefinition } from "@/types/requirements";

export const generalTablesSection: SectionDefinition = {
  id: "general-tables",
  name: "General Tables",
  enableReview: true,
  description:
    "Module-wide reference data shared across OPR sections and other ENCC modules. Maintained centrally — Execution Office, rent management, and future sections reference these tables rather than duplicating definitions.",
  status: "draft",
  summary: [
    "Central master data: customers, product categories, product types, mining sites, bank accounts, branches, property types, procurement contract types",
    "Branch table — id, name, status; Property Type — dynamic admin list for Properties module",
    "Bank receipt types and uploaded bank receipt records — reusable for purchases, rent, and other payments",
    "Weighing rate (ویگن) configurable — default 10 AFN per ton",
    "All sections link here; changes apply immediately to new transactions",
  ],
  relatedSections: ["execution-office", "archive"],
  roles: [
    {
      role: "Master Data Admin",
      location: "HQ",
      mainActions: "Create, edit, deactivate all general table records",
      approval: false,
      readOnly: false,
    },
    {
      role: "Section Clerk",
      location: "HQ — any section",
      mainActions: "Read master data; add customer inline via + button where supported",
      approval: false,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "View all master data and change history",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-OPR-G001",
      name: "Customer",
      description:
        "Registered person or buyer. Used in Execution Office and other sections. Searchable by name; quick add via + button.",
      fields: [
        {
          name: "customer_code",
          label: "Customer Code",
          labelDari: "کود مشتری",
          meaning: "System-generated unique identifier for fast lookup",
          type: "text",
          required: true,
          example: "CUS-004521",
          rules: "Auto-generated, unique",
        },
        {
          name: "first_name",
          label: "First Name",
          labelDari: "نام",
          meaning: "Customer given name",
          type: "text",
          required: true,
          example: "احمد",
        },
        {
          name: "father_name",
          label: "Father Name",
          labelDari: "نام پدر",
          meaning: "Patronymic — primary search key together with first name",
          type: "text",
          required: true,
          example: "محمد",
        },
        {
          name: "display_name",
          label: "Display Name",
          labelDari: "نام نمایشی",
          meaning: "Auto: first_name + father_name — shown in search results and dropdowns",
          type: "text",
          required: true,
          example: "احمد بن محمد",
          rules: "System-generated; used for search",
        },
        {
          name: "phone",
          label: "Phone",
          labelDari: "شماره تماس",
          meaning: "Optional secondary search key",
          type: "text",
          required: false,
          example: "0700123456",
        },
        {
          name: "national_id",
          label: "National ID / Tazkira",
          labelDari: "تذکره",
          meaning: "Identity document number if available",
          type: "text",
          required: false,
          example: "1234567",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Inactive customers hidden from selection but kept on historical records",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-OPR-G002",
      name: "Product Category",
      description: "General product group — coal, wood, or other. Dynamic admin table.",
      fields: [
        {
          name: "name",
          label: "Category Name",
          labelDari: "نام جنس",
          meaning: "General type name e.g. Coal, Wood, Charcoal",
          type: "text",
          required: true,
          example: "Coal / ذغال",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Only active categories shown on new requests",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-OPR-G003",
      name: "Product Type",
      description:
        "Specific variant under a category. Carries a default unit price — copied (not linked) to each request so seasonal price changes are tracked per transaction.",
      fields: [
        {
          name: "product_category_id",
          label: "Product Category",
          labelDari: "جنس",
          meaning: "Parent category (coal, wood, etc.)",
          type: "reference",
          required: true,
          example: "Coal",
        },
        {
          name: "name",
          label: "Type Name",
          labelDari: "نوع",
          meaning: "Specific product variant e.g. Grade A Coal, Grade B Coal",
          type: "text",
          required: true,
          example: "Grade A / درجه اول",
        },
        {
          name: "default_unit_price",
          label: "Default Unit Price",
          labelDari: "قیمت پیش‌فرض",
          meaning:
            "Current standard price — copied to new requests as editable snapshot; update here when seasonal prices change",
          type: "decimal",
          required: true,
          example: "8500 AFN/ton",
        },
        {
          name: "unit",
          label: "Unit of Measure",
          labelDari: "واحد",
          meaning: "Ton, cubic meter, etc.",
          type: "text",
          required: true,
          example: "ton",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Only active types shown when category selected",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-OPR-G004",
      name: "Mining Site",
      description: "ENCC mine or extraction site — shared with MINS module",
      fields: [
        {
          name: "name",
          label: "Site Name",
          labelDari: "نام معدن",
          meaning: "Mine or site name",
          type: "text",
          required: true,
          example: "Karkar Mine",
        },
        {
          name: "code",
          label: "Site Code",
          labelDari: "کود",
          meaning: "Short code for reports and MINS integration",
          type: "text",
          required: true,
          example: "KRK-01",
        },
        {
          name: "location",
          label: "Location",
          labelDari: "موقعیت",
          meaning: "Province / district",
          type: "text",
          required: false,
          example: "Baghlan",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Only active sites available for selection",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-OPR-G005",
      name: "Bank Account",
      description:
        "ENCC bank accounts — general table for all sections. Execution Office uses product and weighing accounts; rent and other sections use other accounts from the same table.",
      fields: [
        {
          name: "account_name",
          label: "Account Name",
          labelDari: "نام حساب",
          meaning: "Name printed on bank payment receipts",
          type: "text",
          required: true,
          example: "ENCC Coal Sales Account",
        },
        {
          name: "account_number",
          label: "Account Number",
          labelDari: "شماره حساب",
          meaning: "Bank account number for customer payment",
          type: "text",
          required: true,
          example: "1234567890",
        },
        {
          name: "bank_name",
          label: "Bank Name",
          labelDari: "نام بانک",
          meaning: "Receiving bank",
          type: "text",
          required: true,
          example: "Da Afghanistan Bank",
        },
        {
          name: "usage_tag",
          label: "Usage Tag",
          labelDari: "کاربرد",
          meaning:
            "Free-text or enum tag for which workflows use this account — e.g. product, weighing, rent, other",
          type: "text",
          required: false,
          example: "product",
          rules: "product | weighing | rent | other — multiple accounts allowed",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Active accounts available for receipt generation",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-OPR-G006",
      name: "Weighing Rate",
      description:
        "Configurable weighing (ویگن) fee — default 10 AFN per ton. Copied to each purchase request as editable snapshot.",
      fields: [
        {
          name: "rate_per_ton",
          label: "Rate per Ton",
          labelDari: "نرخ به ازای تن",
          meaning: "Current weighing fee per ton in AFN — default 10",
          type: "decimal",
          required: true,
          example: "10",
        },
        {
          name: "effective_from",
          label: "Effective From",
          labelDari: "از تاریخ",
          meaning: "Date this rate applies from — audit trail for rate changes",
          type: "date",
          required: true,
          example: "1405/01/01",
        },
        {
          name: "is_current",
          label: "Current Rate",
          labelDari: "نرخ فعلی",
          meaning: "Only one current rate — copied to new requests",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-OPR-G007",
      name: "Bank Receipt Type",
      description:
        "Classification for uploaded bank receipts — reusable across sections (purchase, rent, etc.)",
      fields: [
        {
          name: "name",
          label: "Type Name",
          labelDari: "نوع رسید",
          meaning: "e.g. Product Purchase, Weighing, Rent, Other",
          type: "text",
          required: true,
          example: "Product Purchase",
        },
        {
          name: "code",
          label: "Code",
          labelDari: "کود",
          meaning: "Short code for filtering and reports",
          type: "text",
          required: true,
          example: "purchase",
          rules: "purchase | weighing | rent | other",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Only active types shown when uploading receipts",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-OPR-G008",
      name: "Uploaded Bank Receipt",
      description:
        "Separate record for each bank receipt scan — linked to purchase requests, rent payments, or other transactions. Shared table across sections.",
      fields: [
        {
          name: "receipt_number",
          label: "Receipt Number",
          labelDari: "شماره رسید",
          meaning: "Number printed on the bank receipt",
          type: "text",
          required: true,
          example: "BR-987654",
        },
        {
          name: "receipt_date",
          label: "Receipt Date",
          labelDari: "تاریخ رسید",
          meaning: "Date on the bank receipt",
          type: "date",
          required: true,
          example: "1405/02/20",
        },
        {
          name: "tarafa_number",
          label: "Tarafa Number",
          labelDari: "شماره تعرفه",
          meaning: "Tarafa reference number from the bank receipt",
          type: "text",
          required: true,
          example: "T-445566",
        },
        {
          name: "file",
          label: "Receipt File",
          labelDari: "فایل رسید",
          meaning: "Scan of the bank receipt given to customer after payment",
          type: "file",
          required: true,
          example: "bank_receipt_scan.pdf",
        },
        {
          name: "receipt_type_id",
          label: "Receipt Type",
          labelDari: "نوع",
          meaning: "Classification — purchase, weighing, rent, etc.",
          type: "reference",
          required: true,
          example: "Product Purchase",
        },
        {
          name: "linked_record_type",
          label: "Linked Record Type",
          labelDari: "نوع سند مرتبط",
          meaning: "What this receipt belongs to — purchase_request, rent_contract, etc.",
          type: "text",
          required: false,
          example: "purchase_request",
        },
        {
          name: "linked_record_id",
          label: "Linked Record ID",
          labelDari: "شناسه سند",
          meaning: "Foreign key to the parent transaction",
          type: "reference",
          required: false,
          example: "PR-1245/1405",
        },
        {
          name: "approved_by",
          label: "Approved By",
          labelDari: "تأیید شده توسط",
          meaning: "Staff who verified this receipt against bank records",
          type: "reference",
          required: "conditional",
          example: "Mali Clerk — Hassan",
        },
        {
          name: "approved_at",
          label: "Approved Date",
          labelDari: "تاریخ تأیید",
          meaning: "When receipt verification was completed",
          type: "datetime",
          required: "conditional",
          example: "1405/02/20 09:15",
        },
      ],
    },
    {
      id: "ENT-OPR-G009",
      name: "Branch",
      description:
        "ENCC branch or regional office — minimal master table. Referenced by HR (employee assignment), Items (جمع اشخاص), Drivers, and Properties (managing branch).",
      fields: [
        {
          name: "name",
          label: "Name",
          labelDari: "نام",
          meaning: "Official branch name",
          type: "text",
          required: true,
          example: "Kabul HQ Branch",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | inactive",
          type: "enum",
          required: true,
          example: "active",
          rules: "Only active branches shown in cross-module dropdowns",
        },
      ],
    },
    {
      id: "ENT-OPR-G010",
      name: "Property Type",
      description:
        "Dynamic admin table for property categories — warehouse, land, office, residential, etc. Referenced by Properties module (ENT-PROP-020). Admin can add as many types as needed.",
      fields: [
        {
          name: "name",
          label: "Type Name",
          labelDari: "نام نوع",
          meaning: "Property category name e.g. Warehouse, Land, Office",
          type: "text",
          required: true,
          example: "Warehouse / گدام",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Only active types shown when registering properties",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
    {
      id: "ENT-OPR-G011",
      name: "Procurement Contract Type",
      description:
        "Dynamic admin table for procurement and project categories — items, services, construction, stationery, electrical, etc. Shared by Procurement Projects, Small Procurement, and other modules.",
      fields: [
        {
          name: "name",
          label: "Type Name",
          labelDari: "نام نوع",
          meaning: "Category name e.g. Items, Services, Construction, Stationery, Electrical",
          type: "text",
          required: true,
          example: "Construction / ساختمانی",
        },
        {
          name: "is_active",
          label: "Active",
          labelDari: "فعال",
          meaning: "Only active types shown on new projects and procurements",
          type: "boolean",
          required: true,
          example: "true",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-OPR-G001",
      name: "Maintain general tables",
      trigger: "Admin adds or updates shared reference data",
      startActor: "Master Data Admin",
      endState: "Updated table — available on next transaction in any linked section",
      flowDiagram: "Open general table → Add / edit / deactivate → Save → Audit log",
      steps: [
        {
          step: 1,
          actor: "Master Data Admin",
          action: "Manage product categories and types (with default prices)",
          input: "Category name, type name, default price, unit",
          output: "Types available in Execution Office; price copied to new requests",
        },
        {
          step: 2,
          actor: "Master Data Admin",
          action: "Manage mining sites and bank accounts",
          input: "Site details; account name, number, bank, usage tag",
          output: "Sites synced to MINS; accounts used on Mali-generated receipts",
        },
        {
          step: 3,
          actor: "Master Data Admin",
          action: "Update weighing rate when fee changes",
          input: "New rate per ton, effective date",
          output: "New current rate; copied to new purchase requests",
        },
        {
          step: 4,
          actor: "Master Data Admin",
          action: "Manage bank receipt types",
          input: "Type name and code (purchase, weighing, rent, other)",
          output: "Types available when uploading receipts in any section",
        },
        {
          step: 5,
          actor: "Section Clerk",
          action: "Add customer via + button on request form",
          input: "First name + father name minimum",
          output: "New customer in general table; immediately selectable",
        },
        {
          step: 6,
          actor: "Master Data Admin",
          action: "Manage branches",
          input: "Branch name, status (active | inactive)",
          output: "Branches available in HR, Items, Drivers, and Properties modules",
        },
        {
          step: 7,
          actor: "Master Data Admin",
          action: "Manage property types",
          input: "Type name, is_active",
          output: "Types available in Properties register dropdown",
        },
        {
          step: 8,
          actor: "Master Data Admin",
          action: "Manage procurement contract types",
          input: "Type name, is_active",
          output: "Types available in Projects and Small Procurement",
        },
      ],
    },
  ],
  businessRules: [
    {
      id: "BR-OPR-G001",
      rule: "Customer display_name must be unique per first_name + father_name combination",
      trigger: "Create customer",
      response: "Warn if duplicate; allow if confirmed same person",
      severity: "High",
    },
    {
      id: "BR-OPR-G002",
      rule: "Product type default_unit_price is a snapshot source only — each request stores its own editable copy",
      trigger: "Type selection on request",
      response: "Copy price to request; do not live-link",
      severity: "Critical",
    },
    {
      id: "BR-OPR-G003",
      rule: "Only one weighing rate may have is_current = true",
      trigger: "Set current rate",
      response: "Auto-deactivate previous current rate",
      severity: "Critical",
    },
    {
      id: "BR-OPR-G004",
      rule: "Deactivated records hidden from new transactions but preserved on historical records",
      trigger: "Deactivate",
      response: "Soft delete (is_active=false)",
      severity: "Medium",
    },
    {
      id: "BR-OPR-G005",
      rule: "Uploaded bank receipt requires number, date, Tarafa number, file, and type",
      trigger: "Create receipt record",
      response: "Block if any missing",
      severity: "Critical",
    },
    {
      id: "BR-OPR-G007",
      rule: "Only Operations department can create customers via + button — Sales and other departments read-only",
      trigger: "Create customer from form",
      response: "Block non-Operations roles",
      severity: "Critical",
    },
    {
      id: "BR-OPR-G008",
      rule: "Branch name required; status active or inactive only",
      trigger: "Create or edit branch",
      response: "Block if name empty; inactive branches hidden from new assignments",
      severity: "High",
    },
    {
      id: "BR-OPR-G009",
      rule: "Property type name required; inactive types hidden from new property registration",
      trigger: "Create or edit property type",
      response: "Soft delete via is_active=false",
      severity: "Medium",
    },
    {
      id: "BR-OPR-G010",
      rule: "Procurement contract type name required; inactive types hidden from new projects and procurements",
      trigger: "Create or edit procurement contract type",
      response: "Soft delete via is_active=false",
      severity: "Medium",
    },
  ],
  validationRules: [
    {
      field: "customer search",
      rule: "Search by first name, father name, phone, or customer_code",
      uiBehavior: "Autocomplete dropdown with type-ahead; + button opens add-customer modal",
    },
    {
      field: "product_category",
      rule: "Name required; max 100 chars",
      uiBehavior: "Simple admin list — no sort_order or separate Dari name field",
    },
    {
      field: "weighing rate",
      rule: "Positive decimal; default 10 AFN/ton",
      uiBehavior: "Admin sets current rate; effective_from for history",
    },
    {
      field: "uploaded bank receipt",
      rule: "PDF, JPG, PNG; max 10 MB; all four core fields required",
      uiBehavior: "Standalone form or inline on parent transaction",
    },
    {
      field: "branch",
      rule: "Name required; status enum active | inactive",
      uiBehavior: "Simple admin list — id auto-generated; no province, address, or manager fields",
    },
    {
      field: "property type",
      rule: "Name required; is_active boolean",
      uiBehavior: "Simple admin list — add warehouse, land, office, etc.",
    },
    {
      field: "procurement contract type",
      rule: "Name required; is_active boolean",
      uiBehavior: "Simple admin list — add items, services, construction, stationery, electrical, etc.",
    },
  ],
  integrations: [
    {
      id: "INT-OPR-G001",
      direction: "out",
      module: "MINS — Mines",
      data: "Mining site master data",
      when: "On site create/update",
      note: "Single source of truth for mine list",
    },
    {
      id: "INT-OPR-G002",
      direction: "link",
      module: "FIN — Finance & GL",
      data: "Bank account master",
      when: "On account create/update",
      note: "When FIN module active",
    },
    {
      id: "INT-OPR-G003",
      direction: "out",
      module: "HR, Items, Drivers, Properties",
      data: "branch_id, name, status",
      when: "Employee assignment, جمع اشخاص, driver register, property managing branch",
      note: "Single source of truth for ENCC branches",
    },
    {
      id: "INT-OPR-G004",
      direction: "out",
      module: "Properties — Property Register",
      data: "property_type_id, name, is_active",
      when: "Property create/edit — type dropdown",
      note: "Dynamic property types — admin adds as needed",
    },
    {
      id: "INT-OPR-G005",
      direction: "out",
      module: "Procurement — Projects, Small Procurement",
      data: "contract_type_id, name, is_active",
      when: "Project or small procurement create/edit — type dropdown",
      note: "Shared contract type — items, services, construction, stationery, etc.",
    },
    {
      id: "INT-OPR-G006",
      direction: "out",
      module: "Site — Contract Employees, Daily Work",
      data: "site_id, name, code, is_active",
      when: "Employee registration and daily site reports",
      note: "Mining sites as work locations",
    },
  ],
  crossModuleNotes: [
    "Execution Office departments: Operations (create customers), Mali (receipts), Control (verify), Sales (forms + reports).",
    "Branch (ENT-OPR-G009): id, name, status — consumed by HR, Items, Drivers, Properties.",
    "Property Type (ENT-OPR-G010): dynamic list for Properties register.",
    "Procurement Contract Type (ENT-OPR-G011): items, services, construction, etc. — Projects and Small Procurement.",
    "Mining Site (ENT-OPR-G004): used by Site module for contract employees, groups, and daily work.",
    "Rent and property sections will reuse Bank Account, Bank Receipt Type, and Uploaded Bank Receipt without duplicating tables.",
    "Customer + button: Operations only — see operations section BR-OPR-030.",
  ],
  nfrs: [
    {
      area: "Search",
      requirement: "Customer search returns results within 500ms; supports partial name match",
    },
    {
      area: "Audit",
      requirement: "All price and rate changes in Product Type and Weighing Rate logged with user and date",
    },
  ],
  migration: [
    "Load current product categories, types, and seasonal price list into Product Type table.",
    "Confirm all ENCC bank accounts (product, weighing, rent, others) with Finance.",
    "Set initial weighing rate to 10 AFN/ton.",
    "Import existing customer register with generated customer_code values.",
  ],
  deliverableChecklist: [
    { item: "All general tables defined", done: true },
    { item: "Branch table added (id, name, status)", done: true },
    { item: "Property Type dynamic table added", done: true },
    { item: "Procurement Contract Type dynamic table added", done: true },
    { item: "Cross-section usage documented", done: true },
    { item: "Customer search + add UX specified", done: true },
    { item: "Bank receipt shared table defined", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
