import type { RequirementField } from "@/types/requirements";

/** Shared fields for department item requisition forms (Storage vs Items). */
export const itemRequestCoreFields: RequirementField[] = [
  {
    name: "request_number",
    label: "Request Number",
    labelDari: "شماره درخواست",
    meaning: "Auto-generated unique number on save",
    type: "text",
    required: true,
    example: "SR-0042/1405",
    rules: "System-generated; read-only after create",
  },
  {
    name: "request_date",
    label: "Request Date",
    labelDari: "تاریخ درخواست",
    meaning: "Hijri date when the form was created",
    type: "hijri_date",
    required: true,
    example: "1405/02/19",
  },
  {
    name: "requesting_department_id",
    label: "Requesting Department",
    labelDari: "ریاست درخواست‌کننده",
    meaning: "Department that needs the item — reference to org unit / department master",
    type: "reference",
    required: true,
    example: "Control Department",
  },
  {
    name: "product_name",
    label: "Product / Item Name",
    labelDari: "نام جنس",
    meaning: "Name of the product or material requested",
    type: "text",
    required: true,
    example: "A4 Paper Ream",
  },
  {
    name: "unit",
    label: "Unit",
    labelDari: "واحد",
    meaning: "Unit of measure — piece, box, kg, liter, etc.",
    type: "text",
    required: true,
    example: "box",
  },
  {
    name: "quantity",
    label: "Quantity Requested",
    labelDari: "مقدار درخواستی",
    meaning: "How much the department wants",
    type: "decimal",
    required: true,
    example: "10",
  },
  {
    name: "description",
    label: "Description",
    labelDari: "توضیحات",
    meaning: "Purpose, specifications, or notes for the warehouse/items team",
    type: "longtext",
    required: false,
    example: "For archive filing cabinets — urgent",
  },
  {
    name: "assigned_boss_id",
    label: "Assigned Boss",
    labelDari: "مدیر تأییدکننده",
    meaning: "Which executive receives this for approval — selectable at create time",
    type: "reference",
    required: true,
    example: "Operations / Admin Manager",
    rules: "Creator selects boss; default from department routing rules when configured",
  },
  {
    name: "status",
    label: "Status",
    labelDari: "وضعیت",
    meaning: "Lifecycle status of the request",
    type: "enum",
    required: true,
    example: "pending_boss_approval",
    rules:
      "draft | pending_boss_approval | boss_rejected | pending_warehouse | accepted | rejected | pending_procurement | distributed",
  },
  {
    name: "approved_by",
    label: "Approved By",
    labelDari: "تأیید شده توسط",
    meaning: "Boss who approved",
    type: "reference",
    required: "conditional",
    example: "Operations / Admin Manager",
  },
  {
    name: "approved_at",
    label: "Approval Date",
    labelDari: "تاریخ تأیید",
    meaning: "When boss approved",
    type: "datetime",
    required: "conditional",
    example: "1405/02/19 11:00",
  },
  {
    name: "rejection_reason",
    label: "Rejection Reason",
    labelDari: "دلیل رد",
    meaning: "Required when status is boss_rejected or rejected by warehouse",
    type: "longtext",
    required: "conditional",
    example: "Budget not approved this quarter",
  },
];
