import type { SectionDefinition } from "@/types/requirements";

export const sandaMaliSection: SectionDefinition = {
  id: "sanda-mali",
  name: "Sanda Mali (Financial Voucher)",
  nameDari: "سند مالی",
  enableReview: true,
  description:
    "Foundation of Mali digital accounting. Defines the chart of accounts (general and sub accounts) and سند مالی — the primary voucher used to record balanced debit/credit journal lines. Future Mali tasks (journal summaries, balances, cash flow) build on data created here; they are out of scope for this section.",
  status: "draft",
  currentTool: "Paper ledger books and handwritten سند مالی forms",
  summary: [
    "General accounts — top-level books (bank, cash, etc.) with name, code, status",
    "Sub accounts — detail accounts under each general account; created during account setup (not a separate main screen)",
    "Account-based permissions — each user is assigned to specific general accounts they can view and post to",
    "سند مالی — balanced voucher with DR/CR lines and attachment; mali_year select (current year ± 5)",
    "Dedicated سند مالی finder page — detailed search, filter by account/sub-account/year, view full voucher and print",
    "General and sub accounts cannot be deleted when they have posted journal lines",
    "Fiscal year close — closing accounts (e.g. year-end) hidden from new-year vouchers; regular accounts continue",
    "Out of scope here: trial balance, ledger balances, cash flow, and other derived reports",
  ],
  precededBy: [],
  followedBy: [
    { moduleId: "balance", sectionId: "balance", label: "Balance / derived accounting reports (future)" },
  ],
  relatedSections: ["mali", "balance", "general-tables"],
  roles: [
    {
      role: "Mali Accountant",
      location: "HQ — مالی",
      mainActions:
        "Create سند مالی for assigned accounts, maintain sub accounts under those accounts, attach scanned voucher",
      approval: false,
      readOnly: false,
    },
    {
      role: "Mali Clerk",
      location: "HQ — مالی",
      mainActions:
        "Search and print سند مالی on the finder page; view vouchers for assigned accounts only",
      approval: false,
      readOnly: false,
    },
    {
      role: "Financial Manager",
      location: "HQ",
      mainActions:
        "Assign account access to users, review account setup, approve account deactivation",
      approval: true,
      readOnly: false,
    },
    {
      role: "Account Supervisor",
      location: "HQ — مالی / Branch",
      mainActions:
        "Manages one or more general accounts — creates sub accounts and posts سند مالی only for assigned accounts",
      approval: false,
      readOnly: false,
    },
    {
      role: "Auditor",
      location: "HQ",
      mainActions: "Read-only view of all accounts, vouchers, attachments, and audit trail",
      approval: false,
      readOnly: true,
    },
  ],
  entities: [
    {
      id: "ENT-MALI-001",
      name: "General Account",
      description:
        "Top-level account book — e.g. Bank, Cash, Receivables. Parent of sub accounts. Not deletable when any سند مالی line references it (directly or via sub account).",
      fields: [
        {
          name: "name",
          label: "Account Name",
          labelDari: "نام حساب",
          meaning: "Display name of the general account book",
          type: "text",
          required: true,
          example: "Bank Accounts",
        },
        {
          name: "code",
          label: "Account Code",
          labelDari: "کود حساب",
          meaning: "Unique short code for reporting and search",
          type: "text",
          required: true,
          example: "1100",
          rules: "Unique across all general accounts; immutable after first سند مالی posted",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | inactive",
          type: "enum",
          required: true,
          example: "active",
          rules: "inactive hides from new سند مالی entry pickers; existing lines remain visible in history",
        },
        {
          name: "account_type",
          label: "Account Type",
          labelDari: "نوع حساب",
          meaning: "regular | closing",
          type: "enum",
          required: true,
          example: "regular",
          rules:
            "closing = year-end accounts only; after fiscal year close, hidden from new-year voucher pickers",
        },
      ],
    },
    {
      id: "ENT-MALI-002",
      name: "Sub Account",
      description:
        "Detail account under a general account — e.g. Bank of Branch 1, Cash of Branch 2. Created alongside general account setup. Used as the primary filter dimension on the سند مالی finder page.",
      fields: [
        {
          name: "name",
          label: "Sub Account Name",
          labelDari: "نام حساب فرعی",
          meaning: "Display name of the detail account",
          type: "text",
          required: true,
          example: "Da Afghanistan Bank — Branch 1",
        },
        {
          name: "account_id",
          label: "General Account",
          labelDari: "حساب عمومی",
          meaning: "Reference → General Account (ENT-MALI-001)",
          type: "reference",
          required: true,
          example: "1100 — Bank Accounts",
        },
        {
          name: "code",
          label: "Sub Account Code",
          labelDari: "کود حساب فرعی",
          meaning: "Unique code within the parent general account (or globally unique — confirm with ENCC)",
          type: "text",
          required: true,
          example: "1100-01",
          rules: "Unique per general account; immutable after first سند مالی line posted",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "active | inactive",
          type: "enum",
          required: true,
          example: "active",
          rules: "inactive hides from new entry pickers for that general account",
        },
      ],
    },
    {
      id: "ENT-MALI-003",
      name: "Sanda Mali (Financial Voucher)",
      description:
        "سند مالی — the core financial document. Header holds voucher metadata; lines are journal entries (ENT-MALI-004). Total debit must equal total credit before save.",
      fields: [
        {
          name: "id",
          label: "Record ID",
          labelDari: "شناسه",
          meaning: "Internal database primary key",
          type: "text",
          required: true,
          example: "uuid-internal",
          rules: "System-generated; not shown to users as the main reference",
        },
        {
          name: "unique_id",
          label: "System Voucher Number",
          labelDari: "شماره سیستم سند",
          meaning: "ENCC system-generated unique سند مالی number for tracking and search",
          type: "text",
          required: true,
          example: "SM-0042/1405",
          rules: "Auto-generated on create; unique; used when no paper file_id is provided",
        },
        {
          name: "file_id",
          label: "Paper File Number",
          labelDari: "شماره فایل کاغذی",
          meaning: "Optional number from the physical سند مالی file / ledger book",
          type: "text",
          required: false,
          example: "127/1405",
          rules:
            "Optional — clerks may continue with system unique_id only; when entered, searchable alongside unique_id",
        },
        {
          name: "date",
          label: "Voucher Date",
          labelDari: "تاریخ سند",
          meaning: "Transaction date on the سند مالی",
          type: "hijri_date",
          required: true,
          example: "1405/02/19",
        },
        {
          name: "mali_year",
          label: "Mali Year (Fiscal Year)",
          labelDari: "سال مالی",
          meaning:
            "Fiscal year this voucher belongs to — user selects from dropdown; ENCC confirmed",
          type: "enum",
          required: true,
          example: "1405",
          rules:
            "Required select (not free text). Dropdown lists Solar Hijri years from 5 years before through 5 years after the current year (11 options total). Defaults to current year on new voucher. Used as primary filter on finder and future balance reports.",
        },
        {
          name: "description",
          label: "Description",
          labelDari: "توضیحات",
          meaning: "Summary / مضمون of the voucher",
          type: "longtext",
          required: true,
          example: "Transfer from cash to bank — Branch 1",
        },
        {
          name: "user_id",
          label: "Created By",
          labelDari: "ثبت شده توسط",
          meaning: "Mali user who created the voucher",
          type: "reference",
          required: true,
          example: "Mali Accountant — Ahmad",
        },
        {
          name: "attachment",
          label: "Voucher Attachment",
          labelDari: "ضمیمه سند",
          meaning: "Scan or PDF of the completed paper سند مالی",
          type: "file",
          required: true,
          example: "sanda_mali_127_1405.pdf",
          rules: "PDF, JPG, PNG; max 10 MB",
        },
        {
          name: "total_debit",
          label: "Total Debit",
          labelDari: "مجموع بدهکار",
          meaning: "Sum of all line debits — must equal total_credit",
          type: "decimal",
          required: true,
          example: "500000",
          rules: "Computed; read-only on save",
        },
        {
          name: "total_credit",
          label: "Total Credit",
          labelDari: "مجموع بستانکار",
          meaning: "Sum of all line credits — must equal total_debit",
          type: "decimal",
          required: true,
          example: "500000",
          rules: "Computed; read-only on save",
        },
        {
          name: "status",
          label: "Status",
          labelDari: "وضعیت",
          meaning: "draft | posted",
          type: "enum",
          required: true,
          example: "posted",
          rules: "draft allows unbalanced lines for work-in-progress; posted requires balance + attachment",
        },
      ],
    },
    {
      id: "ENT-MALI-004",
      name: "Sanda Mali Journal Line",
      description:
        "Individual debit/credit line on a سند مالی. User adds as many lines as needed; voucher must balance before posting.",
      fields: [
        {
          name: "sanda_mali_id",
          label: "Sanda Mali",
          labelDari: "سند مالی",
          meaning: "Parent voucher reference",
          type: "reference",
          required: true,
          example: "SM-0042/1405",
        },
        {
          name: "line_number",
          label: "Line Number",
          labelDari: "شماره سطر",
          meaning: "Sequence within the voucher",
          type: "text",
          required: true,
          example: "1",
          rules: "Auto-incremented per voucher",
        },
        {
          name: "account_id",
          label: "General Account",
          labelDari: "حساب عمومی",
          meaning: "Selected general account for this line",
          type: "reference",
          required: true,
          example: "1100 — Bank Accounts",
        },
        {
          name: "sub_account_id",
          label: "Sub Account",
          labelDari: "حساب فرعی",
          meaning: "Selected sub account when parent has active sub accounts",
          type: "reference",
          required: "conditional",
          example: "1100-01 — Da Afghanistan Bank Branch 1",
          rules:
            "Required when the general account has one or more active sub accounts; hidden when none exist — general account alone is sufficient",
        },
        {
          name: "debit",
          label: "Debit (DR)",
          labelDari: "بدهکار",
          meaning: "Debit amount in AFN for this line",
          type: "decimal",
          required: "conditional",
          example: "250000",
          rules: "Either debit or credit must be > 0 per line, not both on same line",
        },
        {
          name: "credit",
          label: "Credit (CR)",
          labelDari: "بستانکار",
          meaning: "Credit amount in AFN for this line",
          type: "decimal",
          required: "conditional",
          example: "0",
          rules: "Either debit or credit must be > 0 per line, not both on same line",
        },
        {
          name: "details",
          label: "Line Details",
          labelDari: "جزئیات",
          meaning: "Narration / explanation for this line",
          type: "longtext",
          required: false,
          example: "Cash deposit to branch 1 operating account",
        },
      ],
    },
    {
      id: "ENT-MALI-005",
      name: "Account User Access",
      description:
        "Maps Mali users to the general accounts they may work with. Different staff manage different accounts — all voucher create, view, and search actions are scoped to assigned accounts.",
      fields: [
        {
          name: "user_id",
          label: "User",
          labelDari: "کاربر",
          meaning: "Mali department user",
          type: "reference",
          required: true,
          example: "Ahmad — Mali Accountant",
        },
        {
          name: "general_account_id",
          label: "General Account",
          labelDari: "حساب عمومی",
          meaning: "Reference → General Account (ENT-MALI-001)",
          type: "reference",
          required: true,
          example: "1100 — Bank Accounts",
        },
        {
          name: "access_level",
          label: "Access Level",
          labelDari: "سطح دسترسی",
          meaning: "view | create_sanda | manage_account",
          type: "enum",
          required: true,
          example: "create_sanda",
          rules:
            "view = search/print vouchers touching this account; create_sanda = post new vouchers with lines on this account; manage_account = edit account, sub accounts, and vouchers",
        },
        {
          name: "assigned_by",
          label: "Assigned By",
          labelDari: "تعیین شده توسط",
          meaning: "Financial Manager who granted access",
          type: "reference",
          required: true,
          example: "Financial Manager",
        },
        {
          name: "assigned_at",
          label: "Assigned Date",
          labelDari: "تاریخ تعیین",
          meaning: "When access was granted",
          type: "datetime",
          required: true,
          example: "1405/02/10 09:00",
        },
      ],
    },
  ],
  workflows: [
    {
      id: "WF-MALI-010",
      name: "Maintain general accounts",
      trigger: "New account book needed (e.g. new bank category)",
      startActor: "Mali Accountant",
      endState: "General account active in chart",
      flowDiagram: "Create → set name, code, status → available for sub accounts and سند مالی",
      steps: [
        {
          step: 1,
          actor: "Mali Accountant",
          action: "Create general account",
          input: "name, code, status=active",
          output: "ENT-MALI-001 record",
        },
        {
          step: 2,
          actor: "Mali Accountant",
          action: "Deactivate instead of delete when retired",
          input: "Account with historical lines",
          output: "status=inactive; delete blocked",
        },
      ],
    },
    {
      id: "WF-MALI-011",
      name: "Add sub accounts (during account setup)",
      trigger: "General account needs detail accounts (e.g. per branch)",
      startActor: "Account Supervisor or Mali Accountant",
      endState: "Sub accounts available in voucher line picker and finder filters",
      flowDiagram:
        "Open general account → add sub account (name, code, status) → appears in سند مالی form and finder",
      steps: [
        {
          step: 1,
          actor: "Account Supervisor",
          action: "Open general account they manage",
          input: "Assigned general account (account access required)",
          output: "Account detail with sub account list",
        },
        {
          step: 2,
          actor: "Account Supervisor",
          action: "Create sub account",
          input: "name, code, status=active",
          output: "ENT-MALI-002 — available in voucher lines and finder filters",
        },
      ],
    },
    {
      id: "WF-MALI-012",
      name: "Create سند مالی with balanced entries",
      trigger: "Financial transaction to record in Mali books",
      startActor: "Mali Accountant",
      endState: "Posted سند مالی with balanced lines and attachment",
      flowDiagram:
        "Header (date, mali_year, description, optional file_id) → add lines (account, sub account if any, DR/CR, details) → balance check → attach scan → post",
      mermaid: `flowchart TD
  H[Enter voucher header] --> L[Add journal line]
  L --> P{Sub accounts exist?}
  P -->|Yes| S[Select general + sub account]
  P -->|No| G[Select general account only]
  S --> D[Enter DR or CR + details]
  G --> D
  D --> M{Add more lines?}
  M -->|Yes| L
  M -->|No| B{DR total = CR total?}
  B -->|No| L
  B -->|Yes| A[Attach file]
  A --> F[Post سند مالی]`,
      steps: [
        {
          step: 1,
          actor: "Mali Accountant",
          action: "Start new سند مالی",
          input: "date, mali_year, description, optional file_id",
          output: "Draft voucher with system unique_id",
        },
        {
          step: 2,
          actor: "Mali Accountant",
          action: "Add journal line — select general account",
          input: "Active general account",
          output: "If sub accounts exist for parent → show sub account dropdown; else general account only",
        },
        {
          step: 3,
          actor: "Mali Accountant",
          action: "Enter DR or CR and line details",
          input: "Amount on one side only; optional details",
          output: "Line added; running DR/CR totals shown",
        },
        {
          step: 4,
          actor: "Mali Accountant",
          action: "Repeat lines until transaction fully captured",
          input: "As many lines as needed",
          output: "All lines listed with running balance indicator",
        },
        {
          step: 5,
          actor: "System",
          action: "Validate voucher balance",
          input: "Sum of debits and credits",
          output: "Block post if totals differ; show difference amount",
          decision: true,
        },
        {
          step: 6,
          actor: "Mali Accountant",
          action: "Attach scanned سند مالی and post",
          input: "PDF or image of paper voucher",
          output: "status=posted; user_id and timestamp logged",
        },
      ],
    },
    {
      id: "WF-MALI-013",
      name: "Find and view سند مالی (dedicated finder page)",
      trigger: "User needs to locate a specific voucher or review account activity",
      startActor: "Mali Clerk / Accountant",
      endState: "Voucher found — full detail and print available",
      flowDiagram:
        "Open finder → filter by account, sub account, year, dates, numbers → select result → view lines + attachment → print",
      mermaid: `flowchart LR
  F[Finder Page] --> S[Apply Filters]
  S --> L[Result List]
  L --> D[Voucher Detail]
  D --> P[Print / Export]`,
      steps: [
        {
          step: 1,
          actor: "Mali Clerk",
          action: "Open dedicated سند مالی finder page",
          input: "User's assigned accounts scope the default filter",
          output: "Search panel with all filter fields",
        },
        {
          step: 2,
          actor: "Mali Clerk",
          action: "Apply filters",
          input:
            "unique_id, file_id, mali_year, Hijri date range, general account, sub account, description, created by, amount range",
          output: "Filtered voucher list — newest first",
        },
        {
          step: 3,
          actor: "Mali Clerk",
          action: "Select voucher from results",
          input: "Click row",
          output: "Detail panel: header, all journal lines, attachment preview, audit info",
        },
        {
          step: 4,
          actor: "Mali Clerk",
          action: "Print or export voucher",
          input: "Selected voucher",
          output: "PDF with header + lines for filing",
        },
      ],
    },
    {
      id: "WF-MALI-014",
      name: "Assign account access to users",
      trigger: "New Mali staff or changed account responsibility",
      startActor: "Financial Manager",
      endState: "User can only see and post to assigned accounts",
      flowDiagram: "Financial Manager → assign user + general account + access level",
      steps: [
        {
          step: 1,
          actor: "Financial Manager",
          action: "Open account access management",
          input: "User list, general account list",
          output: "ENT-MALI-005 assignment screen",
        },
        {
          step: 2,
          actor: "Financial Manager",
          action: "Grant access",
          input: "user_id, general_account_id, access_level",
          output: "User sees only those accounts in form picker and finder",
        },
      ],
    },
    {
      id: "WF-MALI-015",
      name: "Fiscal year close — hide closing accounts",
      trigger: "End of mali year — books closed",
      startActor: "Financial Manager",
      endState: "Closing accounts inactive for new year entry",
      flowDiagram: "Year close → account_type=closing hidden from new سند مالی in next mali_year",
      steps: [
        { step: 1, actor: "Financial Manager", action: "Close fiscal year", input: "mali_year", output: "Year marked closed for Mali ledgers" },
        { step: 2, actor: "System", action: "Hide closing accounts from pickers", input: "New year vouchers", output: "Only regular accounts shown" },
      ],
    },
  ],
  statusLifecycles: [
    {
      entity: "General Account",
      from: "—",
      action: "create",
      to: "active",
      actor: "Mali Accountant",
    },
    {
      entity: "General Account",
      from: "active",
      action: "deactivate",
      to: "inactive",
      actor: "Mali Accountant / Financial Manager",
      notes: "Delete blocked if any journal line references this account or its sub accounts",
    },
    {
      entity: "Sub Account",
      from: "—",
      action: "create",
      to: "active",
      actor: "Mali Accountant",
    },
    {
      entity: "Sub Account",
      from: "active",
      action: "deactivate",
      to: "inactive",
      actor: "Mali Accountant",
      notes: "Delete blocked if any journal line references this sub account",
    },
    {
      entity: "Sanda Mali",
      from: "draft",
      action: "post",
      to: "posted",
      actor: "Mali Accountant",
      notes: "Requires balanced lines, attachment, and all required header fields",
    },
  ],
  businessRules: [
    {
      id: "BR-MALI-001",
      rule: "General account code must be unique",
      trigger: "Create / update code",
      response: "Block duplicate",
      severity: "Critical",
    },
    {
      id: "BR-MALI-002",
      rule: "Sub account code must be unique within its general account",
      trigger: "Create sub account",
      response: "Block duplicate",
      severity: "Critical",
    },
    {
      id: "BR-MALI-003",
      rule: "Cannot delete general account when it or any of its sub accounts have posted journal lines",
      trigger: "Delete general account",
      response: "Block; offer deactivate instead",
      severity: "Critical",
    },
    {
      id: "BR-MALI-004",
      rule: "Cannot delete sub account when it has posted journal lines",
      trigger: "Delete sub account",
      response: "Block; offer deactivate instead",
      severity: "Critical",
    },
    {
      id: "BR-MALI-005",
      rule: "When general account has active sub accounts, each journal line must select a sub account",
      trigger: "Add line",
      response: "Block save if sub_account_id missing",
      severity: "Critical",
    },
    {
      id: "BR-MALI-006",
      rule: "When general account has no active sub accounts, sub account selector is hidden — general account is sufficient",
      trigger: "Add line",
      response: "sub_account_id stored as null",
      severity: "High",
    },
    {
      id: "BR-MALI-007",
      rule: "Each journal line must have either debit or credit > 0, not both on the same line",
      trigger: "Add / edit line",
      response: "Block invalid line",
      severity: "Critical",
    },
    {
      id: "BR-MALI-008",
      rule: "سند مالی cannot be posted unless total debit equals total credit",
      trigger: "Post voucher",
      response: "Block and show difference",
      severity: "Critical",
    },
    {
      id: "BR-MALI-009",
      rule: "Posted سند مالی requires attachment file",
      trigger: "Post voucher",
      response: "Block if attachment missing",
      severity: "Critical",
    },
    {
      id: "BR-MALI-010",
      rule: "mali_year is required — must be chosen from the year select (current Solar Hijri year ± 5 years)",
      trigger: "Create / post voucher",
      response: "Block if empty or not in allowed year list",
      severity: "Critical",
    },
    {
      id: "BR-MALI-011",
      rule: "System unique_id is always generated; paper file_id remains optional",
      trigger: "Create voucher",
      response: "unique_id auto-assigned; file_id user-entered if available",
      severity: "High",
    },
    {
      id: "BR-MALI-012",
      rule: "Posted vouchers are immutable — corrections require a new reversing سند مالی (future rule)",
      trigger: "Edit posted voucher",
      response: "Block edit; audit trail only",
      severity: "High",
    },
    {
      id: "BR-MALI-013",
      rule: "Users may only create سند مالی lines on general accounts assigned with create_sanda or manage_account access",
      trigger: "Add journal line / post voucher",
      response: "Block line if user lacks access to that general account",
      severity: "Critical",
    },
    {
      id: "BR-MALI-014",
      rule: "Finder page and voucher list show only سند مالی records that touch at least one of the user's assigned accounts",
      trigger: "Search / list vouchers",
      response: "Filter results by ENT-MALI-005; auditor sees all",
      severity: "Critical",
    },
    {
      id: "BR-MALI-015",
      rule: "Account picker on new voucher form lists only general accounts the current user is assigned to",
      trigger: "Open voucher form",
      response: "Dropdown scoped to user's account access",
      severity: "Critical",
    },
    {
      id: "BR-MALI-016",
      rule: "Only Financial Manager can assign or revoke account user access",
      trigger: "Create / delete ENT-MALI-005",
      response: "Block for other roles",
      severity: "Critical",
    },
    {
      id: "BR-MALI-017",
      rule: "Voucher must include at least one line on an account the user can access; other lines may reference accounts managed by other users on the same voucher",
      trigger: "Post voucher",
      response: "Allow cross-account vouchers when balanced; each user posts only their side in practice — confirm with ENCC",
      severity: "Medium",
    },
    {
      id: "BR-MALI-018",
      rule: "Closing accounts (account_type=closing) hidden from سند مالی pickers after fiscal year close",
      trigger: "New year voucher in closed year+1",
      response: "Filter closing accounts from account dropdown",
      severity: "Critical",
    },
  ],
  permissionsMatrix: [
    { action: "Assign account access (ENT-MALI-005)", archiveClerk: "—", executive: "A", deptStaff: "—", auditor: "—" },
    { action: "View chart of accounts (assigned only)", archiveClerk: "—", executive: "R", deptStaff: "R*", auditor: "R" },
    { action: "Create / edit general accounts", archiveClerk: "—", executive: "—", deptStaff: "C*", auditor: "—" },
    { action: "Create / edit sub accounts", archiveClerk: "—", executive: "—", deptStaff: "C*", auditor: "—" },
    { action: "سند مالی finder — search / print / export", archiveClerk: "—", executive: "R", deptStaff: "R*", auditor: "R" },
    { action: "Create سند مالی (draft)", archiveClerk: "—", executive: "—", deptStaff: "C*", auditor: "—" },
    { action: "Post سند مالی", archiveClerk: "—", executive: "—", deptStaff: "C*", auditor: "—" },
    { action: "Deactivate account (with records)", archiveClerk: "—", executive: "A", deptStaff: "—", auditor: "—" },
    { action: "Delete account with no records", archiveClerk: "—", executive: "—", deptStaff: "D*", auditor: "—" },
  ],
  reports: [
    {
      id: "RPT-MALI-010",
      name: "سند مالی Finder (primary screen)",
      purpose:
        "Dedicated detailed page for finding a specific voucher — most-used Mali screen after data entry. Filter by account, sub account, year, dates, numbers, description; view full detail and print.",
      filters:
        "unique_id, file_id, mali_year, Hijri date from/to, general account, sub account, description (contains), created by, amount min/max, status — scoped to user's assigned accounts",
      columns:
        "Result list: unique_id, file_id, date, mali_year, description, total, created by | Detail: header + all lines + attachment",
      export: "PDF (single voucher), Excel (result list)",
    },
    {
      id: "RPT-MALI-011",
      name: "Sanda Mali Register",
      purpose: "Bulk export of posted vouchers for a fiscal year (same data as finder, export mode)",
      filters: "mali_year, Hijri date range, account, sub account",
      columns: "unique_id, file_id, date, mali_year, description, total DR/CR, created by, status",
      export: "PDF, Excel",
    },
    {
      id: "RPT-MALI-012",
      name: "Sanda Mali Detail Print",
      purpose: "Print single voucher with all journal lines for filing — opened from finder detail panel",
      filters: "Voucher unique_id or file_id",
      columns: "header + lines: account, sub account, DR, CR, details",
      export: "PDF",
    },
    {
      id: "RPT-MALI-013",
      name: "General Account List",
      purpose: "Chart of accounts overview for Financial Manager",
      filters: "Status",
      columns: "code, name, status, sub account count, assigned users",
      export: "PDF, Excel",
    },
    {
      id: "RPT-MALI-014",
      name: "Account User Access List",
      purpose: "Who can work with which general accounts",
      filters: "User, general account, access level",
      columns: "user, account, access level, assigned by, assigned at",
      export: "PDF, Excel",
    },
  ],
  validationRules: [
    { field: "code (general account)", rule: "Required, unique, max 20 chars", uiBehavior: "Text input; immutable after first posted line" },
    { field: "code (sub account)", rule: "Required, unique per parent, max 30 chars", uiBehavior: "Text input on sub account page" },
    { field: "status", rule: "enum: active | inactive", uiBehavior: "Toggle or dropdown" },
    { field: "file_id", rule: "Optional; max 50 chars", uiBehavior: "Text input on voucher header" },
    { field: "unique_id", rule: "System-generated; read-only", uiBehavior: "Shown on create; primary search key" },
    { field: "mali_year", rule: "Required select; Solar Hijri years from (current − 5) to (current + 5)", uiBehavior: "Dropdown only — no manual entry; default = current year" },
    { field: "date", rule: "Required Hijri date", uiBehavior: "Shamsi date picker" },
    { field: "sub_account_id", rule: "Conditional — required only when parent has active sub accounts", uiBehavior: "Dynamic: hide selector when parent has zero sub accounts" },
    { field: "debit / credit", rule: "One side > 0 per line; voucher totals must match to post", uiBehavior: "Running balance footer on entry form" },
    { field: "attachment", rule: "Required on post; PDF, JPG, PNG; max 10 MB", uiBehavior: "File upload on voucher" },
    { field: "account access", rule: "User sees only assigned general accounts in pickers and finder", uiBehavior: "Scoped dropdowns; Financial Manager assigns via ENT-MALI-005" },
    { field: "finder page", rule: "Dedicated full-page UI: filter panel + result list + detail panel side by side", uiBehavior: "See interactive sample on this section page" },
  ],
  integrations: [
    {
      id: "INT-MALI-001",
      direction: "out",
      module: "BAL — Balance",
      data: "Posted journal lines by account, sub account, mali_year",
      when: "Future balance and ledger tasks",
      note: "Not in scope for this section — data model prepared for downstream use",
    },
    {
      id: "INT-MALI-002",
      direction: "link",
      module: "DOC — Document Management",
      data: "سند مالی attachment files",
      when: "On file upload",
      note: "When active",
    },
  ],
  crossModuleNotes: [
    "This section is the foundation for digitizing Mali financial records. Journal summaries, account balances, cash flow, and trial balance will be documented in separate future sections (likely Balance module).",
    "Separate from existing Mali bank receipt workflow (section: mali) — سند مالی is general ledger voucher entry, not purchase-request receipts.",
    "Primary UI is the سند مالی finder page (not a sub-account management page) — optimized for locating specific vouchers with rich filters.",
    "Permissions are account-based: different Mali staff manage different general accounts via ENT-MALI-005. Dept staff column * = only for accounts assigned to that user.",
    "Interactive sample form and finder on this requirements page are preview only — data is not saved.",
    "ENCC confirmed: mali_year is a select listing Solar Hijri years from 5 years before to 5 years after the current year (11 options).",
  ],
  nfrs: [
    { area: "Performance", requirement: "سند مالی finder returns filtered results under 2 seconds for 50,000 vouchers" },
    { area: "Usability", requirement: "Voucher entry form shows live DR/CR balance indicator while adding lines" },
    { area: "Security", requirement: "All list, search, and form actions respect account user access assignments" },
    { area: "Localization", requirement: "Dari labels on all fields; Hijri dates per module standards" },
    { area: "Audit", requirement: "Immutable posted vouchers; full audit log on account and voucher changes" },
  ],
  edgeCases: [
    {
      id: "EC-MALI-001",
      scenario: "General account has sub accounts but clerk picks wrong parent on a line.",
      behavior: "Sub account dropdown only shows children of selected general account.",
      handler: "UI constraint",
    },
    {
      id: "EC-MALI-002",
      scenario: "Clerk adds lines but voucher is unbalanced.",
      behavior: "Post blocked; show difference amount; draft can be saved.",
      handler: "Mali Accountant",
    },
    {
      id: "EC-MALI-003",
      scenario: "Paper file_id duplicates an older year entry.",
      behavior: "Warn but allow — file_id is not globally unique; unique_id is the system key.",
      handler: "Mali Accountant",
    },
    {
      id: "EC-MALI-004",
      scenario: "Attempt to delete general account that has posted lines.",
      behavior: "Block delete; suggest status=inactive.",
      handler: "System",
    },
    {
      id: "EC-MALI-005",
      scenario: "All sub accounts under a general account deactivated — new lines use general account only.",
      behavior: "Sub account selector hidden until at least one active sub account exists.",
      handler: "System",
    },
    {
      id: "EC-MALI-006",
      scenario: "Single-line voucher (one DR and one CR on two lines minimum).",
      behavior: "Minimum two lines required for a balanced double-entry voucher.",
      handler: "Mali Accountant",
    },
  ],
  deliverableChecklist: [
    { item: "Three core tables documented (general account, sub account, سند مالی + lines)", done: true },
    { item: "Account-based permissions (ENT-MALI-005)", done: true },
    { item: "Balanced entry workflow and business rules", done: true },
    { item: "سند مالی finder page requirements (detailed search + detail view)", done: true },
    { item: "Interactive sample form and finder (preview only)", done: true },
    { item: "Account delete protection when records exist", done: true },
    { item: "Sample paper سند مالی scan from ENCC", done: false },
    { item: "ENCC confirmation of fiscal year (mali_year) rules", done: true },
    { item: "ENCC sign-off", done: false },
  ],
};
